#!/usr/bin/env bash
set -euo pipefail

# v48.19 FACET-BRIDGE: support-aware factorized independent-tail evidence
# correction. The v48.13 top-k proposal and source evidence experts remain frozen.
REPO="${OCRAP_REPO:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO"
export PYTHONPATH="$REPO/src${PYTHONPATH:+:$PYTHONPATH}"

RUN="${RUN:?RUN is required}"
INIT_CKPT="${INIT_CKPT:?INIT_CKPT is required}"
VARIANT="${VARIANT:?VARIANT is required}"
TRAIN_MIX="${TRAIN_MIX:?TRAIN_MIX is required}"
VAL_MIX="${VAL_MIX:?VAL_MIX is required}"
GROUP_INDEX="${GROUP_INDEX:?GROUP_INDEX is required}"
TRAIN_GPU="${TRAIN_GPU:-0}"
MODEL_DIR="${MODEL_DIR:-$RUN/model_v48_trac_sr}"
CAL_DIR="${CAL_DIR:-$RUN/calibration}"
mkdir -p "$RUN/logs" "$MODEL_DIR" "$CAL_DIR"

PROPOSAL_TOP_K="${PROPOSAL_TOP_K:-3}"
CAL_HIDDEN="${EVIDENCE_CALIBRATOR_HIDDEN:-12}"
CAL_SCALE="${EVIDENCE_CALIBRATOR_SCALE:-0.50}"
CAL_MODE="${EVIDENCE_CALIBRATOR_MODE:-dual_tail_context}"
CAL_CONTEXT="${EVIDENCE_CALIBRATOR_CONTEXT:-true}"
CAL_CONTEXT_DETACH="${EVIDENCE_CALIBRATOR_CONTEXT_DETACH:-true}"
CAL_CONTEXT_SOURCE="${EVIDENCE_CALIBRATOR_CONTEXT_SOURCE:-tournament}"
MAX_CALIBRATOR_PARAMS="${MAX_EVIDENCE_CALIBRATOR_PARAMS:-8000}"
STRATIFIED_BATCHES="${GROUP_BATCH_STRATIFIED:-true}"
BATCH_BALANCED="${ORDINAL_EVIDENCE_BATCH_BALANCED:-true}"
MIN_POSITIVE_RECALL="${POLICY_METRIC_MIN_POSITIVE_RECALL:-0.25}"
RECALL_SHORTFALL_WEIGHT="${POLICY_METRIC_RECALL_SHORTFALL_WEIGHT:-4.0}"
INDEPENDENT_TAILS="${ORDINAL_EVIDENCE_INDEPENDENT_TAILS:-true}"
BALANCED_REPLACES_ERM="${ORDINAL_EVIDENCE_BALANCED_REPLACES_ERM:-true}"
BEST_METRIC_NAME="${BEST_METRIC:-direct_facet_selection_risk}"
CAL_SHARED="${EVIDENCE_CALIBRATOR_SHARED:-true}"
CAL_REGIME_SCALE="${EVIDENCE_CALIBRATOR_REGIME_SCALE:-0.25}"
FACTORIZED_HARM="${ORDINAL_EVIDENCE_FACTORIZED_HARM:-true}"

cat > "$RUN/STAGE_ARCHITECTURE.json" <<JSON
{
  "version": "v48.19-FACET-BRIDGE",
  "source_checkpoint": "$INIT_CKPT",
  "training_role": "factorized_component_veto_shared_dual_tail_scene_disjoint_evidence_correction",
  "frozen_policy": "v48.13_topk_recovery_proposal",
  "frozen_source_evidence": true,
  "trainable": ["direct_evidence_shared_calibrator", "direct_evidence_calibrators"],
  "evidence_parameterization": "$CAL_MODE",
  "context_source": "$CAL_CONTEXT_SOURCE",
  "independent_evidence_tails": $INDEPENDENT_TAILS,
  "factorized_component_harm": $FACTORIZED_HARM,
  "shared_cross_regime_calibrator": $CAL_SHARED,
  "regime_residual_scale": $CAL_REGIME_SCALE,
  "balanced_replaces_group_erm": $BALANCED_REPLACES_ERM,
  "context_features_enabled": $CAL_CONTEXT,
  "context_features": "frozen_candidate_nominal_relative_representation_plus_source_evidence_and_rank_margins",
  "calibrator_hidden": $CAL_HIDDEN,
  "calibrator_residual_scale": $CAL_SCALE,
  "proposal_top_k": $PROPOSAL_TOP_K,
  "batch_class_balance": $BATCH_BALANCED,
  "stratified_group_batches": $STRATIFIED_BATCHES,
  "checkpoint_min_positive_recall": $MIN_POSITIVE_RECALL,
  "test_roots_read": false
}
JSON

TRAIN_OCRAP_ROOT="${TRAIN_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
EVAL_OCRAP_ROOT="${EVAL_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
TRAIN_MIX="$TRAIN_MIX" VAL_MIX="$VAL_MIX" CAL_MIX="$VAL_MIX" \
RUN="$RUN" MODEL_DIR="$MODEL_DIR" CAL_DIR="$CAL_DIR" \
INIT_CKPT="$INIT_CKPT" VARIANT="$VARIANT" TRAIN_GPU="$TRAIN_GPU" GROUP_INDEX="$GROUP_INDEX" \
NUM_WORKERS="${NUM_WORKERS:-4}" PREFETCH_FACTOR="${PREFETCH_FACTOR:-2}" BATCH_SIZE="${BATCH_SIZE:-72}" \
EPOCHS="${EVIDENCE_ADAPT_EPOCHS:-20}" PATIENCE="${EVIDENCE_ADAPT_PATIENCE:-5}" \
LR="${EVIDENCE_ADAPT_LR:-0.00030}" ENCODER_LR_SCALE=0 ENCODER_ANCHOR_WEIGHT=0 \
TRAINABLE_PARAM_PREFIXES='direct_evidence_shared_calibrator,direct_evidence_calibrators' \
STRICT_INIT_PREFIXES='direct_preference_set_ranker,direct_delta_adapters' \
BEST_METRIC="$BEST_METRIC_NAME" BEST_METRIC_MIN_DELTA="${BEST_METRIC_MIN_DELTA:-0.00001}" \
SKIP_POST_TRAIN_CALIBRATION=1 EXACT_TEACHER_PCD=true \
SET_CONTEXT_ENABLED=false PREFERENCE_HEAD_ENABLED=false PREFERENCE_CONTEXT_ENABLED=false RELATIVE_INCLUDE_ABSOLUTE=false \
SET_TOURNAMENT_ENABLED=true SET_TOURNAMENT_HIDDEN="${SET_TOURNAMENT_HIDDEN:-48}" SET_TOURNAMENT_HEADS="${SET_TOURNAMENT_HEADS:-4}" \
SET_TOURNAMENT_DROPOUT="${SET_TOURNAMENT_DROPOUT:-0.05}" SET_TOURNAMENT_REPLACE_BASE=true \
DELTA_HEAD_ENABLED=true DELTA_MODE=ordinal_evidence DELTA_HIDDEN="${EVIDENCE_HIDDEN:-48}" DELTA_DROPOUT="${EVIDENCE_DROPOUT:-0.02}" \
DELTA_REGIME_EXPERTS=true DELTA_POLICY_FEATURES=true \
EVIDENCE_CALIBRATOR_ENABLED=true EVIDENCE_CALIBRATOR_HIDDEN="$CAL_HIDDEN" EVIDENCE_CALIBRATOR_SCALE="$CAL_SCALE" \
EVIDENCE_CALIBRATOR_MODE="$CAL_MODE" EVIDENCE_CALIBRATOR_CONTEXT="$CAL_CONTEXT" EVIDENCE_CALIBRATOR_CONTEXT_DETACH="$CAL_CONTEXT_DETACH" \
EVIDENCE_CALIBRATOR_CONTEXT_SOURCE="$CAL_CONTEXT_SOURCE" EVIDENCE_CALIBRATOR_SHARED="$CAL_SHARED" EVIDENCE_CALIBRATOR_REGIME_SCALE="$CAL_REGIME_SCALE" \
ORDINAL_EVIDENCE_INDEPENDENT_TAILS="$INDEPENDENT_TAILS" ORDINAL_EVIDENCE_FACTORIZED_HARM="$FACTORIZED_HARM" \
ORDINAL_EVIDENCE_FACTORIZED_HARM_TEMPERATURE="${ORDINAL_EVIDENCE_FACTORIZED_HARM_TEMPERATURE:-0.025}" \
ORDINAL_EVIDENCE_BALANCED_REPLACES_ERM="$BALANCED_REPLACES_ERM" \
GROUP_BATCH_STRATIFIED="$STRATIFIED_BATCHES" GROUP_BATCH_POSITIVE_FRACTION="${GROUP_BATCH_POSITIVE_FRACTION:-0.35}" \
GROUP_BATCH_HARMFUL_FRACTION="${GROUP_BATCH_HARMFUL_FRACTION:-0.35}" GROUP_BATCH_DEAD_FRACTION="${GROUP_BATCH_DEAD_FRACTION:-0.30}" \
POSITIVE_GROUP_BOOST="${POSITIVE_GROUP_BOOST:-1.0}" POSITIVE_MACRO_BALANCE_POWER="${POSITIVE_MACRO_BALANCE_POWER:-0.25}" \
POINT_WEIGHT=0 VALUE_LISTWISE_WEIGHT=0 CENTERED_WEIGHT=0 ADVANTAGE_WEIGHT=0 SETWISE_W=0 \
PREFERENCE_WEIGHT=0 PREFERENCE_REGRET_WEIGHT=0 PREFERENCE_LISTWISE_WEIGHT=0 PREFERENCE_GAP_WEIGHT=0 \
PREFERENCE_SET_WEIGHT=0 PREFERENCE_ALL_GROUP_SET_WEIGHT=0 PREFERENCE_CONDITIONAL_SET_WEIGHT=0 PREFERENCE_PROPOSAL_TOPK_WEIGHT=0 \
DELTA_NLL_WEIGHT=0 DELTA_SIGN_WEIGHT=0 CERTIFICATE_POLICY_TOP1_WEIGHT=0 CERTIFICATE_POLICY_TOP1_SIGN_WEIGHT=0 \
ORDINAL_EVIDENCE_POLICY_TOP1_WEIGHT=0 ORDINAL_EVIDENCE_ALL_CANDIDATE_WEIGHT=0 \
ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT:-0.10}" \
ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT:-0.00}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT="${ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK="$PROPOSAL_TOP_K" ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY="${ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY:-0.85}" \
ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT="${ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT:-1.50}" \
ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT="${ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT:-1.50}" \
ORDINAL_EVIDENCE_HARD_HARM_WEIGHT=0 ORDINAL_EVIDENCE_HARD_BENEFIT_WEIGHT=0 \
ORDINAL_EVIDENCE_CLASS_BALANCED_WEIGHT="${ORDINAL_EVIDENCE_CLASS_BALANCED_WEIGHT:-1.50}" \
ORDINAL_EVIDENCE_BATCH_BALANCED="$BATCH_BALANCED" \
ORDINAL_EVIDENCE_BENEFIT_MARGIN_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_MARGIN_WEIGHT:-0.75}" \
ORDINAL_EVIDENCE_HARM_MARGIN_WEIGHT="${ORDINAL_EVIDENCE_HARM_MARGIN_WEIGHT:-1.00}" \
ORDINAL_EVIDENCE_TARGET_PROBABILITY="${ORDINAL_EVIDENCE_TARGET_PROBABILITY:-0.65}" \
EVIDENCE_CALIBRATOR_ANCHOR_WEIGHT="${EVIDENCE_CALIBRATOR_ANCHOR_WEIGHT:-0.02}" \
ORDINAL_EVIDENCE_INTRAGROUP_BENEFIT_WEIGHT=0 ORDINAL_EVIDENCE_INTRAGROUP_HARM_WEIGHT=0 \
ORDINAL_EVIDENCE_PAIRWISE_BENEFIT_WEIGHT=0 ORDINAL_EVIDENCE_PAIRWISE_HARM_WEIGHT=0 \
POLICY_METRIC_RISK_SOURCE=ordinal_evidence POLICY_METRIC_PROPOSAL_TOP_K="$PROPOSAL_TOP_K" POLICY_METRIC_EVIDENCE_RERANK_TOP_K=true \
POLICY_METRIC_MIN_FOLD_POSITIVE="${POLICY_METRIC_MIN_FOLD_POSITIVE:-6}" POLICY_METRIC_ROBUST_TOP_K="${POLICY_METRIC_ROBUST_TOP_K:-2}" \
POLICY_METRIC_HARM_WEIGHT="${POLICY_METRIC_HARM_WEIGHT:-0.50}" POLICY_METRIC_FALSE_WEIGHT="${POLICY_METRIC_FALSE_WEIGHT:-0.15}" \
POLICY_METRIC_MISS_WEIGHT="${POLICY_METRIC_MISS_WEIGHT:-1.25}" POLICY_METRIC_MIN_POSITIVE_RECALL="$MIN_POSITIVE_RECALL" \
POLICY_METRIC_RECALL_SHORTFALL_WEIGHT="$RECALL_SHORTFALL_WEIGHT" \
POLICY_METRIC_CROSS_MIN_RECALL="${POLICY_METRIC_CROSS_MIN_RECALL:-0.25}" \
POLICY_METRIC_CROSS_RECALL_WEIGHT="${POLICY_METRIC_CROSS_RECALL_WEIGHT:-2.0}" \
POLICY_METRIC_CROSS_HARM_WEIGHT="${POLICY_METRIC_CROSS_HARM_WEIGHT:-0.50}" \
POLICY_METRIC_CROSS_FALSE_WEIGHT="${POLICY_METRIC_CROSS_FALSE_WEIGHT:-0.20}" \
POLICY_METRIC_FACET_MIN_RECALL="${POLICY_METRIC_FACET_MIN_RECALL:-0.20}" POLICY_METRIC_FACET_HARM_BUDGET="${POLICY_METRIC_FACET_HARM_BUDGET:-0.05}" \
POLICY_METRIC_FACET_FALSE_BUDGET="${POLICY_METRIC_FACET_FALSE_BUDGET:-0.10}" POLICY_METRIC_FACET_BASE_WEIGHT="${POLICY_METRIC_FACET_BASE_WEIGHT:-0.10}" \
POLICY_METRIC_FACET_RECALL_WEIGHT="${POLICY_METRIC_FACET_RECALL_WEIGHT:-12.0}" POLICY_METRIC_FACET_HARM_EXCESS_WEIGHT="${POLICY_METRIC_FACET_HARM_EXCESS_WEIGHT:-10.0}" \
POLICY_METRIC_FACET_FALSE_EXCESS_WEIGHT="${POLICY_METRIC_FACET_FALSE_EXCESS_WEIGHT:-3.0}" \
COMPONENT_HARM_DRS_TOLERANCE="${COMPONENT_HARM_DRS_TOLERANCE:-0.05}" COMPONENT_HARM_DEP_TOLERANCE="${COMPONENT_HARM_DEP_TOLERANCE:-0.05}" \
COMPONENT_HARM_GAP_TOLERANCE="${COMPONENT_HARM_GAP_TOLERANCE:-0.05}" COMPONENT_HARM_HARD_TOLERANCE="${COMPONENT_HARM_HARD_TOLERANCE:-0.05}" \
COMPONENT_HARM_PROXY_TOLERANCE="${COMPONENT_HARM_PROXY_TOLERANCE:-0.05}" \
GROUP_DRO_WEIGHT=0 POLICY_DISTILL_WEIGHT=0 POLICY_REGRET_WEIGHT=0 POLICY_ADMISSION_DISTILL_WEIGHT=0 \
OPPORTUNITY_AUX_WEIGHT=0 HARM_W=0 SELECTIVE_RISK_WEIGHT=0 SELECTIVE_COVERAGE_WEIGHT=0 EXPERT_SPECIALIZATION_WEIGHT=0 \
  bash scripts/train_ocrap_v48_trac_sr.sh

cat > "$RUN/POLICY_CONTRACT.env" <<EOF2
RISK_SOURCE=ordinal_evidence
CONDITIONAL_RECOVERY_RANKING=true
POLICY_FIRST_NO_FALLBACK=false
PROPOSAL_TOP_K=$PROPOSAL_TOP_K
EVIDENCE_RERANK_TOP_K=true
MACRO_CONSTRAINT_MODE=opportunity_normalized
MAX_MACRO_EXCESS_SHARE=${MAX_MACRO_EXCESS_SHARE:-0.15}
HARM_LABEL_MODE=component_veto
CALIBRATION_PROTOCOL=v48_19_facet_scene_disjoint_${CAL_MODE}_context_${CAL_CONTEXT}_batch_${BATCH_BALANCED}
EOF2

python - "$RUN" "$MODEL_DIR/best.pt" "$INIT_CKPT" "$CAL_MODE" "$CAL_CONTEXT" "$BATCH_BALANCED" "$STRATIFIED_BATCHES" "$MIN_POSITIVE_RECALL" "$MAX_CALIBRATOR_PARAMS" "$CAL_CONTEXT_SOURCE" "$INDEPENDENT_TAILS" "$BALANCED_REPLACES_ERM" "$BEST_METRIC_NAME" "$CAL_SHARED" "$CAL_REGIME_SCALE" "$FACTORIZED_HARM" <<'PY'
import hashlib,json,pathlib,sys,time,torch
run,ckpt,source=map(pathlib.Path,sys.argv[1:4])
cal_mode=sys.argv[4]
context_enabled=sys.argv[5].lower() == 'true'
batch_balanced=sys.argv[6].lower() == 'true'
stratified=sys.argv[7].lower() == 'true'
min_positive_recall=float(sys.argv[8])
max_calibrator_params=int(sys.argv[9])
context_source=sys.argv[10]
independent_tails=sys.argv[11].lower() == 'true'
balanced_replaces_erm=sys.argv[12].lower() == 'true'
best_metric=sys.argv[13]
cal_shared=sys.argv[14].lower() == 'true'
cal_regime_scale=float(sys.argv[15])
factorized_harm=sys.argv[16].lower() == 'true'
if not ckpt.is_file(): raise SystemExit(f'missing adapted checkpoint: {ckpt}')
try: doc_ck=torch.load(ckpt,map_location='cpu',weights_only=False)
except TypeError: doc_ck=torch.load(ckpt,map_location='cpu')
state=doc_ck.get('model_state',{})
trainable=sum(v.numel() for k,v in state.items() if k.startswith(('direct_evidence_calibrators.','direct_evidence_shared_calibrator.')))
if trainable <= 0 or trainable > max_calibrator_params:
    raise SystemExit(
        f'unexpected BRIDGE calibrator parameter count: {trainable}; '
        f'allowed=(0,{max_calibrator_params}]'
    )
doc={
 'event':'v48_19_facet_bridge_evidence_correction_complete','created_unix':time.time(),
 'checkpoint':str(ckpt),'checkpoint_sha256':hashlib.sha256(ckpt.read_bytes()).hexdigest(),
 'source_checkpoint':str(source),'source_checkpoint_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
 'frozen_policy':True,'frozen_source_evidence':True,
 'trainable_prefixes':['direct_evidence_shared_calibrator','direct_evidence_calibrators'],'trainable_state_params':trainable,
 'evidence_parameterization':cal_mode,
 'context_features_enabled':context_enabled,'context_source':context_source,
 'independent_evidence_tails':independent_tails,'factorized_component_harm':factorized_harm,
 'shared_cross_regime_calibrator':cal_shared,'regime_residual_scale':cal_regime_scale,
 'balanced_replaces_group_erm':balanced_replaces_erm,
 'checkpoint_metric':best_metric,
 'batch_class_balance':batch_balanced,'stratified_group_batches':stratified,
 'checkpoint_min_positive_recall':min_positive_recall,'test_roots_read':False,
}
(run/'EVIDENCE_CORRECTION_COMPLETE.json').write_text(json.dumps(doc,indent=2)+'\n')
PY
