#!/usr/bin/env bash
set -euo pipefail

# v48.14 PRISM evidence adaptation.
# The high-recall v48.13 proposal policy is frozen. Only the small regime-specific
# ordered-evidence adapters are fine-tuned on scene-disjoint dedicated-calibration
# adaptation scenes; a separate certificate pool remains untouched.
REPO="${OCRAP_REPO:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO"
export PYTHONPATH="$REPO/src${PYTHONPATH:+:$PYTHONPATH}"

RUN="${RUN:?RUN is required}"
INIT_CKPT="${INIT_CKPT:?INIT_CKPT is required}"
VARIANT="${VARIANT:?VARIANT is required}"
TRAIN_MIX="${TRAIN_MIX:?TRAIN_MIX is required}"
VAL_MIX="${VAL_MIX:?VAL_MIX is required}"
GROUP_INDEX="${GROUP_INDEX:?GROUP_INDEX is required}"
TRAIN_GPU="${TRAIN_GPU:-0}"
MODEL_DIR="${MODEL_DIR:-$RUN/model_v48_trac_sr}"
CAL_DIR="${CAL_DIR:-$RUN/calibration}"
mkdir -p "$RUN/logs" "$MODEL_DIR" "$CAL_DIR"

PROPOSAL_TOP_K="${PROPOSAL_TOP_K:-3}"
SET_TOURNAMENT_HIDDEN="${SET_TOURNAMENT_HIDDEN:-48}"
SET_TOURNAMENT_HEADS="${SET_TOURNAMENT_HEADS:-4}"

cat > "$RUN/STAGE_ARCHITECTURE.json" <<JSON
{
  "version": "v48.14-PRISM",
  "source_checkpoint": "$INIT_CKPT",
  "training_role": "scene_disjoint_dedicated_evidence_adaptation",
  "frozen_policy": "v48.13_topk_recovery_proposal",
  "trainable": ["direct_delta_adapters"],
  "proposal_top_k": $PROPOSAL_TOP_K,
  "risk_source": "ordinal_evidence",
  "test_roots_read": false
}
JSON

TRAIN_OCRAP_ROOT="${TRAIN_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
EVAL_OCRAP_ROOT="${EVAL_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
TRAIN_MIX="$TRAIN_MIX" VAL_MIX="$VAL_MIX" CAL_MIX="$VAL_MIX" \
RUN="$RUN" MODEL_DIR="$MODEL_DIR" CAL_DIR="$CAL_DIR" \
INIT_CKPT="$INIT_CKPT" VARIANT="$VARIANT" TRAIN_GPU="$TRAIN_GPU" GROUP_INDEX="$GROUP_INDEX" \
NUM_WORKERS="${NUM_WORKERS:-6}" PREFETCH_FACTOR="${PREFETCH_FACTOR:-2}" BATCH_SIZE="${BATCH_SIZE:-72}" \
EPOCHS="${EVIDENCE_ADAPT_EPOCHS:-8}" PATIENCE="${EVIDENCE_ADAPT_PATIENCE:-3}" \
LR="${EVIDENCE_ADAPT_LR:-0.00006}" ENCODER_LR_SCALE=0 ENCODER_ANCHOR_WEIGHT=0 \
TRAINABLE_PARAM_PREFIXES='direct_delta_adapters' \
STRICT_INIT_PREFIXES='direct_preference_set_ranker,direct_delta_adapters' \
BEST_METRIC=direct_certificate_risk_fold_robust BEST_METRIC_MIN_DELTA="${BEST_METRIC_MIN_DELTA:-0.00001}" \
SKIP_POST_TRAIN_CALIBRATION=1 \
EXACT_TEACHER_PCD=true \
SET_CONTEXT_ENABLED=false PREFERENCE_HEAD_ENABLED=false PREFERENCE_CONTEXT_ENABLED=false RELATIVE_INCLUDE_ABSOLUTE=false \
SET_TOURNAMENT_ENABLED=true SET_TOURNAMENT_HIDDEN="$SET_TOURNAMENT_HIDDEN" SET_TOURNAMENT_HEADS="$SET_TOURNAMENT_HEADS" \
SET_TOURNAMENT_DROPOUT="${SET_TOURNAMENT_DROPOUT:-0.05}" SET_TOURNAMENT_REPLACE_BASE=true \
DELTA_HEAD_ENABLED=true DELTA_MODE=ordinal_evidence DELTA_HIDDEN="${EVIDENCE_HIDDEN:-48}" DELTA_DROPOUT="${EVIDENCE_DROPOUT:-0.02}" \
DELTA_REGIME_EXPERTS=true DELTA_POLICY_FEATURES=true \
POINT_WEIGHT=0 VALUE_LISTWISE_WEIGHT=0 CENTERED_WEIGHT=0 ADVANTAGE_WEIGHT=0 \
SETWISE_W=0 PREFERENCE_WEIGHT=0 PREFERENCE_REGRET_WEIGHT=0 PREFERENCE_LISTWISE_WEIGHT=0 PREFERENCE_GAP_WEIGHT=0 \
PREFERENCE_SET_WEIGHT=0 PREFERENCE_ALL_GROUP_SET_WEIGHT=0 PREFERENCE_CONDITIONAL_SET_WEIGHT=0 PREFERENCE_PROPOSAL_TOPK_WEIGHT=0 \
DELTA_NLL_WEIGHT=0 DELTA_SIGN_WEIGHT=0 CERTIFICATE_POLICY_TOP1_WEIGHT=0 CERTIFICATE_POLICY_TOP1_SIGN_WEIGHT=0 \
ORDINAL_EVIDENCE_POLICY_TOP1_WEIGHT=0 ORDINAL_EVIDENCE_ALL_CANDIDATE_WEIGHT=0 \
ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT:-0.25}" \
ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT:-0.05}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT="${ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT:-3.50}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK="$PROPOSAL_TOP_K" ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY="${ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY:-0.85}" \
ORDINAL_EVIDENCE_INTRAGROUP_BENEFIT_WEIGHT="${ORDINAL_EVIDENCE_INTRAGROUP_BENEFIT_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_INTRAGROUP_HARM_WEIGHT="${ORDINAL_EVIDENCE_INTRAGROUP_HARM_WEIGHT:-1.20}" \
ORDINAL_EVIDENCE_INTRAGROUP_MARGIN="${ORDINAL_EVIDENCE_INTRAGROUP_MARGIN:-0.20}" \
ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT="${ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT:-3.50}" \
ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT="${ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT:-0.45}" \
ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT:-1.50}" \
ORDINAL_EVIDENCE_HARD_HARM_WEIGHT="${ORDINAL_EVIDENCE_HARD_HARM_WEIGHT:-2.50}" \
ORDINAL_EVIDENCE_HARD_BENEFIT_WEIGHT="${ORDINAL_EVIDENCE_HARD_BENEFIT_WEIGHT:-0.75}" \
ORDINAL_EVIDENCE_HARD_EXAMPLE_GAMMA="${ORDINAL_EVIDENCE_HARD_EXAMPLE_GAMMA:-2.0}" \
ORDINAL_EVIDENCE_PAIRWISE_BENEFIT_WEIGHT=0 ORDINAL_EVIDENCE_PAIRWISE_HARM_WEIGHT=0 \
POLICY_METRIC_RISK_SOURCE=ordinal_evidence POLICY_METRIC_PROPOSAL_TOP_K="$PROPOSAL_TOP_K" POLICY_METRIC_EVIDENCE_RERANK_TOP_K=true \
POLICY_METRIC_MIN_FOLD_POSITIVE="${POLICY_METRIC_MIN_FOLD_POSITIVE:-8}" POLICY_METRIC_ROBUST_TOP_K="${POLICY_METRIC_ROBUST_TOP_K:-2}" \
GROUP_DRO_WEIGHT=0 POLICY_DISTILL_WEIGHT=0 POLICY_REGRET_WEIGHT=0 POLICY_ADMISSION_DISTILL_WEIGHT=0 \
OPPORTUNITY_AUX_WEIGHT=0 HARM_W=0 SELECTIVE_RISK_WEIGHT=0 SELECTIVE_COVERAGE_WEIGHT=0 EXPERT_SPECIALIZATION_WEIGHT=0 \
  bash scripts/train_ocrap_v48_trac_sr.sh

cat > "$RUN/POLICY_CONTRACT.env" <<EOF
RISK_SOURCE=ordinal_evidence
CONDITIONAL_RECOVERY_RANKING=true
POLICY_FIRST_NO_FALLBACK=false
PROPOSAL_TOP_K=$PROPOSAL_TOP_K
EVIDENCE_RERANK_TOP_K=true
MACRO_CONSTRAINT_MODE=opportunity_normalized
MAX_MACRO_EXCESS_SHARE=${MAX_MACRO_EXCESS_SHARE:-0.15}
CALIBRATION_PROTOCOL=v48_14_scene_disjoint_adapt_dev_certificate
EOF

python - "$RUN" "$MODEL_DIR/best.pt" "$INIT_CKPT" <<'PY'
import hashlib,json,pathlib,sys,time
run,ckpt,source=map(pathlib.Path,sys.argv[1:])
if not ckpt.is_file(): raise SystemExit(f'missing adapted checkpoint: {ckpt}')
doc={
 'event':'v48_14_prism_evidence_adaptation_complete','created_unix':time.time(),
 'checkpoint':str(ckpt),'checkpoint_sha256':hashlib.sha256(ckpt.read_bytes()).hexdigest(),
 'source_checkpoint':str(source),'source_checkpoint_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
 'frozen_policy':True,'trainable_prefixes':['direct_delta_adapters'],'test_roots_read':False,
}
(run/'EVIDENCE_ADAPTATION_COMPLETE.json').write_text(json.dumps(doc,indent=2)+'\n')
PY
