#!/usr/bin/env bash
set -Eeuo pipefail

# v48.36 OCAF / OBSERVATION-CONDITIONED ACTION FRONTIER
# One unified, regime-agnostic selector trains and validates the exact deployed
# order: frozen rank proposal -> opportunity/harm eligibility -> evidence rerank
# -> one recovery action or nominal.  No regime id or regime-specific policy is
# exposed to the model.
REPO="${OCRAP_REPO:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO"
export PYTHONPATH="$REPO/src${PYTHONPATH:+:$PYTHONPATH}"
export CUBLAS_WORKSPACE_CONFIG="${CUBLAS_WORKSPACE_CONFIG:-:4096:8}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:128}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-2}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-2}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-2}"

RUN="${RUN:?RUN is required}"
INIT_CKPT="${INIT_CKPT:?INIT_CKPT is required}"
VARIANT="${VARIANT:?VARIANT is required}"
TRAIN_MIX="${TRAIN_MIX:?TRAIN_MIX is required}"
VAL_MIX="${VAL_MIX:?VAL_MIX is required}"
GROUP_INDEX="${GROUP_INDEX:?GROUP_INDEX is required}"
TRAIN_GPU="${TRAIN_GPU:-0}"
MODEL_DIR="${MODEL_DIR:-$RUN/model_v48_trac_sr}"
CAL_DIR="${CAL_DIR:-$RUN/calibration}"
mkdir -p "$RUN/logs" "$MODEL_DIR" "$CAL_DIR"

PROPOSAL_TOP_K="${PROPOSAL_TOP_K:-5}"
CAL_HIDDEN="${EVIDENCE_CALIBRATOR_HIDDEN:-32}"
CAL_SCALE="${EVIDENCE_CALIBRATOR_SCALE:-1.50}"
CAL_CONTEXT="${EVIDENCE_CALIBRATOR_CONTEXT:-true}"
CAL_CONTEXT_SOURCE="${EVIDENCE_CALIBRATOR_CONTEXT_SOURCE:-physical_interaction}"
COMPONENT_HEADS="${EVIDENCE_COMPONENT_HEADS:-true}"
COMPONENT_COUNT="${EVIDENCE_COMPONENT_COUNT:-5}"
SETWISE_WEIGHT="${SETWISE_W:-1.00}"
COMPONENT_TAIL_WEIGHT="${ORDINAL_EVIDENCE_COMPONENT_TAIL_WEIGHT:-0.50}"
COMPONENT_MARGIN_TARGET_MODE="${ORDINAL_EVIDENCE_COMPONENT_MARGIN_TARGET_MODE:-raw}"
COMPONENT_MARGIN_TARGET_SCALE="${ORDINAL_EVIDENCE_COMPONENT_MARGIN_TARGET_SCALE:-0.10}"
COMPONENT_MARGIN_CANONICAL_SCALES="${ORDINAL_EVIDENCE_COMPONENT_MARGIN_CANONICAL_SCALES:-}"
COMPONENT_MARGIN_REGRESSION_RELIABILITY="${ORDINAL_EVIDENCE_COMPONENT_MARGIN_REGRESSION_RELIABILITY:-}"
BENEFIT_RESIDUAL_SCALE="${EVIDENCE_BENEFIT_RESIDUAL_SCALE:-1.0}"
UNBOUNDED_BENEFIT_FACTOR="${EVIDENCE_UNBOUNDED_BENEFIT_FACTOR:-false}"
UNBOUNDED_HARM_FACTORS="${EVIDENCE_UNBOUNDED_HARM_FACTORS:-false}"
RESERVE_FACTOR_ALIGNMENT="${EVIDENCE_RESERVE_FACTOR_ALIGNMENT:-false}"
COMPONENT_UNDERESTIMATION_WEIGHT="${ORDINAL_EVIDENCE_COMPONENT_UNDERESTIMATION_WEIGHT:-0.0}"
SAFE_POSITIVE_COMPONENT_OVERESTIMATION_WEIGHT="${ORDINAL_EVIDENCE_SAFE_POSITIVE_COMPONENT_OVERESTIMATION_WEIGHT:-0.0}"
BENEFIT_MARGIN_REGRESSION_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_MARGIN_REGRESSION_WEIGHT:-0.0}"
BENEFIT_MARGIN_TEMPERATURE="${ORDINAL_EVIDENCE_BENEFIT_MARGIN_TEMPERATURE:-0.025}"
JOINT_RESERVE_REGRESSION_WEIGHT="${ORDINAL_EVIDENCE_JOINT_RESERVE_REGRESSION_WEIGHT:-0.0}"
JOINT_RESERVE_BOUNDARY_WEIGHT="${ORDINAL_EVIDENCE_JOINT_RESERVE_BOUNDARY_WEIGHT:-0.0}"
JOINT_RESERVE_BOUNDARY_WIDTH="${ORDINAL_EVIDENCE_JOINT_RESERVE_BOUNDARY_WIDTH:-0.05}"
JOINT_RESERVE_TEMPERATURE="${EVIDENCE_JOINT_RESERVE_TEMPERATURE:-0.025}"
BATCH_BALANCED="${ORDINAL_EVIDENCE_BATCH_BALANCED:-true}"
GLOBAL_BALANCE="${ORDINAL_EVIDENCE_GLOBAL_BALANCE:-true}"
MAX_CALIBRATOR_PARAMS="${MAX_EVIDENCE_CALIBRATOR_PARAMS:-0}"
BEST_METRIC_NAME="${BEST_METRIC:-direct_contract_lexicographic}"
STRATIFIED_BATCHES="${GROUP_BATCH_STRATIFIED:-true}"
CONCORD_ENABLED="${EVIDENCE_CONCORD:-true}"
ADMISSION_ENABLED="${EVIDENCE_ADMISSION_HEAD:-true}"
SAFE_BENEFIT_TARGET="${ORDINAL_EVIDENCE_SAFE_BENEFIT_TARGET:-false}"
GROUP_OPPORTUNITY_WEIGHT="${ORDINAL_EVIDENCE_GROUP_OPPORTUNITY_WEIGHT:-0.0}"
DISAGREEMENT_PENALTY="${EVIDENCE_CONSENSUS_DISAGREEMENT_PENALTY:-0.15}"
CONSENSUS_PRIOR_SCALE="${EVIDENCE_CONSENSUS_PRIOR_SCALE:-0.50}"
INTERACTION_HIDDEN="${EVIDENCE_INTERACTION_HIDDEN:-64}"
INTERACTION_DROPOUT="${EVIDENCE_INTERACTION_DROPOUT:-0.05}"
DUAL_INTERACTION_BRIDGE="${EVIDENCE_DUAL_INTERACTION_BRIDGE:-false}"
FACTORIZED_HARM_INTERACTION="${EVIDENCE_FACTORIZED_HARM_INTERACTION:-false}"
PARTIAL_POOL_HARM_RESIDUAL="${EVIDENCE_PARTIAL_POOL_HARM_RESIDUAL:-false}"
PARTIAL_POOL_HARM_RESIDUAL_SCALE="${EVIDENCE_PARTIAL_POOL_HARM_RESIDUAL_SCALE:-0.50}"
RANK_BENEFIT_SKIP="${EVIDENCE_RANK_BENEFIT_SKIP:-false}"
RANK_BENEFIT_GAIN_INIT="${EVIDENCE_RANK_BENEFIT_GAIN_INIT:-1.0}"
POSTPREFIX_OBS_TRANSPORT_BENEFIT="${EVIDENCE_POSTPREFIX_OBS_TRANSPORT_BENEFIT:-false}"
POSTPREFIX_OBS_TRANSPORT_HARM="${EVIDENCE_POSTPREFIX_OBS_TRANSPORT_HARM:-false}"
POSTPREFIX_OBS_TRANSPORT_SCALE="${EVIDENCE_POSTPREFIX_OBS_TRANSPORT_SCALE:-1.0}"
ROCT_BENEFIT="${EVIDENCE_ROCT_BENEFIT:-false}"
ROCT_DEPLOYABILITY="${EVIDENCE_ROCT_DEPLOYABILITY:-false}"
ROCT_SCALE="${EVIDENCE_ROCT_SCALE:-1.0}"
ROCT_ALPHA="${EVIDENCE_ROCT_ALPHA:-0.2}"
ROCT_BETA="${EVIDENCE_ROCT_BETA:-0.2}"
ROCT_TOP_M="${EVIDENCE_ROCT_TOP_M:-8}"
ROCT_OPTION_TEMPERATURE="${EVIDENCE_ROCT_OPTION_TEMPERATURE:-0.35}"
COMMON_MEASURE_ROOT_MASS="${EVIDENCE_COMMON_MEASURE_ROOT_MASS:-false}"
ABSOLUTE_FEASIBILITY_HEAD="${ABSOLUTE_FEASIBILITY_HEAD:-false}"
ABSOLUTE_OPTION_MARGIN_CORRECTION="${ABSOLUTE_OPTION_MARGIN_CORRECTION:-false}"
ABSOLUTE_PHYSICAL_HEADROOM_CORRECTION="${ABSOLUTE_PHYSICAL_HEADROOM_CORRECTION:-false}"
ABSOLUTE_EXECUTABLE_WITNESS_CORRECTION="${ABSOLUTE_EXECUTABLE_WITNESS_CORRECTION:-false}"
ABSOLUTE_COMMON_WITNESS_CORRECTION="${ABSOLUTE_COMMON_WITNESS_CORRECTION:-false}"
ABSOLUTE_QUANTIFIER_WITNESS_CORRECTION="${ABSOLUTE_QUANTIFIER_WITNESS_CORRECTION:-false}"
ABSOLUTE_SEMANTIC_WITNESS_CORRECTION="${ABSOLUTE_SEMANTIC_WITNESS_CORRECTION:-false}"
SEMANTIC_WITNESS_ACTIVE_SET_ALIGNMENT="${SEMANTIC_WITNESS_ACTIVE_SET_ALIGNMENT:-true}"
SEMANTIC_WITNESS_PATH_STOP_ALIGNMENT="${SEMANTIC_WITNESS_PATH_STOP_ALIGNMENT:-true}"
SEMANTIC_WITNESS_CLASSLOCAL_TRANSPORT="${SEMANTIC_WITNESS_CLASSLOCAL_TRANSPORT:-false}"
SEMANTIC_WITNESS_ROUTE_ALIGNMENT="${SEMANTIC_WITNESS_ROUTE_ALIGNMENT:-false}"
SEMANTIC_WITNESS_REENTRY_ALIGNMENT="${SEMANTIC_WITNESS_REENTRY_ALIGNMENT:-false}"
SEMANTIC_WITNESS_CONTROL_PROJECTION="${SEMANTIC_WITNESS_CONTROL_PROJECTION:-false}"
SEMANTIC_WITNESS_BOUNDARY_TRANSPORT="${SEMANTIC_WITNESS_BOUNDARY_TRANSPORT:-false}"
SEMANTIC_WITNESS_PROJECTION_FIDELITY="${SEMANTIC_WITNESS_PROJECTION_FIDELITY:-false}"
SEMANTIC_WITNESS_ACTIVE_CONSTRAINT_TYPED_SOURCE="${SEMANTIC_WITNESS_ACTIVE_CONSTRAINT_TYPED_SOURCE:-false}"
SEMANTIC_WITNESS_ROOT_TAIL_SOURCE="${SEMANTIC_WITNESS_ROOT_TAIL_SOURCE:-false}"
SEMANTIC_WITNESS_STRUCTURED_TAIL_FIELD="${SEMANTIC_WITNESS_STRUCTURED_TAIL_FIELD:-false}"
SEMANTIC_WITNESS_SIGNED_TAIL_CHANNELS="${SEMANTIC_WITNESS_SIGNED_TAIL_CHANNELS:-false}"
SEMANTIC_WITNESS_COUNTERFACTUAL_TAIL_RESPONSE="${SEMANTIC_WITNESS_COUNTERFACTUAL_TAIL_RESPONSE:-false}"
SEMANTIC_WITNESS_TAIL_LOCALIZATION="${SEMANTIC_WITNESS_TAIL_LOCALIZATION:-false}"
SEMANTIC_WITNESS_DEMAND_NORMALIZED_FIDELITY="${SEMANTIC_WITNESS_DEMAND_NORMALIZED_FIDELITY:-false}"
SEMANTIC_WITNESS_ROBUST_OCCUPANCY="${SEMANTIC_WITNESS_ROBUST_OCCUPANCY:-false}"
SEMANTIC_WITNESS_SOFT_OCCUPANCY_DISAGREEMENT="${SEMANTIC_WITNESS_SOFT_OCCUPANCY_DISAGREEMENT:-false}"
SEMANTIC_WITNESS_BOUNDARY_LOCALIZED_OCCUPANCY_TRUST="${SEMANTIC_WITNESS_BOUNDARY_LOCALIZED_OCCUPANCY_TRUST:-false}"
SEMANTIC_WITNESS_HISTORY_OCCUPANCY_REACHABILITY="${SEMANTIC_WITNESS_HISTORY_OCCUPANCY_REACHABILITY:-false}"
SEMANTIC_WITNESS_INTERACTION_BOX_SUPPORT="${SEMANTIC_WITNESS_INTERACTION_BOX_SUPPORT:-false}"
SEMANTIC_WITNESS_INTERACTION_HULL_SUPPORT="${SEMANTIC_WITNESS_INTERACTION_HULL_SUPPORT:-false}"
SEMANTIC_WITNESS_INTERACTION_ANCHOR_SUPPORT="${SEMANTIC_WITNESS_INTERACTION_ANCHOR_SUPPORT:-false}"
SEMANTIC_WITNESS_INTERACTION_RESPONSE_SUPPORT="${SEMANTIC_WITNESS_INTERACTION_RESPONSE_SUPPORT:-false}"
ABSOLUTE_FEASIBILITY_WEIGHT="${ABSOLUTE_FEASIBILITY_WEIGHT:-0.0}"
ABSOLUTE_FEASIBILITY_TRUTH_CONTRACT="${ABSOLUTE_FEASIBILITY_TRUTH_CONTRACT:-legacy_full}"
ABSOLUTE_FEASIBILITY_SUPERVISION_OBJECTIVE="${ABSOLUTE_FEASIBILITY_SUPERVISION_OBJECTIVE:-binary_sign}"
ABSOLUTE_FEASIBILITY_TRUTH_INDEX="${ABSOLUTE_FEASIBILITY_TRUTH_INDEX:-}"
_abs_source_count=0
[[ "$ABSOLUTE_FEASIBILITY_HEAD" == true ]] && _abs_source_count=$((_abs_source_count+1))
[[ "$ABSOLUTE_OPTION_MARGIN_CORRECTION" == true ]] && _abs_source_count=$((_abs_source_count+1))
[[ "$ABSOLUTE_PHYSICAL_HEADROOM_CORRECTION" == true ]] && _abs_source_count=$((_abs_source_count+1))
[[ "$ABSOLUTE_EXECUTABLE_WITNESS_CORRECTION" == true ]] && _abs_source_count=$((_abs_source_count+1))
[[ "$ABSOLUTE_COMMON_WITNESS_CORRECTION" == true ]] && _abs_source_count=$((_abs_source_count+1))
[[ "$ABSOLUTE_QUANTIFIER_WITNESS_CORRECTION" == true ]] && _abs_source_count=$((_abs_source_count+1))
[[ "$ABSOLUTE_SEMANTIC_WITNESS_CORRECTION" == true ]] && _abs_source_count=$((_abs_source_count+1))
if (( _abs_source_count > 1 )); then
  echo "AFE, ORFC, CPHR, ERWF, OC-CWRF, OC-QARW, and OC-SARW absolute-source corrections are mutually exclusive" >&2
  exit 30
fi
if (( _abs_source_count == 1 )); then
  SELECTION_SEMANTICS="rank_topk_then_absolute_feasibility_then_relative_filter_then_evidence_rerank"
  ABSOLUTE_FEASIBILITY_MODE_CONTRACT="learned"
else
  SELECTION_SEMANTICS="rank_topk_then_filter_then_evidence_rerank"
  ABSOLUTE_FEASIBILITY_MODE_CONTRACT="off"
fi

FRONTIER_ENABLED="${EVIDENCE_FRONTIER:-true}"
COMPONENT_PRIOR_LOGIT="${EVIDENCE_COMPONENT_PRIOR_LOGIT:--2.0}"
CATEGORICAL_GROUP_POLICY="${ORDINAL_EVIDENCE_CATEGORICAL_GROUP_POLICY:-true}"
BENEFIT_LISTWISE_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_LISTWISE_WEIGHT:-0.75}"
BENEFIT_LISTWISE_TEMPERATURE="${ORDINAL_EVIDENCE_BENEFIT_LISTWISE_TEMPERATURE:-0.08}"
FRONTIER_PAIRWISE_WEIGHT="${ORDINAL_EVIDENCE_FRONTIER_PAIRWISE_WEIGHT:-0.75}"
FRONTIER_PAIRWISE_MARGIN="${ORDINAL_EVIDENCE_FRONTIER_PAIRWISE_MARGIN:-0.05}"
SAFE_UTILITY_REGRESSION_WEIGHT="${ORDINAL_EVIDENCE_SAFE_UTILITY_REGRESSION_WEIGHT:-0.50}"
SAFE_UTILITY_LISTWISE_WEIGHT="${ORDINAL_EVIDENCE_SAFE_UTILITY_LISTWISE_WEIGHT:-0.25}"
SAFE_UTILITY_TEMPERATURE="${ORDINAL_EVIDENCE_SAFE_UTILITY_TEMPERATURE:-0.10}"
ELIGIBLE_POLICY_WEIGHT="${ORDINAL_EVIDENCE_ELIGIBLE_POLICY_WEIGHT:-0.0}"
ELIGIBLE_POLICY_TEMPERATURE="${ORDINAL_EVIDENCE_ELIGIBLE_POLICY_TEMPERATURE:-0.10}"
ELIGIBILITY_LOGIT_TEMPERATURE="${ORDINAL_EVIDENCE_ELIGIBILITY_LOGIT_TEMPERATURE:-0.25}"
ELIGIBLE_OPPORTUNITY_THRESHOLD="${ORDINAL_EVIDENCE_ELIGIBLE_OPPORTUNITY_THRESHOLD:-${POLICY_METRIC_OPPORTUNITY_THRESHOLD:-0.50}}"
ELIGIBLE_HARM_THRESHOLD="${ORDINAL_EVIDENCE_ELIGIBLE_HARM_THRESHOLD:-${POLICY_METRIC_HARM_THRESHOLD:-0.50}}"
ELIGIBILITY_BOUNDARY_WEIGHT="${ORDINAL_EVIDENCE_ELIGIBILITY_BOUNDARY_WEIGHT:-0.0}"
ELIGIBILITY_BOUNDARY_MARGIN="${ORDINAL_EVIDENCE_ELIGIBILITY_BOUNDARY_MARGIN:-0.20}"
SAFE_HARD_NEGATIVE_WEIGHT="${ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_WEIGHT:-0.0}"
SAFE_HARD_NEGATIVE_MARGIN="${ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_MARGIN:-0.05}"
ADMISSION_PRIOR_MODE="${EVIDENCE_ADMISSION_PRIOR_MODE:-frontier_capped_slack}"
OCAF_ENABLED=false
[[ "$CAL_CONTEXT_SOURCE" == physical_interaction ]] && OCAF_ENABLED=true
NONCOMPENSATORY_CAP=false
[[ "$ADMISSION_PRIOR_MODE" == frontier_capped_slack || "$ADMISSION_PRIOR_MODE" == joint_reserve ]] && NONCOMPENSATORY_CAP=true
DETERMINISTIC_JOINT_RESERVE=false
[[ "$ADMISSION_PRIOR_MODE" == joint_reserve ]] && DETERMINISTIC_JOINT_RESERVE=true
if [[ "$CONCORD_ENABLED" == true ]]; then
  TRAINABLE_PREFIXES='direct_evidence_concord_benefit_calibrator,direct_evidence_concord_harm_calibrator'
  if [[ "$ADMISSION_ENABLED" == true ]]; then
    TRAINABLE_PREFIXES+=',direct_evidence_concord_admission_calibrator'
  fi
else
  TRAINABLE_PREFIXES='direct_evidence_unified_calibrator'
  ADMISSION_ENABLED=false
fi
if [[ "$CAL_CONTEXT_SOURCE" == physical_interaction ]]; then
  TRAINABLE_PREFIXES+=',direct_evidence_interaction_bridge'
fi
if [[ "$PARTIAL_POOL_HARM_RESIDUAL" == true ]]; then
  TRAINABLE_PREFIXES+=',direct_evidence_concord_harm_component_residuals'
fi
if [[ "$RANK_BENEFIT_SKIP" == true ]]; then
  TRAINABLE_PREFIXES+=',direct_evidence_rank_benefit_log_gain'
fi
if [[ "$POSTPREFIX_OBS_TRANSPORT_BENEFIT" == true ]]; then
  TRAINABLE_PREFIXES+=',direct_evidence_postprefix_obs_transport_benefit'
fi
if [[ "$POSTPREFIX_OBS_TRANSPORT_HARM" == true ]]; then
  TRAINABLE_PREFIXES+=',direct_evidence_postprefix_obs_transport_harm'
fi
if [[ "$ROCT_BENEFIT" == true ]]; then
  TRAINABLE_PREFIXES+=',direct_evidence_roct_benefit'
fi
if [[ "$ROCT_DEPLOYABILITY" == true ]]; then
  TRAINABLE_PREFIXES+=',direct_evidence_roct_deployability'
fi
TRAINABLE_PREFIXES="${EVIDENCE_TRAINABLE_PREFIXES_OVERRIDE:-$TRAINABLE_PREFIXES}"
INTERACTION_BRIDGE_TRAINABLE=false
case ",$TRAINABLE_PREFIXES," in
  *,direct_evidence_interaction_bridge,*) INTERACTION_BRIDGE_TRAINABLE=true ;;
esac
ALGORITHM_VARIANT="${OCRAP_ALGORITHM_VERSION:-v48.36-OCAF}"

cat > "$RUN/STAGE_ARCHITECTURE.json" <<JSON
{
  "version": "v48.36-OCAF",
  "algorithm_variant": "$ALGORITHM_VARIANT",
  "source_checkpoint": "$INIT_CKPT",
  "training_role": "unified_non_regime_specific_safe_set_admission",
  "frozen_policy": "v48.13_topk_recovery_proposal",
  "frozen_source_experts": true,
  "trainable": ["$TRAINABLE_PREFIXES"],
  "regime_id_exposed_to_evidence_model": false,
  "source_expert_use": "evaluate_both_for_every_candidate",
  "source_expert_envelope": "permutation_invariant_mean_minus_disagreement",
  "benefit_transfer": "scaled_consensus_transfer_plus_candidate_context_residual",
  "consensus_prior_scale": $CONSENSUS_PRIOR_SCALE,
  "observation_conditioned_action_frontier": $OCAF_ENABLED,
  "interaction_hidden": $INTERACTION_HIDDEN,
  "interaction_dropout": $INTERACTION_DROPOUT,
  "interaction_zero_action_exact_zero": $OCAF_ENABLED,
  "interaction_scene_only_shortcut_forbidden": $OCAF_ENABLED,
  "harm_transfer": "decoupled_semantic_reset_absolute_component_logits",
  "concord_decoupled_heads": $CONCORD_ENABLED,
  "frontier_enabled": $FRONTIER_ENABLED,
  "raw_benefit_target": true,
  "safe_benefit_target": $SAFE_BENEFIT_TARGET,
  "admission_head": $ADMISSION_ENABLED,
  "admission_target": "$([[ "$ADMISSION_PRIOR_MODE" == joint_reserve ]] && echo deterministic_joint_physical_reserve || echo continuous_safe_utility_with_component_veto)",
  "group_opportunity_mil_weight": $GROUP_OPPORTUNITY_WEIGHT,
  "noisy_or_group_objective_disabled": true,
  "component_harm_heads": $COMPONENT_HEADS,
  "component_harm_components": ["drs", "deployability", "gap", "hard_rule", "harm_proxy"],
  "component_harm_count": $COMPONENT_COUNT,
  "component_reliability": "${EVIDENCE_COMPONENT_RELIABILITY:-}",
  "benefit_residual_scale": $BENEFIT_RESIDUAL_SCALE,
  "unbounded_benefit_factor": $UNBOUNDED_BENEFIT_FACTOR,
  "unbounded_harm_factors": $UNBOUNDED_HARM_FACTORS,
  "reserve_factor_alignment": $RESERVE_FACTOR_ALIGNMENT,
  "physical_factor_parameterization": "$([[ "$UNBOUNDED_BENEFIT_FACTOR" == true || "$UNBOUNDED_HARM_FACTORS" == true ]] && echo signed_unbounded_regression || echo legacy_bounded_residual)",
  "semantic_frontier_eligibility_metric": true,
  "exact_deployment_eligibility_metric": true,
  "exact_deployment_eligibility_provenance": "checkpoint_cfg.training.direct_policy_metric_exact_eligibility",
  "final_thresholds_fit_by_single_shared_rule": true,
  "train_metric_uses_final_fitted_thresholds": false,
  "trainable_parameter_contract": "exact_checkpoint_prefix_match_not_architecture_agnostic_cap",
  "setwise_admission_weight": $SETWISE_WEIGHT,
  "component_tail_weight": $COMPONENT_TAIL_WEIGHT,
  "candidate_balance_is_auxiliary": true,
  "balanced_replaces_group_erm": false,
  "global_not_regime_balance": $GLOBAL_BALANCE,
  "context_source": "$CAL_CONTEXT_SOURCE",
  "dual_interaction_bridge": $DUAL_INTERACTION_BRIDGE,
  "factorized_harm_interaction": $FACTORIZED_HARM_INTERACTION,
  "partial_pool_harm_residual": $PARTIAL_POOL_HARM_RESIDUAL,
  "partial_pool_harm_residual_scale": $PARTIAL_POOL_HARM_RESIDUAL_SCALE,
  "rank_benefit_skip": $RANK_BENEFIT_SKIP,
  "rank_benefit_gain_init": $RANK_BENEFIT_GAIN_INIT,
  "postprefix_obs_transport_benefit": $POSTPREFIX_OBS_TRANSPORT_BENEFIT,
  "postprefix_obs_transport_harm": $POSTPREFIX_OBS_TRANSPORT_HARM,
  "postprefix_obs_transport_scale": $POSTPREFIX_OBS_TRANSPORT_SCALE,
  "postprefix_obs_transport_regime_conditioned": false,
  "roct_benefit": $ROCT_BENEFIT,
  "roct_deployability": $ROCT_DEPLOYABILITY,
  "roct_scale": $ROCT_SCALE,
  "roct_alpha": $ROCT_ALPHA,
  "roct_beta": $ROCT_BETA,
  "roct_top_m": $ROCT_TOP_M,
  "roct_option_temperature": $ROCT_OPTION_TEMPERATURE,
  "common_measure_root_mass": $COMMON_MEASURE_ROOT_MASS,
  "absolute_feasibility_head": $ABSOLUTE_FEASIBILITY_HEAD,
  "absolute_option_margin_correction": $ABSOLUTE_OPTION_MARGIN_CORRECTION,
  "absolute_physical_headroom_correction": $ABSOLUTE_PHYSICAL_HEADROOM_CORRECTION,
  "absolute_executable_witness_correction": $ABSOLUTE_EXECUTABLE_WITNESS_CORRECTION,
  "absolute_common_witness_correction": $ABSOLUTE_COMMON_WITNESS_CORRECTION,
  "absolute_quantifier_witness_correction": $ABSOLUTE_QUANTIFIER_WITNESS_CORRECTION,
  "absolute_semantic_witness_correction": $ABSOLUTE_SEMANTIC_WITNESS_CORRECTION,
  "semantic_witness_active_set_alignment": $SEMANTIC_WITNESS_ACTIVE_SET_ALIGNMENT,
  "semantic_witness_path_stop_alignment": $SEMANTIC_WITNESS_PATH_STOP_ALIGNMENT,
  "semantic_witness_classlocal_transport": $SEMANTIC_WITNESS_CLASSLOCAL_TRANSPORT,
  "semantic_witness_route_alignment": $SEMANTIC_WITNESS_ROUTE_ALIGNMENT,
  "semantic_witness_reentry_alignment": $SEMANTIC_WITNESS_REENTRY_ALIGNMENT,
  "semantic_witness_control_projection": $SEMANTIC_WITNESS_CONTROL_PROJECTION,
  "semantic_witness_boundary_transport": $SEMANTIC_WITNESS_BOUNDARY_TRANSPORT,
  "semantic_witness_projection_fidelity": $SEMANTIC_WITNESS_PROJECTION_FIDELITY,
  "semantic_witness_active_constraint_typed_source": $SEMANTIC_WITNESS_ACTIVE_CONSTRAINT_TYPED_SOURCE,
  "semantic_witness_root_tail_source": $SEMANTIC_WITNESS_ROOT_TAIL_SOURCE,
  "semantic_witness_structured_tail_field": $SEMANTIC_WITNESS_STRUCTURED_TAIL_FIELD,
  "semantic_witness_signed_tail_channels": $SEMANTIC_WITNESS_SIGNED_TAIL_CHANNELS,
  "semantic_witness_counterfactual_tail_response": $SEMANTIC_WITNESS_COUNTERFACTUAL_TAIL_RESPONSE,
  "semantic_witness_tail_localization": $SEMANTIC_WITNESS_TAIL_LOCALIZATION,
  "semantic_witness_demand_normalized_fidelity": $SEMANTIC_WITNESS_DEMAND_NORMALIZED_FIDELITY,
  "semantic_witness_robust_occupancy": $SEMANTIC_WITNESS_ROBUST_OCCUPANCY,
  "semantic_witness_soft_occupancy_disagreement": $SEMANTIC_WITNESS_SOFT_OCCUPANCY_DISAGREEMENT,
  "semantic_witness_boundary_localized_occupancy_trust": $SEMANTIC_WITNESS_BOUNDARY_LOCALIZED_OCCUPANCY_TRUST,
  "semantic_witness_history_occupancy_reachability": $SEMANTIC_WITNESS_HISTORY_OCCUPANCY_REACHABILITY,
  "semantic_witness_interaction_box_support": $SEMANTIC_WITNESS_INTERACTION_BOX_SUPPORT,
  "semantic_witness_interaction_hull_support": $SEMANTIC_WITNESS_INTERACTION_HULL_SUPPORT,
  "semantic_witness_interaction_anchor_support": $SEMANTIC_WITNESS_INTERACTION_ANCHOR_SUPPORT,
  "semantic_witness_interaction_response_support": $SEMANTIC_WITNESS_INTERACTION_RESPONSE_SUPPORT,
  "absolute_feasibility_weight": $ABSOLUTE_FEASIBILITY_WEIGHT,
  "absolute_feasibility_truth_contract": "$ABSOLUTE_FEASIBILITY_TRUTH_CONTRACT",
  "absolute_feasibility_supervision_objective": "$ABSOLUTE_FEASIBILITY_SUPERVISION_OBJECTIVE",
  "absolute_feasibility_truth_index": "$ABSOLUTE_FEASIBILITY_TRUTH_INDEX",
  "roct_regime_conditioned": false,
  "component_margin_target_mode": "$COMPONENT_MARGIN_TARGET_MODE",
  "component_margin_target_scale": $COMPONENT_MARGIN_TARGET_SCALE,
  "component_margin_canonical_scales": "$COMPONENT_MARGIN_CANONICAL_SCALES",
  "component_margin_regression_reliability": "$COMPONENT_MARGIN_REGRESSION_RELIABILITY",
  "proposal_top_k": $PROPOSAL_TOP_K,
  "frontier_runtime_wiring_verified": true,
  "admission_residual_bounded": ${EVIDENCE_ADMISSION_BOUNDED:-false},
  "admission_prior_detach": ${EVIDENCE_ADMISSION_PRIOR_DETACH:-true},
  "admission_prior_mode": "$ADMISSION_PRIOR_MODE",
  "slack_temperature": ${EVIDENCE_SLACK_TEMPERATURE:-0.025},
  "slack_penalty": ${EVIDENCE_SLACK_PENALTY:-1.0},
  "frontier_cap_temperature": ${EVIDENCE_FRONTIER_CAP_TEMPERATURE:-0.10},
  "noncompensatory_frontier_cap": $NONCOMPENSATORY_CAP,
  "shared_deployment_rule_required": true,
  "component_margin_regression_weight": ${ORDINAL_EVIDENCE_COMPONENT_MARGIN_REGRESSION_WEIGHT:-0.0},
  "component_underestimation_weight": $COMPONENT_UNDERESTIMATION_WEIGHT,
  "safe_positive_component_overestimation_weight": $SAFE_POSITIVE_COMPONENT_OVERESTIMATION_WEIGHT,
  "benefit_margin_regression_weight": $BENEFIT_MARGIN_REGRESSION_WEIGHT,
  "benefit_margin_temperature": $BENEFIT_MARGIN_TEMPERATURE,
  "joint_reserve_regression_weight": $JOINT_RESERVE_REGRESSION_WEIGHT,
  "joint_reserve_boundary_weight": $JOINT_RESERVE_BOUNDARY_WEIGHT,
  "joint_reserve_boundary_width": $JOINT_RESERVE_BOUNDARY_WIDTH,
  "joint_reserve_temperature": $JOINT_RESERVE_TEMPERATURE,
  "deterministic_joint_reserve": $DETERMINISTIC_JOINT_RESERVE,
  "learned_admission_residual": $ADMISSION_ENABLED,
  "interaction_bridge_trainable_this_stage": $INTERACTION_BRIDGE_TRAINABLE,
  "group_batch_stratified": $STRATIFIED_BATCHES,
  "group_batching_replacement": ${GROUP_BATCHING_REPLACEMENT:-true},
  "checkpoint_all_abstain_barrier": true,
  "semantic_component_prior_logit": $COMPONENT_PRIOR_LOGIT,
  "categorical_nominal_topk_policy": $CATEGORICAL_GROUP_POLICY,
  "benefit_listwise_weight": $BENEFIT_LISTWISE_WEIGHT,
  "frontier_pairwise_weight": $FRONTIER_PAIRWISE_WEIGHT,
  "safe_utility_regression_weight": $SAFE_UTILITY_REGRESSION_WEIGHT,
  "safe_utility_listwise_weight": $SAFE_UTILITY_LISTWISE_WEIGHT,
  "safe_utility_temperature": $SAFE_UTILITY_TEMPERATURE,
  "eligible_set_policy_weight": $ELIGIBLE_POLICY_WEIGHT,
  "eligible_set_policy_temperature": $ELIGIBLE_POLICY_TEMPERATURE,
  "eligibility_boundary_weight": $ELIGIBILITY_BOUNDARY_WEIGHT,
  "eligibility_boundary_margin": $ELIGIBILITY_BOUNDARY_MARGIN,
  "eligibility_logit_temperature": $ELIGIBILITY_LOGIT_TEMPERATURE,
  "eligible_opportunity_threshold": $ELIGIBLE_OPPORTUNITY_THRESHOLD,
  "eligible_harm_threshold": $ELIGIBLE_HARM_THRESHOLD,
  "selection_semantics": "$SELECTION_SEMANTICS",
  "absolute_feasibility_mode": "$ABSOLUTE_FEASIBILITY_MODE_CONTRACT",
  "absolute_feasibility_target": "$([[ "$ABSOLUTE_FEASIBILITY_HEAD" == true || "$ABSOLUTE_OPTION_MARGIN_CORRECTION" == true || "$ABSOLUTE_PHYSICAL_HEADROOM_CORRECTION" == true || "$ABSOLUTE_EXECUTABLE_WITNESS_CORRECTION" == true || "$ABSOLUTE_COMMON_WITNESS_CORRECTION" == true || "$ABSOLUTE_QUANTIFIER_WITNESS_CORRECTION" == true || "$ABSOLUTE_SEMANTIC_WITNESS_CORRECTION" == true ]] && echo '1[R_dep_star(candidate)>=0]' || echo none)",
  "absolute_feasibility_threshold": 0.5,
  "absolute_feasibility_threshold_search": false,
  "safe_hard_negative_weight": $SAFE_HARD_NEGATIVE_WEIGHT,
  "safe_hard_negative_margin": $SAFE_HARD_NEGATIVE_MARGIN,
  "safe_hard_negative_teacher_scale": ${ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_TEACHER_SCALE:-0.0},
  "test_roots_read": false
}
JSON

DIRECT_VALUE_STRICT_SHAPE_CONTRACT="${DIRECT_VALUE_STRICT_SHAPE_CONTRACT:-true}" \
TRAIN_OCRAP_ROOT="${TRAIN_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
EVAL_OCRAP_ROOT="${EVAL_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
TRAIN_MIX="$TRAIN_MIX" VAL_MIX="$VAL_MIX" CAL_MIX="$VAL_MIX" \
RUN="$RUN" MODEL_DIR="$MODEL_DIR" CAL_DIR="$CAL_DIR" \
INIT_CKPT="$INIT_CKPT" VARIANT="$VARIANT" TRAIN_GPU="$TRAIN_GPU" GROUP_INDEX="$GROUP_INDEX" VAL_GROUP_INDEX="${VAL_GROUP_INDEX:-}" \
NUM_WORKERS="${NUM_WORKERS:-4}" PREFETCH_FACTOR="${PREFETCH_FACTOR:-2}" BATCH_SIZE="${BATCH_SIZE:-72}" \
EPOCHS="${EVIDENCE_ADAPT_EPOCHS:-24}" PATIENCE="${EVIDENCE_ADAPT_PATIENCE:-7}" \
LR="${EVIDENCE_ADAPT_LR:-0.00015}" ENCODER_LR_SCALE=0 ENCODER_ANCHOR_WEIGHT=0 \
TRAINABLE_PARAM_PREFIXES="$TRAINABLE_PREFIXES" \
STRICT_INIT_PREFIXES='direct_preference_set_ranker,direct_delta_adapters' \
BEST_METRIC="$BEST_METRIC_NAME" BEST_METRIC_MIN_DELTA="${BEST_METRIC_MIN_DELTA:-0.00001}" \
SKIP_POST_TRAIN_CALIBRATION=1 EXACT_TEACHER_PCD=true \
SET_CONTEXT_ENABLED=false PREFERENCE_HEAD_ENABLED=false PREFERENCE_CONTEXT_ENABLED=false RELATIVE_INCLUDE_ABSOLUTE=false \
SET_TOURNAMENT_ENABLED=true SET_TOURNAMENT_HIDDEN="${SET_TOURNAMENT_HIDDEN:-48}" SET_TOURNAMENT_HEADS="${SET_TOURNAMENT_HEADS:-4}" \
SET_TOURNAMENT_DROPOUT="${SET_TOURNAMENT_DROPOUT:-0.05}" SET_TOURNAMENT_REPLACE_BASE=true \
DELTA_HEAD_ENABLED=true DELTA_MODE=ordinal_evidence DELTA_HIDDEN="${EVIDENCE_HIDDEN:-48}" DELTA_DROPOUT="${EVIDENCE_DROPOUT:-0.02}" \
DELTA_REGIME_EXPERTS=true DELTA_POLICY_FEATURES=true \
EVIDENCE_CALIBRATOR_ENABLED=true EVIDENCE_CALIBRATOR_HIDDEN="$CAL_HIDDEN" EVIDENCE_CALIBRATOR_SCALE="$CAL_SCALE" \
EVIDENCE_CALIBRATOR_MODE=dual_tail_context EVIDENCE_CALIBRATOR_CONTEXT="$CAL_CONTEXT" EVIDENCE_CALIBRATOR_CONTEXT_DETACH=true \
EVIDENCE_CALIBRATOR_CONTEXT_SOURCE="$CAL_CONTEXT_SOURCE" EVIDENCE_DUAL_INTERACTION_BRIDGE="$DUAL_INTERACTION_BRIDGE" EVIDENCE_CALIBRATOR_SHARED=false EVIDENCE_CALIBRATOR_REGIME_SCALE=0 \
EVIDENCE_UNIFIED_EXPERTS=true EVIDENCE_COMPONENT_HEADS="$COMPONENT_HEADS" EVIDENCE_COMPONENT_COUNT="$COMPONENT_COUNT" \
EVIDENCE_CONCORD="$CONCORD_ENABLED" EVIDENCE_ADMISSION_HEAD="$ADMISSION_ENABLED" \
EVIDENCE_ADMISSION_SCALE="${EVIDENCE_ADMISSION_SCALE:-2.0}" EVIDENCE_ADMISSION_BOUNDED="${EVIDENCE_ADMISSION_BOUNDED:-false}" \
EVIDENCE_ADMISSION_PRIOR_DETACH="${EVIDENCE_ADMISSION_PRIOR_DETACH:-true}" EVIDENCE_ADMISSION_PRIOR_MODE="$ADMISSION_PRIOR_MODE" \
EVIDENCE_SLACK_TEMPERATURE="${EVIDENCE_SLACK_TEMPERATURE:-0.025}" EVIDENCE_SLACK_PENALTY="${EVIDENCE_SLACK_PENALTY:-1.0}" EVIDENCE_FRONTIER_CAP_TEMPERATURE="${EVIDENCE_FRONTIER_CAP_TEMPERATURE:-0.10}" \
EVIDENCE_BENEFIT_MARGIN_TEMPERATURE="$BENEFIT_MARGIN_TEMPERATURE" EVIDENCE_JOINT_RESERVE_TEMPERATURE="$JOINT_RESERVE_TEMPERATURE" \
EVIDENCE_CONSENSUS_DISAGREEMENT_PENALTY="$DISAGREEMENT_PENALTY" EVIDENCE_CONSENSUS_PRIOR_SCALE="$CONSENSUS_PRIOR_SCALE" \
EVIDENCE_COMPONENT_SCALE="${EVIDENCE_COMPONENT_SCALE:-6.0}" \
EVIDENCE_BENEFIT_RESIDUAL_SCALE="$BENEFIT_RESIDUAL_SCALE" \
EVIDENCE_UNBOUNDED_BENEFIT_FACTOR="$UNBOUNDED_BENEFIT_FACTOR" EVIDENCE_UNBOUNDED_HARM_FACTORS="$UNBOUNDED_HARM_FACTORS" EVIDENCE_PARTIAL_POOL_HARM_RESIDUAL="$PARTIAL_POOL_HARM_RESIDUAL" EVIDENCE_PARTIAL_POOL_HARM_RESIDUAL_SCALE="$PARTIAL_POOL_HARM_RESIDUAL_SCALE" EVIDENCE_POSTPREFIX_OBS_TRANSPORT_BENEFIT="$POSTPREFIX_OBS_TRANSPORT_BENEFIT" EVIDENCE_POSTPREFIX_OBS_TRANSPORT_HARM="$POSTPREFIX_OBS_TRANSPORT_HARM" EVIDENCE_POSTPREFIX_OBS_TRANSPORT_SCALE="$POSTPREFIX_OBS_TRANSPORT_SCALE" EVIDENCE_ROCT_BENEFIT="$ROCT_BENEFIT" EVIDENCE_ROCT_DEPLOYABILITY="$ROCT_DEPLOYABILITY" EVIDENCE_ROCT_SCALE="$ROCT_SCALE" EVIDENCE_ROCT_ALPHA="$ROCT_ALPHA" EVIDENCE_ROCT_BETA="$ROCT_BETA" EVIDENCE_ROCT_TOP_M="$ROCT_TOP_M" EVIDENCE_ROCT_OPTION_TEMPERATURE="$ROCT_OPTION_TEMPERATURE" \
EVIDENCE_RESERVE_FACTOR_ALIGNMENT="$RESERVE_FACTOR_ALIGNMENT" \
EVIDENCE_FRONTIER="$FRONTIER_ENABLED" EVIDENCE_COMPONENT_PRIOR_LOGIT="$COMPONENT_PRIOR_LOGIT" \
ORDINAL_EVIDENCE_INDEPENDENT_TAILS=true ORDINAL_EVIDENCE_FACTORIZED_HARM=true \
ORDINAL_EVIDENCE_FACTORIZED_HARM_TEMPERATURE="${ORDINAL_EVIDENCE_FACTORIZED_HARM_TEMPERATURE:-0.025}" \
ORDINAL_EVIDENCE_COMPONENT_TAIL_WEIGHT="$COMPONENT_TAIL_WEIGHT" \
ORDINAL_EVIDENCE_COMPONENT_MARGIN_REGRESSION_WEIGHT="${ORDINAL_EVIDENCE_COMPONENT_MARGIN_REGRESSION_WEIGHT:-0.0}" \
ORDINAL_EVIDENCE_COMPONENT_MARGIN_TARGET_MODE="$COMPONENT_MARGIN_TARGET_MODE" \
ORDINAL_EVIDENCE_COMPONENT_MARGIN_TARGET_SCALE="$COMPONENT_MARGIN_TARGET_SCALE" \
ORDINAL_EVIDENCE_COMPONENT_MARGIN_CANONICAL_SCALES="$COMPONENT_MARGIN_CANONICAL_SCALES" \
ORDINAL_EVIDENCE_COMPONENT_MARGIN_REGRESSION_RELIABILITY="$COMPONENT_MARGIN_REGRESSION_RELIABILITY" \
ORDINAL_EVIDENCE_COMPONENT_UNDERESTIMATION_WEIGHT="$COMPONENT_UNDERESTIMATION_WEIGHT" \
ORDINAL_EVIDENCE_SAFE_POSITIVE_COMPONENT_OVERESTIMATION_WEIGHT="$SAFE_POSITIVE_COMPONENT_OVERESTIMATION_WEIGHT" \
ORDINAL_EVIDENCE_BENEFIT_MARGIN_REGRESSION_WEIGHT="$BENEFIT_MARGIN_REGRESSION_WEIGHT" \
ORDINAL_EVIDENCE_BENEFIT_MARGIN_TEMPERATURE="$BENEFIT_MARGIN_TEMPERATURE" \
ORDINAL_EVIDENCE_JOINT_RESERVE_REGRESSION_WEIGHT="$JOINT_RESERVE_REGRESSION_WEIGHT" \
ORDINAL_EVIDENCE_JOINT_RESERVE_BOUNDARY_WEIGHT="$JOINT_RESERVE_BOUNDARY_WEIGHT" \
ORDINAL_EVIDENCE_JOINT_RESERVE_BOUNDARY_WIDTH="$JOINT_RESERVE_BOUNDARY_WIDTH" \
ORDINAL_EVIDENCE_BATCH_BALANCED="$BATCH_BALANCED" ORDINAL_EVIDENCE_GLOBAL_BALANCE="$GLOBAL_BALANCE" \
ORDINAL_EVIDENCE_BALANCED_REPLACES_ERM=false \
ORDINAL_EVIDENCE_SAFE_SET_TEMPERATURE="${ORDINAL_EVIDENCE_SAFE_SET_TEMPERATURE:-0.08}" \
ORDINAL_EVIDENCE_SAFE_BENEFIT_TARGET="$SAFE_BENEFIT_TARGET" \
ORDINAL_EVIDENCE_GROUP_OPPORTUNITY_WEIGHT="$GROUP_OPPORTUNITY_WEIGHT" \
ORDINAL_EVIDENCE_CATEGORICAL_GROUP_POLICY="$CATEGORICAL_GROUP_POLICY" \
ORDINAL_EVIDENCE_BENEFIT_LISTWISE_WEIGHT="$BENEFIT_LISTWISE_WEIGHT" \
ORDINAL_EVIDENCE_BENEFIT_LISTWISE_TEMPERATURE="$BENEFIT_LISTWISE_TEMPERATURE" \
ORDINAL_EVIDENCE_SAFE_UTILITY_REGRESSION_WEIGHT="$SAFE_UTILITY_REGRESSION_WEIGHT" \
ORDINAL_EVIDENCE_SAFE_UTILITY_LISTWISE_WEIGHT="$SAFE_UTILITY_LISTWISE_WEIGHT" \
ORDINAL_EVIDENCE_SAFE_UTILITY_TEMPERATURE="$SAFE_UTILITY_TEMPERATURE" \
ORDINAL_EVIDENCE_ELIGIBLE_POLICY_WEIGHT="$ELIGIBLE_POLICY_WEIGHT" \
ORDINAL_EVIDENCE_ELIGIBLE_POLICY_TEMPERATURE="$ELIGIBLE_POLICY_TEMPERATURE" \
ORDINAL_EVIDENCE_ELIGIBILITY_LOGIT_TEMPERATURE="$ELIGIBILITY_LOGIT_TEMPERATURE" \
ORDINAL_EVIDENCE_ELIGIBLE_OPPORTUNITY_THRESHOLD="$ELIGIBLE_OPPORTUNITY_THRESHOLD" \
ORDINAL_EVIDENCE_ELIGIBLE_HARM_THRESHOLD="$ELIGIBLE_HARM_THRESHOLD" \
ORDINAL_EVIDENCE_ELIGIBILITY_BOUNDARY_WEIGHT="$ELIGIBILITY_BOUNDARY_WEIGHT" \
ORDINAL_EVIDENCE_ELIGIBILITY_BOUNDARY_MARGIN="$ELIGIBILITY_BOUNDARY_MARGIN" \
ORDINAL_EVIDENCE_FRONTIER_PAIRWISE_WEIGHT="$FRONTIER_PAIRWISE_WEIGHT" \
ORDINAL_EVIDENCE_FRONTIER_PAIRWISE_MARGIN="$FRONTIER_PAIRWISE_MARGIN" \
ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_WEIGHT="$SAFE_HARD_NEGATIVE_WEIGHT" \
ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_MARGIN="$SAFE_HARD_NEGATIVE_MARGIN" \
ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_TEACHER_SCALE="${ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_TEACHER_SCALE:-0.0}" \
ORDINAL_EVIDENCE_ADMISSION_WEIGHT="${ORDINAL_EVIDENCE_ADMISSION_WEIGHT:-1.0}" \
ORDINAL_EVIDENCE_ADMISSION_POS_WEIGHT="${ORDINAL_EVIDENCE_ADMISSION_POS_WEIGHT:-6.0}" \
ORDINAL_EVIDENCE_ADMISSION_HARM_NEGATIVE_WEIGHT="${ORDINAL_EVIDENCE_ADMISSION_HARM_NEGATIVE_WEIGHT:-2.5}" \
EVALUATE_INITIAL_CHECKPOINT="${EVALUATE_INITIAL_CHECKPOINT:-true}" \
DETERMINISTIC_ALGORITHMS="${DETERMINISTIC_ALGORITHMS:-true}" CUDNN_BENCHMARK="${CUDNN_BENCHMARK:-false}" \
GROUP_BATCH_STRATIFIED="$STRATIFIED_BATCHES" GROUP_BATCHING_REPLACEMENT="${GROUP_BATCHING_REPLACEMENT:-true}" GROUP_BATCH_SAFE_POSITIVE_TARGET="${GROUP_BATCH_SAFE_POSITIVE_TARGET:-true}" GROUP_BATCH_POSITIVE_FRACTION="${GROUP_BATCH_POSITIVE_FRACTION:-0.50}" \
GROUP_BATCH_HARMFUL_FRACTION="${GROUP_BATCH_HARMFUL_FRACTION:-0.30}" GROUP_BATCH_DEAD_FRACTION="${GROUP_BATCH_DEAD_FRACTION:-0.20}" \
POSITIVE_GROUP_BOOST="${POSITIVE_GROUP_BOOST:-1.0}" POSITIVE_MACRO_BALANCE_POWER="${POSITIVE_MACRO_BALANCE_POWER:-0.50}" SCENE_BALANCE_POWER="${SCENE_BALANCE_POWER:-0.50}" \
POINT_WEIGHT=0 VALUE_LISTWISE_WEIGHT=0 CENTERED_WEIGHT=0 ADVANTAGE_WEIGHT=0 SETWISE_W="$SETWISE_WEIGHT" \
OPPORTUNITY_ADMISSION_WEIGHT="${OPPORTUNITY_ADMISSION_WEIGHT:-1.0}" HARM_ADMISSION_WEIGHT="${HARM_ADMISSION_WEIGHT:-1.5}" \
SELECTIVE_RISK_WEIGHT="${SELECTIVE_RISK_WEIGHT:-0.75}" SELECTIVE_HARM_BUDGET="${SELECTIVE_HARM_BUDGET:-0.05}" \
SELECTIVE_COVERAGE_WEIGHT="${SELECTIVE_COVERAGE_WEIGHT:-0.25}" SELECTIVE_COVERAGE_TARGET="${SELECTIVE_COVERAGE_TARGET:-0.50}" \
POLICY_DISTILL_WEIGHT=0 POLICY_REGRET_WEIGHT=0 POLICY_ADMISSION_DISTILL_WEIGHT=0 \
PREFERENCE_WEIGHT=0 PREFERENCE_REGRET_WEIGHT=0 PREFERENCE_LISTWISE_WEIGHT=0 PREFERENCE_GAP_WEIGHT=0 \
PREFERENCE_SET_WEIGHT=0 PREFERENCE_ALL_GROUP_SET_WEIGHT=0 PREFERENCE_CONDITIONAL_SET_WEIGHT=0 PREFERENCE_PROPOSAL_TOPK_WEIGHT=0 \
DELTA_NLL_WEIGHT=0 DELTA_SIGN_WEIGHT=0 CERTIFICATE_POLICY_TOP1_WEIGHT=0 CERTIFICATE_POLICY_TOP1_SIGN_WEIGHT=0 \
ORDINAL_EVIDENCE_POLICY_TOP1_WEIGHT=0 ORDINAL_EVIDENCE_ALL_CANDIDATE_WEIGHT=0 \
ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT:-0.10}" \
ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT:-0.10}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT="${ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT:-0.35}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK="$PROPOSAL_TOP_K" ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY="${ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY:-0.85}" \
ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT="${ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT:-1.00}" \
ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT="${ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT:-2.00}" \
ORDINAL_EVIDENCE_CLASS_BALANCED_WEIGHT="${ORDINAL_EVIDENCE_CLASS_BALANCED_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_BENEFIT_MARGIN_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_MARGIN_WEIGHT:-0.25}" \
ORDINAL_EVIDENCE_HARM_MARGIN_WEIGHT="${ORDINAL_EVIDENCE_HARM_MARGIN_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_TARGET_PROBABILITY="${ORDINAL_EVIDENCE_TARGET_PROBABILITY:-0.65}" \
EVIDENCE_CALIBRATOR_ANCHOR_WEIGHT="${EVIDENCE_CALIBRATOR_ANCHOR_WEIGHT:-0.05}" \
ORDINAL_EVIDENCE_INTRAGROUP_BENEFIT_WEIGHT="${ORDINAL_EVIDENCE_INTRAGROUP_BENEFIT_WEIGHT:-0.10}" \
ORDINAL_EVIDENCE_INTRAGROUP_HARM_WEIGHT="${ORDINAL_EVIDENCE_INTRAGROUP_HARM_WEIGHT:-0.15}" \
ORDINAL_EVIDENCE_PAIRWISE_BENEFIT_WEIGHT=0 ORDINAL_EVIDENCE_PAIRWISE_HARM_WEIGHT=0 \
POLICY_METRIC_RISK_SOURCE=ordinal_evidence POLICY_METRIC_PROPOSAL_TOP_K="$PROPOSAL_TOP_K" POLICY_METRIC_EVIDENCE_RERANK_TOP_K=true \
POLICY_METRIC_EXACT_ELIGIBILITY=true POLICY_METRIC_MAX_HARD="${POLICY_METRIC_MAX_HARD:-1.0}" POLICY_METRIC_MIN_NOMINAL_DEVIATION="${POLICY_METRIC_MIN_NOMINAL_DEVIATION:-0.002}" \
POLICY_METRIC_SAFE_OPPORTUNITY=true POLICY_METRIC_SOFT_TEMPERATURE="${POLICY_METRIC_SOFT_TEMPERATURE:-0.10}" \
POLICY_METRIC_ELIGIBILITY_LOGIT_TEMPERATURE="${POLICY_METRIC_ELIGIBILITY_LOGIT_TEMPERATURE:-${ORDINAL_EVIDENCE_ELIGIBILITY_LOGIT_TEMPERATURE:-0.25}}" \
POLICY_METRIC_CATEGORICAL_GROUP_POLICY="$CATEGORICAL_GROUP_POLICY" \
POLICY_METRIC_CONCORD_MISS_WEIGHT="${POLICY_METRIC_CONCORD_MISS_WEIGHT:-2.0}" \
POLICY_METRIC_CONCORD_FALSE_WEIGHT="${POLICY_METRIC_CONCORD_FALSE_WEIGHT:-0.75}" \
POLICY_METRIC_CONCORD_HARM_WEIGHT="${POLICY_METRIC_CONCORD_HARM_WEIGHT:-2.0}" \
POLICY_METRIC_CONCORD_REGRET_WEIGHT="${POLICY_METRIC_CONCORD_REGRET_WEIGHT:-0.50}" \
POLICY_METRIC_CONCORD_SAFE_MASS_WEIGHT="${POLICY_METRIC_CONCORD_SAFE_MASS_WEIGHT:-1.0}" \
POLICY_METRIC_FRONTIER_HARM_WEIGHT="${POLICY_METRIC_FRONTIER_HARM_WEIGHT:-1.5}" POLICY_METRIC_FRONTIER_FALSE_WEIGHT="${POLICY_METRIC_FRONTIER_FALSE_WEIGHT:-0.5}" \
POLICY_METRIC_INTEGRITY_MIN_RECALL="${POLICY_METRIC_INTEGRITY_MIN_RECALL:-0.20}" POLICY_METRIC_INTEGRITY_RECALL_WEIGHT="${POLICY_METRIC_INTEGRITY_RECALL_WEIGHT:-20.0}" \
POLICY_METRIC_INTEGRITY_MIN_PRECISION="${POLICY_METRIC_INTEGRITY_MIN_PRECISION:-0.60}" POLICY_METRIC_INTEGRITY_PRECISION_WEIGHT="${POLICY_METRIC_INTEGRITY_PRECISION_WEIGHT:-8.0}" \
POLICY_METRIC_INTEGRITY_INVALID_WEIGHT="${POLICY_METRIC_INTEGRITY_INVALID_WEIGHT:-4.0}" POLICY_METRIC_INTEGRITY_SAFE_REGRET_WEIGHT="${POLICY_METRIC_INTEGRITY_SAFE_REGRET_WEIGHT:-2.0}" \
POLICY_METRIC_INTEGRITY_ALL_ABSTAIN_WEIGHT="${POLICY_METRIC_INTEGRITY_ALL_ABSTAIN_WEIGHT:-8.0}" \
POLICY_METRIC_CONTRACT_MIN_SAFE_TOP1_RECALL="${POLICY_METRIC_CONTRACT_MIN_SAFE_TOP1_RECALL:-0.20}" \
POLICY_METRIC_CONTRACT_ZERO_TOP1_WEIGHT="${POLICY_METRIC_CONTRACT_ZERO_TOP1_WEIGHT:-100.0}" \
POLICY_METRIC_CONTRACT_TOP1_SHORTFALL_WEIGHT="${POLICY_METRIC_CONTRACT_TOP1_SHORTFALL_WEIGHT:-20.0}" \
POLICY_METRIC_CONTRACT_ALL_ABSTAIN_WEIGHT="${POLICY_METRIC_CONTRACT_ALL_ABSTAIN_WEIGHT:-10.0}" \
POLICY_METRIC_MIN_FOLD_POSITIVE="${POLICY_METRIC_MIN_FOLD_POSITIVE:-6}" POLICY_METRIC_ROBUST_TOP_K="${POLICY_METRIC_ROBUST_TOP_K:-2}" \
POLICY_METRIC_HARM_WEIGHT="${POLICY_METRIC_HARM_WEIGHT:-0.50}" POLICY_METRIC_FALSE_WEIGHT="${POLICY_METRIC_FALSE_WEIGHT:-0.15}" \
POLICY_METRIC_MISS_WEIGHT="${POLICY_METRIC_MISS_WEIGHT:-1.25}" POLICY_METRIC_MIN_POSITIVE_RECALL="${POLICY_METRIC_MIN_POSITIVE_RECALL:-0.20}" \
POLICY_METRIC_RECALL_SHORTFALL_WEIGHT="${POLICY_METRIC_RECALL_SHORTFALL_WEIGHT:-4.0}" \
POLICY_METRIC_CROSS_MIN_RECALL="${POLICY_METRIC_CROSS_MIN_RECALL:-0.20}" POLICY_METRIC_CROSS_RECALL_WEIGHT="${POLICY_METRIC_CROSS_RECALL_WEIGHT:-2.0}" \
POLICY_METRIC_CROSS_HARM_WEIGHT="${POLICY_METRIC_CROSS_HARM_WEIGHT:-0.50}" POLICY_METRIC_CROSS_FALSE_WEIGHT="${POLICY_METRIC_CROSS_FALSE_WEIGHT:-0.20}" \
POLICY_METRIC_FACET_MIN_RECALL="${POLICY_METRIC_FACET_MIN_RECALL:-0.20}" POLICY_METRIC_FACET_HARM_BUDGET="${POLICY_METRIC_FACET_HARM_BUDGET:-0.05}" \
POLICY_METRIC_FACET_FALSE_BUDGET="${POLICY_METRIC_FACET_FALSE_BUDGET:-0.10}" POLICY_METRIC_FACET_BASE_WEIGHT="${POLICY_METRIC_FACET_BASE_WEIGHT:-0.10}" \
POLICY_METRIC_FACET_RECALL_WEIGHT="${POLICY_METRIC_FACET_RECALL_WEIGHT:-12.0}" POLICY_METRIC_FACET_HARM_EXCESS_WEIGHT="${POLICY_METRIC_FACET_HARM_EXCESS_WEIGHT:-10.0}" \
POLICY_METRIC_FACET_FALSE_EXCESS_WEIGHT="${POLICY_METRIC_FACET_FALSE_EXCESS_WEIGHT:-3.0}" \
COMPONENT_HARM_DRS_TOLERANCE="${COMPONENT_HARM_DRS_TOLERANCE:-0.05}" COMPONENT_HARM_DEP_TOLERANCE="${COMPONENT_HARM_DEP_TOLERANCE:-0.05}" \
COMPONENT_HARM_GAP_TOLERANCE="${COMPONENT_HARM_GAP_TOLERANCE:-0.05}" COMPONENT_HARM_HARD_TOLERANCE="${COMPONENT_HARM_HARD_TOLERANCE:-0.05}" \
COMPONENT_HARM_PROXY_TOLERANCE="${COMPONENT_HARM_PROXY_TOLERANCE:-0.05}" \
ABSOLUTE_FEASIBILITY_HEAD="$ABSOLUTE_FEASIBILITY_HEAD" ABSOLUTE_OPTION_MARGIN_CORRECTION="$ABSOLUTE_OPTION_MARGIN_CORRECTION" ABSOLUTE_PHYSICAL_HEADROOM_CORRECTION="$ABSOLUTE_PHYSICAL_HEADROOM_CORRECTION" ABSOLUTE_EXECUTABLE_WITNESS_CORRECTION="$ABSOLUTE_EXECUTABLE_WITNESS_CORRECTION" ABSOLUTE_COMMON_WITNESS_CORRECTION="$ABSOLUTE_COMMON_WITNESS_CORRECTION" ABSOLUTE_QUANTIFIER_WITNESS_CORRECTION="$ABSOLUTE_QUANTIFIER_WITNESS_CORRECTION" ABSOLUTE_SEMANTIC_WITNESS_CORRECTION="$ABSOLUTE_SEMANTIC_WITNESS_CORRECTION" SEMANTIC_WITNESS_ACTIVE_SET_ALIGNMENT="$SEMANTIC_WITNESS_ACTIVE_SET_ALIGNMENT" SEMANTIC_WITNESS_PATH_STOP_ALIGNMENT="$SEMANTIC_WITNESS_PATH_STOP_ALIGNMENT" SEMANTIC_WITNESS_CLASSLOCAL_TRANSPORT="$SEMANTIC_WITNESS_CLASSLOCAL_TRANSPORT" SEMANTIC_WITNESS_ROUTE_ALIGNMENT="$SEMANTIC_WITNESS_ROUTE_ALIGNMENT" SEMANTIC_WITNESS_REENTRY_ALIGNMENT="$SEMANTIC_WITNESS_REENTRY_ALIGNMENT" SEMANTIC_WITNESS_CONTROL_PROJECTION="$SEMANTIC_WITNESS_CONTROL_PROJECTION" SEMANTIC_WITNESS_BOUNDARY_TRANSPORT="$SEMANTIC_WITNESS_BOUNDARY_TRANSPORT" SEMANTIC_WITNESS_PROJECTION_FIDELITY="$SEMANTIC_WITNESS_PROJECTION_FIDELITY" SEMANTIC_WITNESS_ACTIVE_CONSTRAINT_TYPED_SOURCE="$SEMANTIC_WITNESS_ACTIVE_CONSTRAINT_TYPED_SOURCE" SEMANTIC_WITNESS_ROOT_TAIL_SOURCE="$SEMANTIC_WITNESS_ROOT_TAIL_SOURCE" SEMANTIC_WITNESS_STRUCTURED_TAIL_FIELD="$SEMANTIC_WITNESS_STRUCTURED_TAIL_FIELD" SEMANTIC_WITNESS_SIGNED_TAIL_CHANNELS="$SEMANTIC_WITNESS_SIGNED_TAIL_CHANNELS" SEMANTIC_WITNESS_COUNTERFACTUAL_TAIL_RESPONSE="$SEMANTIC_WITNESS_COUNTERFACTUAL_TAIL_RESPONSE" SEMANTIC_WITNESS_TAIL_LOCALIZATION="$SEMANTIC_WITNESS_TAIL_LOCALIZATION" SEMANTIC_WITNESS_DEMAND_NORMALIZED_FIDELITY="$SEMANTIC_WITNESS_DEMAND_NORMALIZED_FIDELITY" SEMANTIC_WITNESS_ROBUST_OCCUPANCY="$SEMANTIC_WITNESS_ROBUST_OCCUPANCY" SEMANTIC_WITNESS_SOFT_OCCUPANCY_DISAGREEMENT="$SEMANTIC_WITNESS_SOFT_OCCUPANCY_DISAGREEMENT" SEMANTIC_WITNESS_BOUNDARY_LOCALIZED_OCCUPANCY_TRUST="$SEMANTIC_WITNESS_BOUNDARY_LOCALIZED_OCCUPANCY_TRUST" SEMANTIC_WITNESS_HISTORY_OCCUPANCY_REACHABILITY="$SEMANTIC_WITNESS_HISTORY_OCCUPANCY_REACHABILITY" SEMANTIC_WITNESS_INTERACTION_BOX_SUPPORT="$SEMANTIC_WITNESS_INTERACTION_BOX_SUPPORT" SEMANTIC_WITNESS_INTERACTION_HULL_SUPPORT="$SEMANTIC_WITNESS_INTERACTION_HULL_SUPPORT" SEMANTIC_WITNESS_INTERACTION_ANCHOR_SUPPORT="$SEMANTIC_WITNESS_INTERACTION_ANCHOR_SUPPORT" SEMANTIC_WITNESS_INTERACTION_RESPONSE_SUPPORT="$SEMANTIC_WITNESS_INTERACTION_RESPONSE_SUPPORT" ABSOLUTE_FEASIBILITY_WEIGHT="$ABSOLUTE_FEASIBILITY_WEIGHT" ABSOLUTE_FEASIBILITY_TRUTH_CONTRACT="$ABSOLUTE_FEASIBILITY_TRUTH_CONTRACT" ABSOLUTE_FEASIBILITY_SUPERVISION_OBJECTIVE="$ABSOLUTE_FEASIBILITY_SUPERVISION_OBJECTIVE" ABSOLUTE_FEASIBILITY_TRUTH_INDEX="$ABSOLUTE_FEASIBILITY_TRUTH_INDEX" \
GROUP_DRO_WEIGHT=0 OPPORTUNITY_AUX_WEIGHT=0 HARM_W=0 EXPERT_SPECIALIZATION_WEIGHT=0 \
  bash scripts/train_ocrap_v48_trac_sr.sh

cat > "$RUN/POLICY_CONTRACT.env" <<EOF
RISK_SOURCE=ordinal_evidence
CONDITIONAL_RECOVERY_RANKING=true
POLICY_FIRST_NO_FALLBACK=false
PROPOSAL_TOP_K=$PROPOSAL_TOP_K
EVIDENCE_RERANK_TOP_K=true
MACRO_CONSTRAINT_MODE=opportunity_normalized
MAX_MACRO_EXCESS_SHARE=${MAX_MACRO_EXCESS_SHARE:-0.15}
HARM_LABEL_MODE=component_veto
OPPORTUNITY_LABEL_MODE=raw_benefit
GATE_POSITIVE_MODE=safe_benefit
ADMISSION_LABEL_MODE=$([[ "$ADMISSION_PRIOR_MODE" == joint_reserve ]] && echo deterministic_joint_physical_reserve || echo continuous_safe_utility_with_component_veto)
CALIBRATION_PROTOCOL=v48_36_ocaf_shared_rule_dev_frozen_full_certificate_verification
SELECTION_SEMANTICS=$SELECTION_SEMANTICS
ABSOLUTE_FEASIBILITY_MODE=$ABSOLUTE_FEASIBILITY_MODE_CONTRACT
ABSOLUTE_FEASIBILITY_THRESHOLD=0.5
ABSOLUTE_FEASIBILITY_TRUTH_CONTRACT=$ABSOLUTE_FEASIBILITY_TRUTH_CONTRACT
ABSOLUTE_FEASIBILITY_SUPERVISION_OBJECTIVE=$ABSOLUTE_FEASIBILITY_SUPERVISION_OBJECTIVE
ABSOLUTE_FEASIBILITY_TRUTH_INDEX=$ABSOLUTE_FEASIBILITY_TRUTH_INDEX
EOF

python - "$RUN" "$MODEL_DIR/best.pt" "$INIT_CKPT" "$MAX_CALIBRATOR_PARAMS" "$BEST_METRIC_NAME" "$COMPONENT_HEADS" "$SETWISE_WEIGHT" "$COMPONENT_TAIL_WEIGHT" "$TRAINABLE_PREFIXES" "$CAL_CONTEXT_SOURCE" "$CONSENSUS_PRIOR_SCALE" "$ALGORITHM_VARIANT" <<'PY_VERIFY'
import hashlib,json,pathlib,sys,time,torch
run,ckpt,source=map(pathlib.Path,sys.argv[1:4])
max_params=int(sys.argv[4]); best_metric=sys.argv[5]
component_heads=sys.argv[6].lower()=='true'; setwise=float(sys.argv[7]); component_tail=float(sys.argv[8])
declared=[x.strip() for x in sys.argv[9].split(',') if x.strip()]
context_source=sys.argv[10]; consensus_prior_scale=float(sys.argv[11]); algorithm_variant=sys.argv[12]
if not ckpt.is_file(): raise SystemExit(f'missing adapted checkpoint: {ckpt}')
try: doc=torch.load(ckpt,map_location='cpu',weights_only=False)
except TypeError: doc=torch.load(ckpt,map_location='cpu')
state=doc.get('model_state',{})
checkpoint_declared=[str(x) for x in (doc.get('trainable_param_prefixes') or [])]
if checkpoint_declared != declared:
    raise SystemExit(f'trainable prefix contract mismatch: checkpoint={checkpoint_declared}, declared={declared}')
matched={prefix:[k for k in state if k == prefix or k.startswith(prefix+'.')] for prefix in declared}
missing=[prefix for prefix,keys in matched.items() if not keys]
if missing: raise SystemExit(f'declared trainable prefixes absent from checkpoint: {missing}')
trainable=sum(state[k].numel() for keys in matched.values() for k in keys)
if trainable <= 0: raise SystemExit('no parameters matched the exact trainable-prefix contract')
if max_params > 0 and trainable > max_params:
    raise SystemExit(f'explicit calibrator parameter budget exceeded: {trainable}>{max_params}')
bridge_keys=[k for k in state if k.startswith('direct_evidence_interaction_bridge.')]
bridge_trainable=bool(matched.get('direct_evidence_interaction_bridge',[]))
if context_source == 'physical_interaction' and not bridge_keys:
    raise SystemExit('OCAF context requires direct_evidence_interaction_bridge weights in the checkpoint')
if context_source != 'physical_interaction' and bridge_keys:
    raise SystemExit('non-OCAF ablation unexpectedly trains the interaction bridge')
legacy=[k for k in state if k.startswith(('direct_evidence_calibrators.','direct_evidence_shared_calibrator.'))]
meta={
 'event':'v48_36_ocaf_evidence_correction_complete','version':'v48.36-OCAF','created_unix':time.time(),
 'checkpoint':str(ckpt),'checkpoint_sha256':hashlib.sha256(ckpt.read_bytes()).hexdigest(),
 'source_checkpoint':str(source),'source_checkpoint_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
 'frozen_policy':True,'frozen_source_experts':True,'regime_id_exposed_to_evidence_model':False,
 'trainable_prefixes':declared,'matched_state_keys':matched,'trainable_state_params':trainable,
 'generic_architecture_parameter_cap_disabled':max_params == 0,'explicit_parameter_cap':max_params,
 'exact_checkpoint_prefix_match_not_architecture_agnostic_cap':True,
 'legacy_evidence_keys_loaded_but_frozen':len(legacy),'source_expert_use':'both_experts_for_every_candidate',
 'benefit_transfer':'scaled_mean_consensus_minus_disagreement_plus_observation_conditioned_action_residual',
 'consensus_prior_scale':consensus_prior_scale,'context_source':context_source,
 'observation_conditioned_action_frontier':context_source=='physical_interaction',
 'interaction_bridge_trainable_this_stage':bridge_trainable,
 'action_zero_implies_zero_interaction':context_source=='physical_interaction',
 'scene_context_cannot_create_action_free_signal':context_source=='physical_interaction',
 'frontier_runtime_wiring_verified':True,
 'admission_residual_bounded':bool(doc.get('direct_recovery_evidence_admission_bounded',False)),
 'harm_transfer':'deadband_centered_component_residual_logits',
 'component_harm_heads':component_heads,'component_harm_count':int(doc.get('direct_recovery_evidence_component_count',3)),
 'admission_head':any(k.startswith('direct_evidence_concord_admission_calibrator.') for k in state),
 'setwise_admission_weight':setwise,'component_tail_weight':component_tail,
 'balanced_replaces_group_erm':False,'checkpoint_metric':best_metric,'categorical_group_policy':True,
 'benefit_listwise':float(doc.get('train_config',{}).get('ordinal_evidence_benefit_listwise_weight',0.0) or 0.0)>0,
 'safe_utility_regression':float(doc.get('train_config',{}).get('ordinal_evidence_safe_utility_regression_weight',0.0) or 0.0)>0,
 'safe_utility_listwise':float(doc.get('train_config',{}).get('ordinal_evidence_safe_utility_listwise_weight',0.0) or 0.0)>0,
 'frontier_contrast':float(doc.get('train_config',{}).get('ordinal_evidence_frontier_pairwise_weight',0.0) or 0.0)>0,
 'benefit_margin_regression_weight':float(doc.get('train_config',{}).get('ordinal_evidence_benefit_margin_regression_weight',0.0) or 0.0),
 'benefit_margin_temperature':float(doc.get('train_config',{}).get('ordinal_evidence_benefit_margin_temperature',0.025) or 0.025),
 'component_underestimation_weight':float(doc.get('train_config',{}).get('ordinal_evidence_component_underestimation_weight',0.0) or 0.0),
 'safe_positive_component_overestimation_weight':float(doc.get('train_config',{}).get('ordinal_evidence_safe_positive_component_overestimation_weight',0.0) or 0.0),
 'joint_reserve_regression_weight':float(doc.get('train_config',{}).get('ordinal_evidence_joint_reserve_regression_weight',0.0) or 0.0),
 'joint_reserve_boundary_weight':float(doc.get('train_config',{}).get('ordinal_evidence_joint_reserve_boundary_weight',0.0) or 0.0),
 'joint_reserve_boundary_width':float(doc.get('train_config',{}).get('ordinal_evidence_joint_reserve_boundary_width',0.05) or 0.05),
 'partial_pool_harm_residual':bool(doc.get('direct_recovery_evidence_partial_pool_harm_residual',False)),
 'partial_pool_harm_residual_scale':float(doc.get('direct_recovery_evidence_partial_pool_harm_residual_scale',0.50) or 0.50),
 'rank_benefit_skip':bool(doc.get('direct_recovery_evidence_rank_benefit_skip',False)),
 'rank_benefit_gain_init':float(doc.get('direct_recovery_evidence_rank_benefit_gain_init',1.0) or 1.0),
 'postprefix_obs_transport_benefit':bool(doc.get('direct_recovery_evidence_postprefix_obs_transport_benefit',False)),
 'postprefix_obs_transport_harm':bool(doc.get('direct_recovery_evidence_postprefix_obs_transport_harm',False)),
 'postprefix_obs_transport_scale':float(doc.get('direct_recovery_evidence_postprefix_obs_transport_scale',1.0) or 1.0),
 'roct_benefit':bool(doc.get('direct_recovery_evidence_roct_benefit',False)),
 'roct_deployability':bool(doc.get('direct_recovery_evidence_roct_deployability',False)),
 'roct_scale':float(doc.get('direct_recovery_evidence_roct_scale',1.0) or 1.0),
 'roct_alpha':float(doc.get('direct_recovery_evidence_roct_alpha',0.2) or 0.2),
 'roct_beta':float(doc.get('direct_recovery_evidence_roct_beta',0.2) or 0.2),
 'roct_top_m':int(doc.get('direct_recovery_evidence_roct_top_m',8) or 8),
 'roct_option_temperature':float(doc.get('direct_recovery_evidence_roct_option_temperature',0.35) or 0.35),
 'common_measure_root_mass':bool(doc.get('direct_recovery_evidence_common_measure_root_mass',False)),
 'algorithm_variant':algorithm_variant,
 'test_roots_read':False,
}
out=run/'EVIDENCE_CORRECTION_COMPLETE.json'; tmp=out.with_name(f'.{out.name}.tmp.{time.time_ns()}')
tmp.write_text(json.dumps(meta,indent=2)+'\n',encoding='utf-8'); tmp.replace(out)
PY_VERIFY
