#!/usr/bin/env bash
set -Eeuo pipefail

# v48.33 ELIGIBLE-SET-POLICY
# One unified, regime-agnostic selector trains and validates the exact deployed
# order: frozen rank proposal -> opportunity/harm eligibility -> evidence rerank
# -> one recovery action or nominal.  No regime id or regime-specific policy is
# exposed to the model.
REPO="${OCRAP_REPO:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO"
export PYTHONPATH="$REPO/src${PYTHONPATH:+:$PYTHONPATH}"
export CUBLAS_WORKSPACE_CONFIG="${CUBLAS_WORKSPACE_CONFIG:-:4096:8}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:128}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-2}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-2}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-2}"

RUN="${RUN:?RUN is required}"
INIT_CKPT="${INIT_CKPT:?INIT_CKPT is required}"
VARIANT="${VARIANT:?VARIANT is required}"
TRAIN_MIX="${TRAIN_MIX:?TRAIN_MIX is required}"
VAL_MIX="${VAL_MIX:?VAL_MIX is required}"
GROUP_INDEX="${GROUP_INDEX:?GROUP_INDEX is required}"
TRAIN_GPU="${TRAIN_GPU:-0}"
MODEL_DIR="${MODEL_DIR:-$RUN/model_v48_trac_sr}"
CAL_DIR="${CAL_DIR:-$RUN/calibration}"
mkdir -p "$RUN/logs" "$MODEL_DIR" "$CAL_DIR"

PROPOSAL_TOP_K="${PROPOSAL_TOP_K:-5}"
CAL_HIDDEN="${EVIDENCE_CALIBRATOR_HIDDEN:-16}"
CAL_SCALE="${EVIDENCE_CALIBRATOR_SCALE:-0.75}"
CAL_CONTEXT="${EVIDENCE_CALIBRATOR_CONTEXT:-true}"
CAL_CONTEXT_SOURCE="${EVIDENCE_CALIBRATOR_CONTEXT_SOURCE:-tournament}"
COMPONENT_HEADS="${EVIDENCE_COMPONENT_HEADS:-true}"
COMPONENT_COUNT="${EVIDENCE_COMPONENT_COUNT:-5}"
SETWISE_WEIGHT="${SETWISE_W:-1.00}"
COMPONENT_TAIL_WEIGHT="${ORDINAL_EVIDENCE_COMPONENT_TAIL_WEIGHT:-0.50}"
BATCH_BALANCED="${ORDINAL_EVIDENCE_BATCH_BALANCED:-true}"
GLOBAL_BALANCE="${ORDINAL_EVIDENCE_GLOBAL_BALANCE:-true}"
MAX_CALIBRATOR_PARAMS="${MAX_EVIDENCE_CALIBRATOR_PARAMS:-8000}"
BEST_METRIC_NAME="${BEST_METRIC:-direct_contract_safe_rank_risk}"
STRATIFIED_BATCHES="${GROUP_BATCH_STRATIFIED:-true}"
CONCORD_ENABLED="${EVIDENCE_CONCORD:-true}"
ADMISSION_ENABLED="${EVIDENCE_ADMISSION_HEAD:-true}"
SAFE_BENEFIT_TARGET="${ORDINAL_EVIDENCE_SAFE_BENEFIT_TARGET:-false}"
GROUP_OPPORTUNITY_WEIGHT="${ORDINAL_EVIDENCE_GROUP_OPPORTUNITY_WEIGHT:-0.0}"
DISAGREEMENT_PENALTY="${EVIDENCE_CONSENSUS_DISAGREEMENT_PENALTY:-0.15}"

FRONTIER_ENABLED="${EVIDENCE_FRONTIER:-true}"
COMPONENT_PRIOR_LOGIT="${EVIDENCE_COMPONENT_PRIOR_LOGIT:--2.0}"
CATEGORICAL_GROUP_POLICY="${ORDINAL_EVIDENCE_CATEGORICAL_GROUP_POLICY:-true}"
BENEFIT_LISTWISE_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_LISTWISE_WEIGHT:-0.75}"
BENEFIT_LISTWISE_TEMPERATURE="${ORDINAL_EVIDENCE_BENEFIT_LISTWISE_TEMPERATURE:-0.08}"
FRONTIER_PAIRWISE_WEIGHT="${ORDINAL_EVIDENCE_FRONTIER_PAIRWISE_WEIGHT:-0.75}"
FRONTIER_PAIRWISE_MARGIN="${ORDINAL_EVIDENCE_FRONTIER_PAIRWISE_MARGIN:-0.05}"
SAFE_UTILITY_REGRESSION_WEIGHT="${ORDINAL_EVIDENCE_SAFE_UTILITY_REGRESSION_WEIGHT:-0.50}"
SAFE_UTILITY_LISTWISE_WEIGHT="${ORDINAL_EVIDENCE_SAFE_UTILITY_LISTWISE_WEIGHT:-0.25}"
SAFE_UTILITY_TEMPERATURE="${ORDINAL_EVIDENCE_SAFE_UTILITY_TEMPERATURE:-0.10}"
ELIGIBLE_POLICY_WEIGHT="${ORDINAL_EVIDENCE_ELIGIBLE_POLICY_WEIGHT:-0.0}"
ELIGIBLE_POLICY_TEMPERATURE="${ORDINAL_EVIDENCE_ELIGIBLE_POLICY_TEMPERATURE:-0.10}"
ELIGIBILITY_LOGIT_TEMPERATURE="${ORDINAL_EVIDENCE_ELIGIBILITY_LOGIT_TEMPERATURE:-0.25}"
ELIGIBLE_OPPORTUNITY_THRESHOLD="${ORDINAL_EVIDENCE_ELIGIBLE_OPPORTUNITY_THRESHOLD:-${POLICY_METRIC_OPPORTUNITY_THRESHOLD:-0.65}}"
ELIGIBLE_HARM_THRESHOLD="${ORDINAL_EVIDENCE_ELIGIBLE_HARM_THRESHOLD:-${POLICY_METRIC_HARM_THRESHOLD:-0.30}}"
SAFE_HARD_NEGATIVE_WEIGHT="${ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_WEIGHT:-0.0}"
SAFE_HARD_NEGATIVE_MARGIN="${ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_MARGIN:-0.05}"
ADMISSION_PRIOR_MODE="${EVIDENCE_ADMISSION_PRIOR_MODE:-risk_centered}"
if [[ "$CONCORD_ENABLED" == true ]]; then
  TRAINABLE_PREFIXES='direct_evidence_concord_benefit_calibrator,direct_evidence_concord_harm_calibrator'
  if [[ "$ADMISSION_ENABLED" == true ]]; then
    TRAINABLE_PREFIXES+=',direct_evidence_concord_admission_calibrator'
  fi
else
  TRAINABLE_PREFIXES='direct_evidence_unified_calibrator'
  ADMISSION_ENABLED=false
fi
TRAINABLE_PREFIXES="${EVIDENCE_TRAINABLE_PREFIXES_OVERRIDE:-$TRAINABLE_PREFIXES}"

cat > "$RUN/STAGE_ARCHITECTURE.json" <<JSON
{
  "version": "v48.33-ELIGIBLE-SET-POLICY",
  "source_checkpoint": "$INIT_CKPT",
  "training_role": "unified_non_regime_specific_safe_set_admission",
  "frozen_policy": "v48.13_topk_recovery_proposal",
  "frozen_source_experts": true,
  "trainable": ["$TRAINABLE_PREFIXES"],
  "regime_id_exposed_to_evidence_model": false,
  "source_expert_use": "evaluate_both_for_every_candidate",
  "source_expert_envelope": "permutation_invariant_mean_minus_disagreement",
  "benefit_transfer": "consensus_transfer_plus_decoupled_residual",
  "harm_transfer": "decoupled_semantic_reset_absolute_component_logits",
  "concord_decoupled_heads": $CONCORD_ENABLED,
  "frontier_enabled": $FRONTIER_ENABLED,
  "raw_benefit_target": true,
  "safe_benefit_target": $SAFE_BENEFIT_TARGET,
  "admission_head": $ADMISSION_ENABLED,
  "admission_target": "continuous_safe_utility_with_component_veto",
  "group_opportunity_mil_weight": $GROUP_OPPORTUNITY_WEIGHT,
  "noisy_or_group_objective_disabled": true,
  "component_harm_heads": $COMPONENT_HEADS,
  "component_harm_components": ["drs", "deployability", "gap", "hard_rule", "harm_proxy"],
  "component_harm_count": $COMPONENT_COUNT,
  "component_reliability": "${EVIDENCE_COMPONENT_RELIABILITY:-}",
  "exact_deployment_eligibility_metric": true,
  "setwise_admission_weight": $SETWISE_WEIGHT,
  "component_tail_weight": $COMPONENT_TAIL_WEIGHT,
  "candidate_balance_is_auxiliary": true,
  "balanced_replaces_group_erm": false,
  "global_not_regime_balance": $GLOBAL_BALANCE,
  "context_source": "$CAL_CONTEXT_SOURCE",
  "proposal_top_k": $PROPOSAL_TOP_K,
  "frontier_runtime_wiring_verified": true,
  "admission_residual_bounded": ${EVIDENCE_ADMISSION_BOUNDED:-false},
  "admission_prior_detach": ${EVIDENCE_ADMISSION_PRIOR_DETACH:-true},
  "admission_prior_mode": "$ADMISSION_PRIOR_MODE",
  "slack_temperature": ${EVIDENCE_SLACK_TEMPERATURE:-0.025},
  "slack_penalty": ${EVIDENCE_SLACK_PENALTY:-1.0},
  "component_margin_regression_weight": ${ORDINAL_EVIDENCE_COMPONENT_MARGIN_REGRESSION_WEIGHT:-0.0},
  "group_batch_stratified": $STRATIFIED_BATCHES,
  "group_batching_replacement": ${GROUP_BATCHING_REPLACEMENT:-true},
  "checkpoint_all_abstain_barrier": true,
  "semantic_component_prior_logit": $COMPONENT_PRIOR_LOGIT,
  "categorical_nominal_topk_policy": $CATEGORICAL_GROUP_POLICY,
  "benefit_listwise_weight": $BENEFIT_LISTWISE_WEIGHT,
  "frontier_pairwise_weight": $FRONTIER_PAIRWISE_WEIGHT,
  "safe_utility_regression_weight": $SAFE_UTILITY_REGRESSION_WEIGHT,
  "safe_utility_listwise_weight": $SAFE_UTILITY_LISTWISE_WEIGHT,
  "safe_utility_temperature": $SAFE_UTILITY_TEMPERATURE,
  "eligible_set_policy_weight": $ELIGIBLE_POLICY_WEIGHT,
  "eligible_set_policy_temperature": $ELIGIBLE_POLICY_TEMPERATURE,
  "eligibility_logit_temperature": $ELIGIBILITY_LOGIT_TEMPERATURE,
  "eligible_opportunity_threshold": $ELIGIBLE_OPPORTUNITY_THRESHOLD,
  "eligible_harm_threshold": $ELIGIBLE_HARM_THRESHOLD,
  "selection_semantics": "rank_topk_then_filter_then_evidence_rerank",
  "safe_hard_negative_weight": $SAFE_HARD_NEGATIVE_WEIGHT,
  "safe_hard_negative_margin": $SAFE_HARD_NEGATIVE_MARGIN,
  "safe_hard_negative_teacher_scale": ${ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_TEACHER_SCALE:-0.0},
  "test_roots_read": false
}
JSON

DIRECT_VALUE_STRICT_SHAPE_CONTRACT="${DIRECT_VALUE_STRICT_SHAPE_CONTRACT:-true}" \
TRAIN_OCRAP_ROOT="${TRAIN_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
EVAL_OCRAP_ROOT="${EVAL_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
TRAIN_MIX="$TRAIN_MIX" VAL_MIX="$VAL_MIX" CAL_MIX="$VAL_MIX" \
RUN="$RUN" MODEL_DIR="$MODEL_DIR" CAL_DIR="$CAL_DIR" \
INIT_CKPT="$INIT_CKPT" VARIANT="$VARIANT" TRAIN_GPU="$TRAIN_GPU" GROUP_INDEX="$GROUP_INDEX" VAL_GROUP_INDEX="${VAL_GROUP_INDEX:-}" \
NUM_WORKERS="${NUM_WORKERS:-4}" PREFETCH_FACTOR="${PREFETCH_FACTOR:-2}" BATCH_SIZE="${BATCH_SIZE:-72}" \
EPOCHS="${EVIDENCE_ADAPT_EPOCHS:-24}" PATIENCE="${EVIDENCE_ADAPT_PATIENCE:-7}" \
LR="${EVIDENCE_ADAPT_LR:-0.00015}" ENCODER_LR_SCALE=0 ENCODER_ANCHOR_WEIGHT=0 \
TRAINABLE_PARAM_PREFIXES="$TRAINABLE_PREFIXES" \
STRICT_INIT_PREFIXES='direct_preference_set_ranker,direct_delta_adapters' \
BEST_METRIC="$BEST_METRIC_NAME" BEST_METRIC_MIN_DELTA="${BEST_METRIC_MIN_DELTA:-0.00001}" \
SKIP_POST_TRAIN_CALIBRATION=1 EXACT_TEACHER_PCD=true \
SET_CONTEXT_ENABLED=false PREFERENCE_HEAD_ENABLED=false PREFERENCE_CONTEXT_ENABLED=false RELATIVE_INCLUDE_ABSOLUTE=false \
SET_TOURNAMENT_ENABLED=true SET_TOURNAMENT_HIDDEN="${SET_TOURNAMENT_HIDDEN:-48}" SET_TOURNAMENT_HEADS="${SET_TOURNAMENT_HEADS:-4}" \
SET_TOURNAMENT_DROPOUT="${SET_TOURNAMENT_DROPOUT:-0.05}" SET_TOURNAMENT_REPLACE_BASE=true \
DELTA_HEAD_ENABLED=true DELTA_MODE=ordinal_evidence DELTA_HIDDEN="${EVIDENCE_HIDDEN:-48}" DELTA_DROPOUT="${EVIDENCE_DROPOUT:-0.02}" \
DELTA_REGIME_EXPERTS=true DELTA_POLICY_FEATURES=true \
EVIDENCE_CALIBRATOR_ENABLED=true EVIDENCE_CALIBRATOR_HIDDEN="$CAL_HIDDEN" EVIDENCE_CALIBRATOR_SCALE="$CAL_SCALE" \
EVIDENCE_CALIBRATOR_MODE=dual_tail_context EVIDENCE_CALIBRATOR_CONTEXT="$CAL_CONTEXT" EVIDENCE_CALIBRATOR_CONTEXT_DETACH=true \
EVIDENCE_CALIBRATOR_CONTEXT_SOURCE="$CAL_CONTEXT_SOURCE" EVIDENCE_CALIBRATOR_SHARED=false EVIDENCE_CALIBRATOR_REGIME_SCALE=0 \
EVIDENCE_UNIFIED_EXPERTS=true EVIDENCE_COMPONENT_HEADS="$COMPONENT_HEADS" EVIDENCE_COMPONENT_COUNT="$COMPONENT_COUNT" \
EVIDENCE_CONCORD="$CONCORD_ENABLED" EVIDENCE_ADMISSION_HEAD="$ADMISSION_ENABLED" \
EVIDENCE_ADMISSION_SCALE="${EVIDENCE_ADMISSION_SCALE:-1.0}" EVIDENCE_ADMISSION_BOUNDED="${EVIDENCE_ADMISSION_BOUNDED:-false}" \
EVIDENCE_ADMISSION_PRIOR_DETACH="${EVIDENCE_ADMISSION_PRIOR_DETACH:-true}" EVIDENCE_ADMISSION_PRIOR_MODE="$ADMISSION_PRIOR_MODE" \
EVIDENCE_SLACK_TEMPERATURE="${EVIDENCE_SLACK_TEMPERATURE:-0.025}" EVIDENCE_SLACK_PENALTY="${EVIDENCE_SLACK_PENALTY:-1.0}" EVIDENCE_CONSENSUS_DISAGREEMENT_PENALTY="$DISAGREEMENT_PENALTY" \
EVIDENCE_COMPONENT_SCALE="${EVIDENCE_COMPONENT_SCALE:-6.0}" \
EVIDENCE_FRONTIER="$FRONTIER_ENABLED" EVIDENCE_COMPONENT_PRIOR_LOGIT="$COMPONENT_PRIOR_LOGIT" \
ORDINAL_EVIDENCE_INDEPENDENT_TAILS=true ORDINAL_EVIDENCE_FACTORIZED_HARM=true \
ORDINAL_EVIDENCE_FACTORIZED_HARM_TEMPERATURE="${ORDINAL_EVIDENCE_FACTORIZED_HARM_TEMPERATURE:-0.025}" \
ORDINAL_EVIDENCE_COMPONENT_TAIL_WEIGHT="$COMPONENT_TAIL_WEIGHT" \
ORDINAL_EVIDENCE_COMPONENT_MARGIN_REGRESSION_WEIGHT="${ORDINAL_EVIDENCE_COMPONENT_MARGIN_REGRESSION_WEIGHT:-0.0}" \
ORDINAL_EVIDENCE_BATCH_BALANCED="$BATCH_BALANCED" ORDINAL_EVIDENCE_GLOBAL_BALANCE="$GLOBAL_BALANCE" \
ORDINAL_EVIDENCE_BALANCED_REPLACES_ERM=false \
ORDINAL_EVIDENCE_SAFE_SET_TEMPERATURE="${ORDINAL_EVIDENCE_SAFE_SET_TEMPERATURE:-0.08}" \
ORDINAL_EVIDENCE_SAFE_BENEFIT_TARGET="$SAFE_BENEFIT_TARGET" \
ORDINAL_EVIDENCE_GROUP_OPPORTUNITY_WEIGHT="$GROUP_OPPORTUNITY_WEIGHT" \
ORDINAL_EVIDENCE_CATEGORICAL_GROUP_POLICY="$CATEGORICAL_GROUP_POLICY" \
ORDINAL_EVIDENCE_BENEFIT_LISTWISE_WEIGHT="$BENEFIT_LISTWISE_WEIGHT" \
ORDINAL_EVIDENCE_BENEFIT_LISTWISE_TEMPERATURE="$BENEFIT_LISTWISE_TEMPERATURE" \
ORDINAL_EVIDENCE_SAFE_UTILITY_REGRESSION_WEIGHT="$SAFE_UTILITY_REGRESSION_WEIGHT" \
ORDINAL_EVIDENCE_SAFE_UTILITY_LISTWISE_WEIGHT="$SAFE_UTILITY_LISTWISE_WEIGHT" \
ORDINAL_EVIDENCE_SAFE_UTILITY_TEMPERATURE="$SAFE_UTILITY_TEMPERATURE" \
ORDINAL_EVIDENCE_ELIGIBLE_POLICY_WEIGHT="$ELIGIBLE_POLICY_WEIGHT" \
ORDINAL_EVIDENCE_ELIGIBLE_POLICY_TEMPERATURE="$ELIGIBLE_POLICY_TEMPERATURE" \
ORDINAL_EVIDENCE_ELIGIBILITY_LOGIT_TEMPERATURE="$ELIGIBILITY_LOGIT_TEMPERATURE" \
ORDINAL_EVIDENCE_ELIGIBLE_OPPORTUNITY_THRESHOLD="$ELIGIBLE_OPPORTUNITY_THRESHOLD" \
ORDINAL_EVIDENCE_ELIGIBLE_HARM_THRESHOLD="$ELIGIBLE_HARM_THRESHOLD" \
ORDINAL_EVIDENCE_FRONTIER_PAIRWISE_WEIGHT="$FRONTIER_PAIRWISE_WEIGHT" \
ORDINAL_EVIDENCE_FRONTIER_PAIRWISE_MARGIN="$FRONTIER_PAIRWISE_MARGIN" \
ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_WEIGHT="$SAFE_HARD_NEGATIVE_WEIGHT" \
ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_MARGIN="$SAFE_HARD_NEGATIVE_MARGIN" \
ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_TEACHER_SCALE="${ORDINAL_EVIDENCE_SAFE_HARD_NEGATIVE_TEACHER_SCALE:-0.0}" \
ORDINAL_EVIDENCE_ADMISSION_WEIGHT="${ORDINAL_EVIDENCE_ADMISSION_WEIGHT:-1.0}" \
ORDINAL_EVIDENCE_ADMISSION_POS_WEIGHT="${ORDINAL_EVIDENCE_ADMISSION_POS_WEIGHT:-6.0}" \
ORDINAL_EVIDENCE_ADMISSION_HARM_NEGATIVE_WEIGHT="${ORDINAL_EVIDENCE_ADMISSION_HARM_NEGATIVE_WEIGHT:-2.5}" \
EVALUATE_INITIAL_CHECKPOINT="${EVALUATE_INITIAL_CHECKPOINT:-true}" \
DETERMINISTIC_ALGORITHMS="${DETERMINISTIC_ALGORITHMS:-true}" CUDNN_BENCHMARK="${CUDNN_BENCHMARK:-false}" \
GROUP_BATCH_STRATIFIED="$STRATIFIED_BATCHES" GROUP_BATCHING_REPLACEMENT="${GROUP_BATCHING_REPLACEMENT:-true}" GROUP_BATCH_SAFE_POSITIVE_TARGET="${GROUP_BATCH_SAFE_POSITIVE_TARGET:-true}" GROUP_BATCH_POSITIVE_FRACTION="${GROUP_BATCH_POSITIVE_FRACTION:-0.50}" \
GROUP_BATCH_HARMFUL_FRACTION="${GROUP_BATCH_HARMFUL_FRACTION:-0.30}" GROUP_BATCH_DEAD_FRACTION="${GROUP_BATCH_DEAD_FRACTION:-0.20}" \
POSITIVE_GROUP_BOOST="${POSITIVE_GROUP_BOOST:-1.0}" POSITIVE_MACRO_BALANCE_POWER="${POSITIVE_MACRO_BALANCE_POWER:-0.25}" \
POINT_WEIGHT=0 VALUE_LISTWISE_WEIGHT=0 CENTERED_WEIGHT=0 ADVANTAGE_WEIGHT=0 SETWISE_W="$SETWISE_WEIGHT" \
OPPORTUNITY_ADMISSION_WEIGHT="${OPPORTUNITY_ADMISSION_WEIGHT:-1.0}" HARM_ADMISSION_WEIGHT="${HARM_ADMISSION_WEIGHT:-1.5}" \
SELECTIVE_RISK_WEIGHT="${SELECTIVE_RISK_WEIGHT:-0.75}" SELECTIVE_HARM_BUDGET="${SELECTIVE_HARM_BUDGET:-0.05}" \
SELECTIVE_COVERAGE_WEIGHT="${SELECTIVE_COVERAGE_WEIGHT:-0.25}" SELECTIVE_COVERAGE_TARGET="${SELECTIVE_COVERAGE_TARGET:-0.50}" \
POLICY_DISTILL_WEIGHT=0 POLICY_REGRET_WEIGHT=0 POLICY_ADMISSION_DISTILL_WEIGHT=0 \
PREFERENCE_WEIGHT=0 PREFERENCE_REGRET_WEIGHT=0 PREFERENCE_LISTWISE_WEIGHT=0 PREFERENCE_GAP_WEIGHT=0 \
PREFERENCE_SET_WEIGHT=0 PREFERENCE_ALL_GROUP_SET_WEIGHT=0 PREFERENCE_CONDITIONAL_SET_WEIGHT=0 PREFERENCE_PROPOSAL_TOPK_WEIGHT=0 \
DELTA_NLL_WEIGHT=0 DELTA_SIGN_WEIGHT=0 CERTIFICATE_POLICY_TOP1_WEIGHT=0 CERTIFICATE_POLICY_TOP1_SIGN_WEIGHT=0 \
ORDINAL_EVIDENCE_POLICY_TOP1_WEIGHT=0 ORDINAL_EVIDENCE_ALL_CANDIDATE_WEIGHT=0 \
ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT:-0.10}" \
ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT:-0.10}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT="${ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT:-0.35}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK="$PROPOSAL_TOP_K" ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY="${ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY:-0.85}" \
ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT="${ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT:-1.00}" \
ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT="${ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT:-2.00}" \
ORDINAL_EVIDENCE_CLASS_BALANCED_WEIGHT="${ORDINAL_EVIDENCE_CLASS_BALANCED_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_BENEFIT_MARGIN_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_MARGIN_WEIGHT:-0.25}" \
ORDINAL_EVIDENCE_HARM_MARGIN_WEIGHT="${ORDINAL_EVIDENCE_HARM_MARGIN_WEIGHT:-0.50}" \
ORDINAL_EVIDENCE_TARGET_PROBABILITY="${ORDINAL_EVIDENCE_TARGET_PROBABILITY:-0.65}" \
EVIDENCE_CALIBRATOR_ANCHOR_WEIGHT="${EVIDENCE_CALIBRATOR_ANCHOR_WEIGHT:-0.05}" \
ORDINAL_EVIDENCE_INTRAGROUP_BENEFIT_WEIGHT="${ORDINAL_EVIDENCE_INTRAGROUP_BENEFIT_WEIGHT:-0.10}" \
ORDINAL_EVIDENCE_INTRAGROUP_HARM_WEIGHT="${ORDINAL_EVIDENCE_INTRAGROUP_HARM_WEIGHT:-0.15}" \
ORDINAL_EVIDENCE_PAIRWISE_BENEFIT_WEIGHT=0 ORDINAL_EVIDENCE_PAIRWISE_HARM_WEIGHT=0 \
POLICY_METRIC_RISK_SOURCE=ordinal_evidence POLICY_METRIC_PROPOSAL_TOP_K="$PROPOSAL_TOP_K" POLICY_METRIC_EVIDENCE_RERANK_TOP_K=true \
POLICY_METRIC_EXACT_ELIGIBILITY=true POLICY_METRIC_MAX_HARD="${POLICY_METRIC_MAX_HARD:-1.0}" POLICY_METRIC_MIN_NOMINAL_DEVIATION="${POLICY_METRIC_MIN_NOMINAL_DEVIATION:-0.002}" \
POLICY_METRIC_SAFE_OPPORTUNITY=true POLICY_METRIC_SOFT_TEMPERATURE="${POLICY_METRIC_SOFT_TEMPERATURE:-0.10}" \
POLICY_METRIC_ELIGIBILITY_LOGIT_TEMPERATURE="${POLICY_METRIC_ELIGIBILITY_LOGIT_TEMPERATURE:-${ORDINAL_EVIDENCE_ELIGIBILITY_LOGIT_TEMPERATURE:-0.25}}" \
POLICY_METRIC_CATEGORICAL_GROUP_POLICY="$CATEGORICAL_GROUP_POLICY" \
POLICY_METRIC_CONCORD_MISS_WEIGHT="${POLICY_METRIC_CONCORD_MISS_WEIGHT:-2.0}" \
POLICY_METRIC_CONCORD_FALSE_WEIGHT="${POLICY_METRIC_CONCORD_FALSE_WEIGHT:-0.75}" \
POLICY_METRIC_CONCORD_HARM_WEIGHT="${POLICY_METRIC_CONCORD_HARM_WEIGHT:-2.0}" \
POLICY_METRIC_CONCORD_REGRET_WEIGHT="${POLICY_METRIC_CONCORD_REGRET_WEIGHT:-0.50}" \
POLICY_METRIC_CONCORD_SAFE_MASS_WEIGHT="${POLICY_METRIC_CONCORD_SAFE_MASS_WEIGHT:-1.0}" \
POLICY_METRIC_FRONTIER_HARM_WEIGHT="${POLICY_METRIC_FRONTIER_HARM_WEIGHT:-1.5}" POLICY_METRIC_FRONTIER_FALSE_WEIGHT="${POLICY_METRIC_FRONTIER_FALSE_WEIGHT:-0.5}" \
POLICY_METRIC_INTEGRITY_MIN_RECALL="${POLICY_METRIC_INTEGRITY_MIN_RECALL:-0.20}" POLICY_METRIC_INTEGRITY_RECALL_WEIGHT="${POLICY_METRIC_INTEGRITY_RECALL_WEIGHT:-20.0}" \
POLICY_METRIC_INTEGRITY_MIN_PRECISION="${POLICY_METRIC_INTEGRITY_MIN_PRECISION:-0.60}" POLICY_METRIC_INTEGRITY_PRECISION_WEIGHT="${POLICY_METRIC_INTEGRITY_PRECISION_WEIGHT:-8.0}" \
POLICY_METRIC_INTEGRITY_INVALID_WEIGHT="${POLICY_METRIC_INTEGRITY_INVALID_WEIGHT:-4.0}" POLICY_METRIC_INTEGRITY_SAFE_REGRET_WEIGHT="${POLICY_METRIC_INTEGRITY_SAFE_REGRET_WEIGHT:-2.0}" \
POLICY_METRIC_INTEGRITY_ALL_ABSTAIN_WEIGHT="${POLICY_METRIC_INTEGRITY_ALL_ABSTAIN_WEIGHT:-8.0}" \
POLICY_METRIC_CONTRACT_MIN_SAFE_TOP1_RECALL="${POLICY_METRIC_CONTRACT_MIN_SAFE_TOP1_RECALL:-0.20}" \
POLICY_METRIC_CONTRACT_ZERO_TOP1_WEIGHT="${POLICY_METRIC_CONTRACT_ZERO_TOP1_WEIGHT:-100.0}" \
POLICY_METRIC_CONTRACT_TOP1_SHORTFALL_WEIGHT="${POLICY_METRIC_CONTRACT_TOP1_SHORTFALL_WEIGHT:-20.0}" \
POLICY_METRIC_CONTRACT_ALL_ABSTAIN_WEIGHT="${POLICY_METRIC_CONTRACT_ALL_ABSTAIN_WEIGHT:-10.0}" \
POLICY_METRIC_MIN_FOLD_POSITIVE="${POLICY_METRIC_MIN_FOLD_POSITIVE:-6}" POLICY_METRIC_ROBUST_TOP_K="${POLICY_METRIC_ROBUST_TOP_K:-2}" \
POLICY_METRIC_HARM_WEIGHT="${POLICY_METRIC_HARM_WEIGHT:-0.50}" POLICY_METRIC_FALSE_WEIGHT="${POLICY_METRIC_FALSE_WEIGHT:-0.15}" \
POLICY_METRIC_MISS_WEIGHT="${POLICY_METRIC_MISS_WEIGHT:-1.25}" POLICY_METRIC_MIN_POSITIVE_RECALL="${POLICY_METRIC_MIN_POSITIVE_RECALL:-0.20}" \
POLICY_METRIC_RECALL_SHORTFALL_WEIGHT="${POLICY_METRIC_RECALL_SHORTFALL_WEIGHT:-4.0}" \
POLICY_METRIC_CROSS_MIN_RECALL="${POLICY_METRIC_CROSS_MIN_RECALL:-0.20}" POLICY_METRIC_CROSS_RECALL_WEIGHT="${POLICY_METRIC_CROSS_RECALL_WEIGHT:-2.0}" \
POLICY_METRIC_CROSS_HARM_WEIGHT="${POLICY_METRIC_CROSS_HARM_WEIGHT:-0.50}" POLICY_METRIC_CROSS_FALSE_WEIGHT="${POLICY_METRIC_CROSS_FALSE_WEIGHT:-0.20}" \
POLICY_METRIC_FACET_MIN_RECALL="${POLICY_METRIC_FACET_MIN_RECALL:-0.20}" POLICY_METRIC_FACET_HARM_BUDGET="${POLICY_METRIC_FACET_HARM_BUDGET:-0.05}" \
POLICY_METRIC_FACET_FALSE_BUDGET="${POLICY_METRIC_FACET_FALSE_BUDGET:-0.10}" POLICY_METRIC_FACET_BASE_WEIGHT="${POLICY_METRIC_FACET_BASE_WEIGHT:-0.10}" \
POLICY_METRIC_FACET_RECALL_WEIGHT="${POLICY_METRIC_FACET_RECALL_WEIGHT:-12.0}" POLICY_METRIC_FACET_HARM_EXCESS_WEIGHT="${POLICY_METRIC_FACET_HARM_EXCESS_WEIGHT:-10.0}" \
POLICY_METRIC_FACET_FALSE_EXCESS_WEIGHT="${POLICY_METRIC_FACET_FALSE_EXCESS_WEIGHT:-3.0}" \
COMPONENT_HARM_DRS_TOLERANCE="${COMPONENT_HARM_DRS_TOLERANCE:-0.05}" COMPONENT_HARM_DEP_TOLERANCE="${COMPONENT_HARM_DEP_TOLERANCE:-0.05}" \
COMPONENT_HARM_GAP_TOLERANCE="${COMPONENT_HARM_GAP_TOLERANCE:-0.05}" COMPONENT_HARM_HARD_TOLERANCE="${COMPONENT_HARM_HARD_TOLERANCE:-0.05}" \
COMPONENT_HARM_PROXY_TOLERANCE="${COMPONENT_HARM_PROXY_TOLERANCE:-0.05}" \
GROUP_DRO_WEIGHT=0 OPPORTUNITY_AUX_WEIGHT=0 HARM_W=0 EXPERT_SPECIALIZATION_WEIGHT=0 \
  bash scripts/train_ocrap_v48_trac_sr.sh

cat > "$RUN/POLICY_CONTRACT.env" <<EOF
RISK_SOURCE=ordinal_evidence
CONDITIONAL_RECOVERY_RANKING=true
POLICY_FIRST_NO_FALLBACK=false
PROPOSAL_TOP_K=$PROPOSAL_TOP_K
EVIDENCE_RERANK_TOP_K=true
MACRO_CONSTRAINT_MODE=opportunity_normalized
MAX_MACRO_EXCESS_SHARE=${MAX_MACRO_EXCESS_SHARE:-0.15}
HARM_LABEL_MODE=component_veto
OPPORTUNITY_LABEL_MODE=raw_benefit
GATE_POSITIVE_MODE=safe_benefit
ADMISSION_LABEL_MODE=continuous_safe_utility_with_component_veto
CALIBRATION_PROTOCOL=v48_33_dev_frozen_full_certificate_verification
SELECTION_SEMANTICS=rank_topk_then_filter_then_evidence_rerank
EOF

python - "$RUN" "$MODEL_DIR/best.pt" "$INIT_CKPT" "$MAX_CALIBRATOR_PARAMS" "$BEST_METRIC_NAME" "$COMPONENT_HEADS" "$SETWISE_WEIGHT" "$COMPONENT_TAIL_WEIGHT" <<'PY'
import hashlib,json,pathlib,sys,time,torch
run,ckpt,source=map(pathlib.Path,sys.argv[1:4])
max_params=int(sys.argv[4]); best_metric=sys.argv[5]
component_heads=sys.argv[6].lower()=='true'; setwise=float(sys.argv[7]); component_tail=float(sys.argv[8])
if not ckpt.is_file(): raise SystemExit(f'missing adapted checkpoint: {ckpt}')
try: doc=torch.load(ckpt,map_location='cpu',weights_only=False)
except TypeError: doc=torch.load(ckpt,map_location='cpu')
state=doc.get('model_state',{})
trainable=sum(v.numel() for k,v in state.items() if k.startswith(('direct_evidence_concord_benefit_calibrator.','direct_evidence_concord_harm_calibrator.','direct_evidence_concord_admission_calibrator.','direct_evidence_unified_calibrator.')))
legacy=[k for k in state if k.startswith(('direct_evidence_calibrators.','direct_evidence_shared_calibrator.'))]
if trainable <= 0 or trainable > max_params:
    raise SystemExit(f'unexpected FACTOR-PHYSICS-BRIDGE calibrator parameter count: {trainable}; allowed=(0,{max_params}]')
meta={
 'event':'v48_33_identity_utility_evidence_correction_complete','created_unix':time.time(),
 'checkpoint':str(ckpt),'checkpoint_sha256':hashlib.sha256(ckpt.read_bytes()).hexdigest(),
 'source_checkpoint':str(source),'source_checkpoint_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
 'frozen_policy':True,'frozen_source_experts':True,
 'regime_id_exposed_to_evidence_model':False,
 'trainable_prefixes':[x for x in ('direct_evidence_concord_benefit_calibrator','direct_evidence_concord_harm_calibrator','direct_evidence_concord_admission_calibrator') if any(k.startswith(x+'.') for k in state)] or ['direct_evidence_unified_calibrator'],'trainable_state_params':trainable,
 'legacy_evidence_keys_loaded_but_frozen':len(legacy),
 'source_expert_use':'both_experts_for_every_candidate',
 'benefit_transfer':'mean_consensus_minus_disagreement_plus_decoupled_residual','frontier_runtime_wiring_verified':True,'admission_residual_bounded':bool(doc.get('direct_recovery_evidence_admission_bounded',False)),
 'harm_transfer':'deadband_centered_component_residual_logits',
 'component_harm_heads':component_heads,'component_harm_count':int(doc.get('direct_recovery_evidence_component_count',3)),'admission_head':any(k.startswith('direct_evidence_concord_admission_calibrator.') for k in state),'setwise_admission_weight':setwise,
 'component_tail_weight':component_tail,'balanced_replaces_group_erm':False,
 'checkpoint_metric':best_metric,'categorical_group_policy':True,
 'benefit_listwise':float(doc.get('train_config',{}).get('ordinal_evidence_benefit_listwise_weight',0.0) or 0.0)>0,
 'safe_utility_regression':float(doc.get('train_config',{}).get('ordinal_evidence_safe_utility_regression_weight',0.0) or 0.0)>0,
 'safe_utility_listwise':float(doc.get('train_config',{}).get('ordinal_evidence_safe_utility_listwise_weight',0.0) or 0.0)>0,
 'frontier_contrast':float(doc.get('train_config',{}).get('ordinal_evidence_frontier_pairwise_weight',0.0) or 0.0)>0,'test_roots_read':False,
}
(run/'EVIDENCE_CORRECTION_COMPLETE.json').write_text(json.dumps(meta,indent=2)+'\n')
PY
