#!/usr/bin/env bash
set -euo pipefail

# v48.15 PRISM-CC: low-capacity, target-domain evidence correction.
# The source top-k proposal and source ordinal-evidence experts are frozen.
# Only a zero-initialized (<1k parameter) regime-specific residual calibrator
# is trained on the dedicated adaptation split.
REPO="${OCRAP_REPO:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO"
export PYTHONPATH="$REPO/src${PYTHONPATH:+:$PYTHONPATH}"

RUN="${RUN:?RUN is required}"
INIT_CKPT="${INIT_CKPT:?INIT_CKPT is required}"
VARIANT="${VARIANT:?VARIANT is required}"
TRAIN_MIX="${TRAIN_MIX:?TRAIN_MIX is required}"
VAL_MIX="${VAL_MIX:?VAL_MIX is required}"
GROUP_INDEX="${GROUP_INDEX:?GROUP_INDEX is required}"
TRAIN_GPU="${TRAIN_GPU:-0}"
MODEL_DIR="${MODEL_DIR:-$RUN/model_v48_trac_sr}"
CAL_DIR="${CAL_DIR:-$RUN/calibration}"
mkdir -p "$RUN/logs" "$MODEL_DIR" "$CAL_DIR"

PROPOSAL_TOP_K="${PROPOSAL_TOP_K:-3}"
SET_TOURNAMENT_HIDDEN="${SET_TOURNAMENT_HIDDEN:-48}"
SET_TOURNAMENT_HEADS="${SET_TOURNAMENT_HEADS:-4}"
CAL_HIDDEN="${EVIDENCE_CALIBRATOR_HIDDEN:-8}"
CAL_SCALE="${EVIDENCE_CALIBRATOR_SCALE:-0.30}"

cat > "$RUN/STAGE_ARCHITECTURE.json" <<JSON
{
  "version": "v48.15-PRISM-CC",
  "source_checkpoint": "$INIT_CKPT",
  "training_role": "low_capacity_scene_disjoint_evidence_correction",
  "frozen_policy": "v48.13_topk_recovery_proposal",
  "frozen_source_evidence": true,
  "trainable": ["direct_evidence_calibrators"],
  "calibrator_hidden": $CAL_HIDDEN,
  "calibrator_residual_scale": $CAL_SCALE,
  "proposal_top_k": $PROPOSAL_TOP_K,
  "risk_source": "ordinal_evidence",
  "test_roots_read": false
}
JSON

TRAIN_OCRAP_ROOT="${TRAIN_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
EVAL_OCRAP_ROOT="${EVAL_OCRAP_ROOT:-/data0/senzeyu2/dataset/OCRAP}" \
TRAIN_MIX="$TRAIN_MIX" VAL_MIX="$VAL_MIX" CAL_MIX="$VAL_MIX" \
RUN="$RUN" MODEL_DIR="$MODEL_DIR" CAL_DIR="$CAL_DIR" \
INIT_CKPT="$INIT_CKPT" VARIANT="$VARIANT" TRAIN_GPU="$TRAIN_GPU" GROUP_INDEX="$GROUP_INDEX" \
NUM_WORKERS="${NUM_WORKERS:-4}" PREFETCH_FACTOR="${PREFETCH_FACTOR:-2}" BATCH_SIZE="${BATCH_SIZE:-72}" \
EPOCHS="${EVIDENCE_ADAPT_EPOCHS:-10}" PATIENCE="${EVIDENCE_ADAPT_PATIENCE:-4}" \
LR="${EVIDENCE_ADAPT_LR:-0.00020}" ENCODER_LR_SCALE=0 ENCODER_ANCHOR_WEIGHT=0 \
TRAINABLE_PARAM_PREFIXES='direct_evidence_calibrators' \
STRICT_INIT_PREFIXES='direct_preference_set_ranker,direct_delta_adapters' \
BEST_METRIC=direct_certificate_risk_fold_robust BEST_METRIC_MIN_DELTA="${BEST_METRIC_MIN_DELTA:-0.00001}" \
SKIP_POST_TRAIN_CALIBRATION=1 EXACT_TEACHER_PCD=true \
SET_CONTEXT_ENABLED=false PREFERENCE_HEAD_ENABLED=false PREFERENCE_CONTEXT_ENABLED=false RELATIVE_INCLUDE_ABSOLUTE=false \
SET_TOURNAMENT_ENABLED=true SET_TOURNAMENT_HIDDEN="$SET_TOURNAMENT_HIDDEN" SET_TOURNAMENT_HEADS="$SET_TOURNAMENT_HEADS" \
SET_TOURNAMENT_DROPOUT="${SET_TOURNAMENT_DROPOUT:-0.05}" SET_TOURNAMENT_REPLACE_BASE=true \
DELTA_HEAD_ENABLED=true DELTA_MODE=ordinal_evidence DELTA_HIDDEN="${EVIDENCE_HIDDEN:-48}" DELTA_DROPOUT="${EVIDENCE_DROPOUT:-0.02}" \
DELTA_REGIME_EXPERTS=true DELTA_POLICY_FEATURES=true \
EVIDENCE_CALIBRATOR_ENABLED=true EVIDENCE_CALIBRATOR_HIDDEN="$CAL_HIDDEN" EVIDENCE_CALIBRATOR_SCALE="$CAL_SCALE" \
POINT_WEIGHT=0 VALUE_LISTWISE_WEIGHT=0 CENTERED_WEIGHT=0 ADVANTAGE_WEIGHT=0 SETWISE_W=0 \
PREFERENCE_WEIGHT=0 PREFERENCE_REGRET_WEIGHT=0 PREFERENCE_LISTWISE_WEIGHT=0 PREFERENCE_GAP_WEIGHT=0 \
PREFERENCE_SET_WEIGHT=0 PREFERENCE_ALL_GROUP_SET_WEIGHT=0 PREFERENCE_CONDITIONAL_SET_WEIGHT=0 PREFERENCE_PROPOSAL_TOPK_WEIGHT=0 \
DELTA_NLL_WEIGHT=0 DELTA_SIGN_WEIGHT=0 CERTIFICATE_POLICY_TOP1_WEIGHT=0 CERTIFICATE_POLICY_TOP1_SIGN_WEIGHT=0 \
ORDINAL_EVIDENCE_POLICY_TOP1_WEIGHT=0 ORDINAL_EVIDENCE_ALL_CANDIDATE_WEIGHT=0 \
ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_TOP1_WEIGHT:-0.20}" \
ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT="${ORDINAL_EVIDENCE_ORDERED_NLL_ALL_WEIGHT:-0.02}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT="${ORDINAL_EVIDENCE_PROPOSAL_TOPK_WEIGHT:-2.75}" \
ORDINAL_EVIDENCE_PROPOSAL_TOPK="$PROPOSAL_TOP_K" ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY="${ORDINAL_EVIDENCE_PROPOSAL_RANK_DECAY:-0.85}" \
ORDINAL_EVIDENCE_INTRAGROUP_BENEFIT_WEIGHT=0 ORDINAL_EVIDENCE_INTRAGROUP_HARM_WEIGHT=0 \
ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT="${ORDINAL_EVIDENCE_HARM_CLASS_WEIGHT:-2.50}" \
ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT="${ORDINAL_EVIDENCE_DEAD_CLASS_WEIGHT:-0.60}" \
ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT="${ORDINAL_EVIDENCE_BENEFIT_CLASS_WEIGHT:-2.00}" \
ORDINAL_EVIDENCE_HARD_HARM_WEIGHT="${ORDINAL_EVIDENCE_HARD_HARM_WEIGHT:-1.00}" \
ORDINAL_EVIDENCE_HARD_BENEFIT_WEIGHT="${ORDINAL_EVIDENCE_HARD_BENEFIT_WEIGHT:-1.00}" \
ORDINAL_EVIDENCE_HARD_EXAMPLE_GAMMA="${ORDINAL_EVIDENCE_HARD_EXAMPLE_GAMMA:-1.25}" \
ORDINAL_EVIDENCE_PAIRWISE_BENEFIT_WEIGHT=0 ORDINAL_EVIDENCE_PAIRWISE_HARM_WEIGHT=0 \
POLICY_METRIC_RISK_SOURCE=ordinal_evidence POLICY_METRIC_PROPOSAL_TOP_K="$PROPOSAL_TOP_K" POLICY_METRIC_EVIDENCE_RERANK_TOP_K=true \
POLICY_METRIC_MIN_FOLD_POSITIVE="${POLICY_METRIC_MIN_FOLD_POSITIVE:-6}" POLICY_METRIC_ROBUST_TOP_K="${POLICY_METRIC_ROBUST_TOP_K:-2}" \
POLICY_METRIC_HARM_WEIGHT="${POLICY_METRIC_HARM_WEIGHT:-0.35}" POLICY_METRIC_FALSE_WEIGHT="${POLICY_METRIC_FALSE_WEIGHT:-0.10}" \
POLICY_METRIC_MISS_WEIGHT="${POLICY_METRIC_MISS_WEIGHT:-0.55}" \
GROUP_DRO_WEIGHT=0 POLICY_DISTILL_WEIGHT=0 POLICY_REGRET_WEIGHT=0 POLICY_ADMISSION_DISTILL_WEIGHT=0 \
OPPORTUNITY_AUX_WEIGHT=0 HARM_W=0 SELECTIVE_RISK_WEIGHT=0 SELECTIVE_COVERAGE_WEIGHT=0 EXPERT_SPECIALIZATION_WEIGHT=0 \
  bash scripts/train_ocrap_v48_trac_sr.sh

cat > "$RUN/POLICY_CONTRACT.env" <<EOF2
RISK_SOURCE=ordinal_evidence
CONDITIONAL_RECOVERY_RANKING=true
POLICY_FIRST_NO_FALLBACK=false
PROPOSAL_TOP_K=$PROPOSAL_TOP_K
EVIDENCE_RERANK_TOP_K=true
MACRO_CONSTRAINT_MODE=opportunity_normalized
MAX_MACRO_EXCESS_SHARE=${MAX_MACRO_EXCESS_SHARE:-0.15}
CALIBRATION_PROTOCOL=v48_15_scene_disjoint_low_capacity_evidence_correction
EOF2

python - "$RUN" "$MODEL_DIR/best.pt" "$INIT_CKPT" <<'PY'
import hashlib,json,pathlib,sys,time,torch
run,ckpt,source=map(pathlib.Path,sys.argv[1:])
if not ckpt.is_file(): raise SystemExit(f'missing adapted checkpoint: {ckpt}')
try: doc_ck=torch.load(ckpt,map_location='cpu',weights_only=False)
except TypeError: doc_ck=torch.load(ckpt,map_location='cpu')
state=doc_ck.get('model_state',{})
trainable=sum(v.numel() for k,v in state.items() if k.startswith('direct_evidence_calibrators.'))
if trainable <= 0 or trainable > 2000:
    raise SystemExit(f'unexpected calibrator parameter count: {trainable}')
doc={
 'event':'v48_15_prism_cc_evidence_correction_complete','created_unix':time.time(),
 'checkpoint':str(ckpt),'checkpoint_sha256':hashlib.sha256(ckpt.read_bytes()).hexdigest(),
 'source_checkpoint':str(source),'source_checkpoint_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
 'frozen_policy':True,'frozen_source_evidence':True,
 'trainable_prefixes':['direct_evidence_calibrators'],'trainable_state_params':trainable,
 'test_roots_read':False,
}
(run/'EVIDENCE_CORRECTION_COMPLETE.json').write_text(json.dumps(doc,indent=2)+'\n')
PY
