#!/usr/bin/env bash
set -Eeuo pipefail
ARM="${1:?usage: $0 A|B|C|D}"
REPO="${OCRAP_REPO:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO"
BASE_OUT="${BASE_OUT:-runs}"
export OUTPUTDIR="${OUTPUTDIR:-$BASE_OUT/ocrap_v48_41_fcfr_ablation_${ARM}}"
export RESUME_AFTER_ADAPTATION=0
export V4841_ALLOW_EXACT_FACTOR_CACHE=0
unset V4836_FACTOR_CACHE_BALANCED V4836_FACTOR_CACHE_PRECISION || true

# Common v48.41 baseline: v48.40-B semantics, not the weaker v48.40-D main.
export EVIDENCE_UNBOUNDED_BENEFIT_FACTOR=false
export EVIDENCE_UNBOUNDED_HARM_FACTORS=false
export EVIDENCE_BENEFIT_RESIDUAL_SCALE=1.0
export EVIDENCE_COMPONENT_SCALE=6.0
export FACTOR_BENEFIT_MARGIN_REGRESSION_WEIGHT=1.00
export FACTOR_BENEFIT_MARGIN_TEMPERATURE=0.050
export FACTOR_COMPONENT_MARGIN_REGRESSION_WEIGHT=1.00
export FACTOR_COMPONENT_TAIL_WEIGHT=0.75
export FACTOR_COMPONENT_MARGIN_TARGET_MODE=raw
export FACTOR_COMPONENT_MARGIN_TARGET_SCALE=0.10
export EVIDENCE_DUAL_INTERACTION_BRIDGE=true
export EVIDENCE_FACTORIZED_HARM_INTERACTION=false
export EVIDENCE_RANK_BENEFIT_SKIP=false
export EVIDENCE_RANK_BENEFIT_GAIN_INIT=1.0
export EVIDENCE_RESERVE_FACTOR_ALIGNMENT=true
export EVIDENCE_ADMISSION_PRIOR_MODE=joint_reserve
export EVIDENCE_JOINT_RESERVE_TEMPERATURE=0.050
export V4838_RFR_RESERVE_ONLY=1
export V4837_FACTOR_PRESERVING_IDENTITY=0
export V4836_IDENTITY_TRAIN_ALL=0
export V4836_COUPLE_ADMISSION_PRIOR=0
export V4836_ADAPTIVE_IDENTITY_MARGIN=0
export V4836_ENABLE_FINAL_CALIBRATION=0
export FACTOR_COMPONENT_UNDERESTIMATION_WEIGHT=0
export FACTOR_SAFE_POSITIVE_COMPONENT_OVERESTIMATION_WEIGHT=0
export FACTOR_JOINT_RESERVE_REGRESSION_WEIGHT=0
export FACTOR_JOINT_RESERVE_BOUNDARY_WEIGHT=0
export PROPOSAL_TOP_K=5
export EVIDENCE_CALIBRATOR_CONTEXT_SOURCE=physical_interaction

case "$ARM" in
  A)
    export OCRAP_ALGORITHM_VERSION="v48.41-FCFR-ablation-A"
    export OCRAP_IMPLEMENTATION_VERSION="v48.41-FCFR-REFERENCE"
    export V4838_FACTOR_ALGORITHM_FAMILY="v48.41-A-dual-raw-reference"
    ;;
  B)
    export OCRAP_ALGORITHM_VERSION="v48.41-FCFR-ablation-B"
    export OCRAP_IMPLEMENTATION_VERSION="v48.41-FCFR-FACTORIZED-HARM"
    export V4838_FACTOR_ALGORITHM_FAMILY="v48.41-B-factorized-harm"
    export EVIDENCE_FACTORIZED_HARM_INTERACTION=true
    ;;
  C)
    export OCRAP_ALGORITHM_VERSION="v48.41-FCFR-ablation-C"
    export OCRAP_IMPLEMENTATION_VERSION="v48.41-FCFR-RANK-BENEFIT-SKIP"
    export V4838_FACTOR_ALGORITHM_FAMILY="v48.41-C-rank-benefit-skip"
    export EVIDENCE_RANK_BENEFIT_SKIP=true
    ;;
  D)
    export OCRAP_ALGORITHM_VERSION="v48.41-FCFR"
    export OCRAP_IMPLEMENTATION_VERSION="v48.41-FCFR-FACTORIZED-COMPONENT-FRONTIER"
    export V4838_FACTOR_ALGORITHM_FAMILY="v48.41-D-factorized-harm-rank-skip"
    export EVIDENCE_FACTORIZED_HARM_INTERACTION=true
    export EVIDENCE_RANK_BENEFIT_SKIP=true
    ;;
  *) echo "unknown arm: $ARM" >&2; exit 2 ;;
esac
exec bash scripts/run_v48_36_ocaf_dedicated.sh
