#!/usr/bin/env bash
set -Eeuo pipefail
ARM="${1:?usage: $0 A|B|C|D}"
REPO="${OCRAP_REPO:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO"
BASE_OUT="${BASE_OUT:-runs}"
if [[ "$ARM" == D ]]; then
  export OUTPUTDIR="${OUTPUTDIR:-$BASE_OUT/ocrap_v48_43_poet_main}"
else
  export OUTPUTDIR="${OUTPUTDIR:-$BASE_OUT/ocrap_v48_43_poet_ablation_${ARM}}"
fi
export RESUME_AFTER_ADAPTATION=0
unset V4836_FACTOR_CACHE_BALANCED V4836_FACTOR_CACHE_PRECISION || true

# v48.43 reference is the engineering-valid v48.42-A semantics.  The two
# v48.42 hypotheses were falsified by valid RC=20 experiments, so they are
# force-disabled in every arm.  All arms keep one continuous physics policy,
# one shared development rule, and no regime-conditioned routing/threshold.
export EVIDENCE_UNBOUNDED_BENEFIT_FACTOR=false
export EVIDENCE_UNBOUNDED_HARM_FACTORS=false
export EVIDENCE_BENEFIT_RESIDUAL_SCALE=1.0
export EVIDENCE_COMPONENT_SCALE=6.0
export FACTOR_BENEFIT_MARGIN_REGRESSION_WEIGHT=1.00
export FACTOR_BENEFIT_MARGIN_TEMPERATURE=0.050
export FACTOR_COMPONENT_MARGIN_REGRESSION_WEIGHT=1.00
export FACTOR_COMPONENT_TAIL_WEIGHT=0.75
export FACTOR_COMPONENT_MARGIN_TARGET_MODE=raw
export FACTOR_COMPONENT_MARGIN_TARGET_SCALE=0.10
export EVIDENCE_DUAL_INTERACTION_BRIDGE=true
export EVIDENCE_FACTORIZED_HARM_INTERACTION=false
export EVIDENCE_PARTIAL_POOL_HARM_RESIDUAL=false
export EVIDENCE_PARTIAL_POOL_HARM_RESIDUAL_SCALE=0.50
export EVIDENCE_RANK_BENEFIT_SKIP=false
export EVIDENCE_RANK_BENEFIT_GAIN_INIT=1.0
export EVIDENCE_POSTPREFIX_OBS_TRANSPORT_BENEFIT=false
export EVIDENCE_POSTPREFIX_OBS_TRANSPORT_HARM=false
export EVIDENCE_POSTPREFIX_OBS_TRANSPORT_SCALE="${EVIDENCE_POSTPREFIX_OBS_TRANSPORT_SCALE:-1.0}"
export EVIDENCE_RESERVE_FACTOR_ALIGNMENT=true
export EVIDENCE_ADMISSION_PRIOR_MODE=joint_reserve
export EVIDENCE_JOINT_RESERVE_TEMPERATURE=0.050
export V4838_RFR_RESERVE_ONLY=1
export V4837_FACTOR_PRESERVING_IDENTITY=0
export V4836_IDENTITY_TRAIN_ALL=0
export V4836_COUPLE_ADMISSION_PRIOR=0
export V4836_ADAPTIVE_IDENTITY_MARGIN=0
export V4836_ENABLE_FINAL_CALIBRATION=0
export FACTOR_COMPONENT_UNDERESTIMATION_WEIGHT=0
export FACTOR_SAFE_POSITIVE_COMPONENT_OVERESTIMATION_WEIGHT=0
export FACTOR_JOINT_RESERVE_REGRESSION_WEIGHT=0
export FACTOR_JOINT_RESERVE_BOUNDARY_WEIGHT=0
export PROPOSAL_TOP_K=5
export EVIDENCE_CALIBRATOR_CONTEXT_SOURCE=physical_interaction

case "$ARM" in
  A)
    export OCRAP_ALGORITHM_VERSION="v48.43-POET-ablation-A"
    export OCRAP_IMPLEMENTATION_VERSION="v48.43-POET-SHARED-DUAL-OCAF-REFERENCE"
    export V4838_FACTOR_ALGORITHM_FAMILY="v48.43-A-shared-dual-ocaf-reference"
    ;;
  B)
    export OCRAP_ALGORITHM_VERSION="v48.43-POET-ablation-B"
    export OCRAP_IMPLEMENTATION_VERSION="v48.43-POET-HARM-TRANSPORT"
    export V4838_FACTOR_ALGORITHM_FAMILY="v48.43-B-postprefix-obs-harm-transport"
    export EVIDENCE_POSTPREFIX_OBS_TRANSPORT_HARM=true
    ;;
  C)
    export OCRAP_ALGORITHM_VERSION="v48.43-POET-ablation-C"
    export OCRAP_IMPLEMENTATION_VERSION="v48.43-POET-BENEFIT-TRANSPORT"
    export V4838_FACTOR_ALGORITHM_FAMILY="v48.43-C-postprefix-obs-benefit-transport"
    export EVIDENCE_POSTPREFIX_OBS_TRANSPORT_BENEFIT=true
    ;;
  D)
    export OCRAP_ALGORITHM_VERSION="v48.43-POET"
    export OCRAP_IMPLEMENTATION_VERSION="v48.43-POET-DUAL-TRANSPORT"
    export V4838_FACTOR_ALGORITHM_FAMILY="v48.43-D-postprefix-obs-dual-transport"
    export EVIDENCE_POSTPREFIX_OBS_TRANSPORT_BENEFIT=true
    export EVIDENCE_POSTPREFIX_OBS_TRANSPORT_HARM=true
    ;;
  *) echo "unknown arm: $ARM" >&2; exit 2 ;;
esac
exec bash scripts/run_v48_36_ocaf_dedicated.sh
