#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
KINDS=('dev_near','dev_contact','certificate_near','certificate_contact'); VARIANTS=('balanced','precision')
def load(p):return json.loads(Path(p).read_text())
def cell(a,arm,v,k,key):return (((a.get('arms') or {}).get(arm) or {}).get(v) or {}).get(k,{}).get(key)
def delta(a,b):return None if a is None or b is None else float(a)-float(b)
def main():
 ap=argparse.ArgumentParser(description='v48.68 OC-RTRW projection-fidelity x robust-occupancy factorial attribution')
 ap.add_argument('--feasibility-audit',type=Path,required=True);ap.add_argument('--v67-complete',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);x=ap.parse_args()
 a=load(x.feasibility_audit);v67=load(x.v67_complete);deltas={};source=[];sel=[];safe=[];coverage=[];trust=[];tchecks=[];uchecks=[]
 for v in VARIANTS:
  deltas[v]={}
  for k in KINDS:
   vals={arm:cell(a,arm,v,k,'absolute_feasibility_auc') for arm in ('B_native','F_ERWF','P66_OCACRW','Q67_CTRLPROJ','T_FIDELITY','U_OCCUPANCY','V_Main_OCRTRW')}
   tq=delta(vals['T_FIDELITY'],vals['Q67_CTRLPROJ']); uq=delta(vals['U_OCCUPANCY'],vals['Q67_CTRLPROJ']); vq=delta(vals['V_Main_OCRTRW'],vals['Q67_CTRLPROJ']); vb=delta(vals['V_Main_OCRTRW'],vals['B_native']); inter=None if None in(tq,uq,vq) else vq-tq-uq
   deltas[v][k]={'V_minus_B_auc':vb,'T_minus_Q67_fidelity_main_effect':tq,'U_minus_Q67_occupancy_main_effect':uq,'V_minus_Q67_total_effect':vq,'V_minus_U_fidelity_conditional_effect':delta(vals['V_Main_OCRTRW'],vals['U_OCCUPANCY']),'V_minus_T_occupancy_conditional_effect':delta(vals['V_Main_OCRTRW'],vals['T_FIDELITY']),'fidelity_x_occupancy_interaction':inter}
   source.append(vb is not None and vb>0)
   ph=cell(a,'V_Main_OCRTRW',v,k,'harmful_pass_fraction'); pti=cell(a,'V_Main_OCRTRW',v,k,'teacher_infeasible_pass_fraction'); fh=cell(a,'F_ERWF',v,k,'harmful_pass_fraction'); fti=cell(a,'F_ERWF',v,k,'teacher_infeasible_pass_fraction'); caph=min(.25,float(fh)-.10); capt=min(.25,float(fti)-.10); sel.append({'variant':v,'split':k,'harmful':ph,'teacher_infeasible':pti,'valid':float(ph)<=caph and float(pti)<=capt})
   vp=cell(a,'V_Main_OCRTRW',v,k,'safe_positive_pass_fraction'); pp=cell(a,'P66_OCACRW',v,k,'safe_positive_pass_fraction'); safe.append({'variant':v,'split':k,'V_minus_P66':delta(vp,pp),'valid':vp is not None and pp is not None and float(vp)>float(pp)})
   vc=cell(a,'V_Main_OCRTRW',v,k,'safe_positive_positive_certificate_fraction'); pc=cell(a,'P66_OCACRW',v,k,'safe_positive_positive_certificate_fraction'); qc=cell(a,'Q67_CTRLPROJ',v,k,'safe_positive_positive_certificate_fraction'); coverage.append({'variant':v,'split':k,'V_minus_P66':delta(vc,pc),'V_minus_Q67':delta(vc,qc),'valid':vc is not None and pc is not None and float(vc)>float(pc)})
   vt=cell(a,'V_Main_OCRTRW',v,k,'positive_certificate_teacher_feasible_precision'); pt=cell(a,'P66_OCACRW',v,k,'positive_certificate_teacher_feasible_precision'); trust.append({'variant':v,'split':k,'V_minus_P66':delta(vt,pt),'V':vt,'P66':pt,'valid':vt is not None and pt is not None and float(vt)>=float(pt)-.03})
   tc=cell(a,'T_FIDELITY',v,k,'safe_positive_positive_certificate_rows'); qcr=cell(a,'Q67_CTRLPROJ',v,k,'safe_positive_positive_certificate_rows'); ta=cell(a,'T_FIDELITY',v,k,'absolute_feasibility_auc'); qa=cell(a,'Q67_CTRLPROJ',v,k,'absolute_feasibility_auc'); th=cell(a,'T_FIDELITY',v,k,'harmful_pass_fraction'); qh=cell(a,'Q67_CTRLPROJ',v,k,'harmful_pass_fraction'); tt=cell(a,'T_FIDELITY',v,k,'teacher_infeasible_pass_fraction'); qt=cell(a,'Q67_CTRLPROJ',v,k,'teacher_infeasible_pass_fraction'); tchecks.append({'variant':v,'split':k,'certificate_rows_equal':tc==qcr,'T_minus_Q67_auc':delta(ta,qa),'harmful_nonincrease':float(th)<=float(qh)+1e-12,'TI_nonincrease':float(tt)<=float(qt)+1e-12,'valid':tc==qcr})
   up=cell(a,'U_OCCUPANCY',v,k,'positive_certificate_teacher_feasible_precision'); uc=cell(a,'U_OCCUPANCY',v,k,'safe_positive_positive_certificate_fraction'); uchecks.append({'variant':v,'split':k,'precision_gain':delta(up,cell(a,'Q67_CTRLPROJ',v,k,'positive_certificate_teacher_feasible_precision')),'coverage_delta':delta(uc,qc),'U_precision':up,'Q_precision':cell(a,'Q67_CTRLPROJ',v,k,'positive_certificate_teacher_feasible_precision'),'valid':up is not None and cell(a,'Q67_CTRLPROJ',v,k,'positive_certificate_teacher_feasible_precision') is not None and float(up)>float(cell(a,'Q67_CTRLPROJ',v,k,'positive_certificate_teacher_feasible_precision')) and delta(uc,qc)>=-.05})
 source_go=all(source) and sum((deltas[v][k]['V_minus_B_auc'] or -9)>=.01 for v in VARIANTS for k in KINDS)>=6
 sel_go=all(z['valid'] for z in sel)
 safe_go=all(z['valid'] for z in safe) and sum((z['V_minus_P66'] or -9)>=.05 for z in safe)>=6
 cov_go=all(z['valid'] for z in coverage) and sum((z['V_minus_P66'] or -9)>=.05 for z in coverage)>=6
 trust_go=all(z['valid'] for z in trust)
 t_go=all(z['certificate_rows_equal'] for z in tchecks) and sum((z['T_minus_Q67_auc'] or -9)>0 for z in tchecks)>=6 and sum(z['harmful_nonincrease'] and z['TI_nonincrease'] for z in tchecks)>=6
 u_go=all(z['valid'] for z in uchecks) and sum((z['precision_gain'] or -9)>=.05 for z in uchecks)>=6
 prereq=bool(v67.get('valid')) and bool(v67.get('attribution_ready')) and v67.get('engineering_version')=='v48.67.1-OC-PBRW-ENGFIX' and not v67.get('test_roots_read')
 go=bool(prereq and source_go and sel_go and safe_go and cov_go and trust_go and t_go and u_go)
 doc={'schema':'ocrap-v48.68-rtrw-comparison-v1','source_deltas':deltas,'preregistered_decision':{'status':'GO' if go else 'STOP','v48_67_prerequisite_attribution_ready':prereq,'source_gate':source_go,'selectivity_gate':sel_go,'safe_positive_admission_gate':safe_go,'safe_positive_witness_coverage_gate':cov_go,'trust_nonregression_gate':trust_go,'projection_fidelity_mechanism_gate':t_go,'robust_occupancy_mechanism_gate':u_go,'selectivity_checks':sel,'safe_positive_checks':safe,'coverage_checks':coverage,'trust_checks':trust,'projection_fidelity_checks':tchecks,'robust_occupancy_checks':uchecks},'attribution_order':['V-B is the primary absolute-source gate','T-Q67 isolates sign-preserving projection-fidelity trust','U-Q67 isolates observation-only robust occupancy','V-U and V-T are conditional main effects; V-Q67-(T-Q67)-(U-Q67) is the interaction','witness trust must recover without sacrificing safe-positive witness recall','boundary transport remains OFF and deployment/Safe are interpreted only after source GO'],'scientific_contract':{'primary_hypothesis':'v48.67 proved actuator projection can realize witnesses but erases informative projection severity and makes CV-only clearance the dominant optimistic failure mode; v48.68 preserves projection effort as soft trust and replaces point CV with a deployable CV/current-acceleration occupancy envelope.','frozen':['v48.56-A Stage-I tensors','v48.67 actuator projection ON','v48.66 route+reentry constraints ON','v48.64 active-set alignment ON','boundary transport OFF','class-local/path-stop OFF','OC-MERO/RIFA/top-K=5/threshold=0.5','relative filter/ranker','option library','teacher labels/datasets'],'interventions':['T: soft projection-fidelity weighting only','U: robust CV/current-acceleration occupancy only','V: both factors'],'forbidden':['threshold/LR/horizon/feature/class-weight grids','proposal expansion/top-K search','generic AFE/MLP','candidate-only CPHR','compensatory ERWF','per-option negative veto','quantifier gain sweep','regime router/policy/threshold/budget','broad root/margin/encoder retraining','privileged teacher future/component-margin distillation','relative ranker changes before source GO','option-library expansion without teacher-option-support evidence','class-local correction as Main','path-stop as Main','v48.67 boundary transport before trust GO','unconditional projected-control confidence that discards projection severity']},'feasibility_role_audit':a}
 x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(json.dumps(doc,indent=2,sort_keys=True)+'\n');print(json.dumps({'event':'v48_68_rtrw_comparison','decision':doc['preregistered_decision']['status'],'output':str(x.output)}))
if __name__=='__main__':main()
