#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
KINDS=('dev_near','dev_contact','certificate_near','certificate_contact');VARIANTS=('balanced','precision')
def load(p):return json.loads(Path(p).read_text())
def cell(a,arm,v,k,key):return (((a.get('arms') or {}).get(arm) or {}).get(v) or {}).get(k,{}).get(key)
def delta(a,b):return None if a is None or b is None else float(a)-float(b)
def main():
 ap=argparse.ArgumentParser(description='v48.67 OC-PBRW control-projection x boundary-transport factorial attribution')
 for n in ('b','f','p66','q','r','s'):ap.add_argument('--'+n,type=Path,required=True)
 ap.add_argument('--feasibility-audit',type=Path,required=True);ap.add_argument('--boundary-audit',type=Path,required=True);ap.add_argument('--v66-complete',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);x=ap.parse_args()
 a=load(x.feasibility_audit);debt=load(x.boundary_audit);v66=load(x.v66_complete);deltas={};source=[];sel=[];safe=[];coverage=[];trust=[];false=[];qcov=[];rtransport=[]
 for v in VARIANTS:
  deltas[v]={}
  for k in KINDS:
   vals={arm:cell(a,arm,v,k,'absolute_feasibility_auc') for arm in ('B_native','P66_OCACRW','Q_CTRLPROJ','R_BOUNDARY','S_Main_OCPBRW')}
   q=delta(vals['Q_CTRLPROJ'],vals['P66_OCACRW']);r=delta(vals['R_BOUNDARY'],vals['P66_OCACRW']);s=delta(vals['S_Main_OCPBRW'],vals['P66_OCACRW']);sb=delta(vals['S_Main_OCPBRW'],vals['B_native']);inter=None if None in(q,r,s) else s-q-r
   deltas[v][k]={'S_minus_B_auc':sb,'S_minus_P66_total_effect':s,'Q_minus_P66_control_projection_main_effect':q,'R_minus_P66_boundary_transport_main_effect':r,'S_minus_R_control_projection_conditional_effect':delta(vals['S_Main_OCPBRW'],vals['R_BOUNDARY']),'S_minus_Q_boundary_transport_conditional_effect':delta(vals['S_Main_OCPBRW'],vals['Q_CTRLPROJ']),'projection_x_boundary_interaction':inter}
   source.append(sb is not None and sb>0)
   ph=cell(a,'S_Main_OCPBRW',v,k,'harmful_pass_fraction');pti=cell(a,'S_Main_OCPBRW',v,k,'teacher_infeasible_pass_fraction');fh=cell(a,'F_ERWF',v,k,'harmful_pass_fraction');fti=cell(a,'F_ERWF',v,k,'teacher_infeasible_pass_fraction');cap_h=min(.25,float(fh)-.10);cap_t=min(.25,float(fti)-.10);sel.append({'variant':v,'split':k,'harmful':ph,'teacher_infeasible':pti,'valid':float(ph)<=cap_h and float(pti)<=cap_t})
   sp=cell(a,'S_Main_OCPBRW',v,k,'safe_positive_pass_fraction');bp=cell(a,'P66_OCACRW',v,k,'safe_positive_pass_fraction');sg=delta(sp,bp);safe.append({'variant':v,'split':k,'S_minus_P66':sg,'S':sp,'P66':bp,'valid':sg is not None and sg>0})
   sc=cell(a,'S_Main_OCPBRW',v,k,'safe_positive_positive_certificate_fraction');bc=cell(a,'P66_OCACRW',v,k,'safe_positive_positive_certificate_fraction');cg=delta(sc,bc);coverage.append({'variant':v,'split':k,'S_minus_P66':cg,'S':sc,'P66':bc,'valid':cg is not None and cg>0})
   st=cell(a,'S_Main_OCPBRW',v,k,'positive_certificate_teacher_feasible_precision');bt=cell(a,'P66_OCACRW',v,k,'positive_certificate_teacher_feasible_precision');trust.append({'variant':v,'split':k,'S_minus_P66':delta(st,bt),'S':st,'P66':bt,'valid':st is not None and bt is not None and float(st)>=float(bt)-.03})
   sf=cell(a,'S_Main_OCPBRW',v,k,'positive_certificate_teacher_infeasible_fraction');bf=cell(a,'P66_OCACRW',v,k,'positive_certificate_teacher_infeasible_fraction');false.append({'variant':v,'split':k,'S_minus_P66':delta(sf,bf),'S':sf,'P66':bf,'valid':sf is not None and bf is not None and float(sf)<=float(bf)+.03})
   qc=cell(a,'Q_CTRLPROJ',v,k,'safe_positive_positive_certificate_fraction');qg=delta(qc,bc);qcov.append({'variant':v,'split':k,'Q_minus_P66_safe_positive_certificate_coverage':qg,'valid':qg is not None and qg>0})
   spcond=cell(a,'S_Main_OCPBRW',v,k,'safe_positive_pass_given_positive_certificate');qpcond=cell(a,'Q_CTRLPROJ',v,k,'safe_positive_pass_given_positive_certificate');rg=delta(spcond,qpcond);qcert=cell(a,'Q_CTRLPROJ',v,k,'safe_positive_positive_certificate_rows');scert=cell(a,'S_Main_OCPBRW',v,k,'safe_positive_positive_certificate_rows');rtransport.append({'variant':v,'split':k,'S_minus_Q_pass_given_positive_certificate':rg,'S':spcond,'Q':qpcond,'Q_positive_certificate_rows':qcert,'S_positive_certificate_rows':scert,'certificate_set_size_equal':qcert==scert,'valid':rg is not None and rg>0 and qcert is not None and float(qcert)>0 and qcert==scert})
 source_go=all(source) and sum((deltas[v][k]['S_minus_B_auc'] or -9)>=.01 for v in VARIANTS for k in KINDS)>=6
 sel_go=all(z['valid'] for z in sel)
 safe_go=all(z['valid'] for z in safe) and sum((z['S_minus_P66'] or -9)>=.15 for z in safe)>=6
 cov_go=all(z['valid'] for z in coverage) and sum((z['S_minus_P66'] or -9)>=.15 for z in coverage)>=6
 trust_go=all(z['valid'] for z in trust) and all(z['valid'] for z in false)
 q_go=all(z['valid'] for z in qcov) and sum((z['Q_minus_P66_safe_positive_certificate_coverage'] or -9)>=.15 for z in qcov)>=6
 r_go=all(z['valid'] for z in rtransport) and sum((z['S_minus_Q_pass_given_positive_certificate'] or -9)>=.20 for z in rtransport)>=6
 prereq=bool(v66.get('valid')) and bool(v66.get('attribution_ready')) and v66.get('engineering_version')=='v48.66.0-OC-ACRW' and not v66.get('test_roots_read')
 go=bool(prereq and source_go and sel_go and safe_go and cov_go and trust_go and q_go and r_go)
 doc={'schema':'ocrap-v48.67-ocpbrw-comparison-v1','source_deltas':deltas,'preregistered_decision':{'status':'GO' if go else 'STOP','v48_66_prerequisite_attribution_ready':prereq,'source_gate':source_go,'selectivity_gate':sel_go,'safe_positive_admission_gate':safe_go,'safe_positive_witness_coverage_gate':cov_go,'trust_nonregression_gate':trust_go,'control_projection_mechanism_gate':q_go,'boundary_transport_mechanism_gate':r_go,'selectivity_checks':sel,'safe_positive_checks':safe,'coverage_checks':coverage,'trust_checks':trust,'false_certificate_checks':false,'control_projection_checks':qcov,'boundary_transport_checks':rtransport},
 'attribution_order':['S-B is the primary absolute-source gate','Q-P66 isolates actuator-feasible recovery realization','R-P66 is the pure boundary main-effect control where historical positive certificates exist','S-Q is the preregistered boundary-transport effect after Q creates actuator-feasible witnesses; S-R and the factorial interaction remain diagnostic','witness trust must not materially regress from v48.66 P while positive witness recall is restored','deployment and Safe nominal utility are interpreted only after source GO'],
 'scientific_contract':{'primary_hypothesis':'v48.66 validated active-constraint trust but exposed two remaining layers: desired-command recovery traces violate controllable rate/jerk constraints, and the arbitrary additive witness lift is not aligned with each native root-option deficit to R_dep=0. v48.67 enforces observable actuator constraints by construction and transports only trusted positive certificates through a bounded one-sided interpolation toward their normalized signed reserve.','frozen':['v48.56-A Stage-I tensors','v48.66 route+reentry trust constraints ON','v48.64 active-set alignment ON','legacy stopping; path-stop OFF','candidate-global common support; class-local OFF','OC-MERO/RIFA/top-K=5/threshold=0.5','relative filter/ranker','option library','teacher labels/datasets'],'interventions':['Q: projected actuator-feasible deterministic recovery; historical additive transport','R: historical unprojected recovery; bounded boundary transport','S: both factors'],'GO_requires':['S-B AUC >0 in 8/8 and >=+0.01 in >=6/8','harmful/TI pass <=0.25 and >=0.10 below F in every cell','safe-positive pass > P66 in 8/8 and +0.15 in >=6/8','safe-positive positive-certificate coverage > P66 in 8/8 and +0.15 in >=6/8','positive-certificate precision and false-certificate fraction do not regress >0.03 vs P66','Q independently restores positive-certificate coverage in 8/8, +0.15 in >=6/8','S-Q increases safe-positive pass conditional on the identical Q/S positive-certificate set in 8/8, +0.20 in >=6/8; Q must create at least one safe-positive certificate in every cell'],'forbidden':['threshold/LR/horizon/feature-weight/class-weight grids','proposal expansion/top-K search','generic AFE/MLP','candidate-only CPHR','compensatory ERWF','per-option negative veto','quantifier gain sweep','regime router/policy/threshold/budget','broad root/margin/encoder retraining','privileged future/component-margin distillation','relative-ranker changes before source GO','option-library expansion without teacher-option-support evidence','class-local correction as Main','path-stop as Main','hard native-q/margin replacement or OR/AND transport','teacher-only physical-sign replacement']},'feasibility_role_audit':a,'boundary_debt_audit':debt}
 x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(json.dumps(doc,indent=2,sort_keys=True)+'\n');print(json.dumps({'event':'v48_67_ocpbrw_comparison','decision':doc['preregistered_decision']['status'],'output':str(x.output)}))
if __name__=='__main__':main()
