#!/usr/bin/env python3
"""Render synchronized reviewer-facing OC-RAP comparison videos.

The paper-facing default is deliberately conservative: every selected target is
rerun for OC-RAP and *all* paper-table external baselines, but the primary video
compares OC-RAP only against the per-scene strongest/hardest external baseline.
A compact side panel discloses the full paper-table baseline ranking and full-run metric
values, so the qualitative pair cannot hide weaker/stronger alternatives.

Optional flags can additionally render single-method, global-strongest, or worst
comparators for debugging/supplementary material.  Worst-baseline comparisons
are intentionally not generated by default because they are weak evidence for a
submission figure.

All videos for a scene use the same clip duration, simulation-time samples and
scene-wide fixed world-frame camera by default.  If a rollout terminates before
the selected clip duration, the final state is held and explicitly labeled.
"""
from __future__ import annotations

import argparse
import json
import math
import os
import re
import shutil
import subprocess
import textwrap
import time
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import animation, patches, transforms
from matplotlib.collections import LineCollection

try:
    from ocrap.external_baselines.provenance import find_provenance
except Exception:  # pragma: no cover - renderer still works outside installed package
    find_provenance = None


def _parse_trace_specs(specs: list[str]) -> dict[str, Path]:
    out: dict[str, Path] = {}
    for spec in specs:
        if "=" not in spec:
            raise SystemExit(f"invalid --trace {spec!r}; expected METHOD=SCENES.jsonl")
        name, raw = spec.split("=", 1)
        name = name.strip()
        if not name or name in out:
            raise SystemExit(f"duplicate/empty method in --trace {spec!r}")
        out[name] = Path(raw)
    if "ocrap" not in out:
        raise SystemExit("--trace must include ocrap=...")
    if len(out) < 2:
        raise SystemExit("at least one external baseline trace is required")
    return out


def _load_scenes(path: Path):
    if path.suffix == ".json" and not path.name.endswith(".scenes.jsonl"):
        alt = Path(str(path) + ".scenes.jsonl")
        if alt.is_file():
            path = alt
    direct: dict[str, dict[str, Any]] = {}
    by_scene_time: dict[tuple[str, str], dict[str, Any]] = {}
    by_scene: dict[str, list[dict[str, Any]]] = {}
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            envelope = json.loads(line)
            scene = envelope.get("scene", envelope)
            key = str(scene.get("target_key") or envelope.get("resume_key") or "")
            if key.startswith("target:"):
                key = key[len("target:"):]
            scene_id = str(scene.get("scene_id") or "")
            raw_time = scene.get("target_time_index")
            time_index = str(raw_time if raw_time is not None else "")
            if not key:
                key = f"{scene_id}:t{time_index}" if scene_id and time_index else scene_id
            if not key:
                raise ValueError(f"scene without target key in {path}")
            if key in direct:
                raise ValueError(f"duplicate target key {key} in {path}")
            direct[key] = scene
            if scene_id:
                by_scene.setdefault(scene_id, []).append(scene)
                if time_index:
                    by_scene_time[(scene_id, time_index)] = scene
    if not direct:
        raise ValueError(f"empty scene journal: {path}")
    return direct, by_scene_time, by_scene


def _resolve_scene(item, loaded):
    direct, by_scene_time, by_scene = loaded
    key = str(item["target_key"])
    if key in direct:
        return direct[key], "target_key"
    scene_id = str(item.get("scene_id") or "")
    time_index = str(item.get("target_time_index") if item.get("target_time_index") is not None else "")
    if scene_id and time_index and (scene_id, time_index) in by_scene_time:
        return by_scene_time[(scene_id, time_index)], "scene_id_and_time"
    if scene_id and len(by_scene.get(scene_id, [])) == 1:
        return by_scene[scene_id][0], "unique_scene_id"
    return None, "unresolved"


def _safe_name(text: str) -> str:
    value = re.sub(r"[^A-Za-z0-9._-]+", "_", text.strip())
    return value.strip("._-") or "model"


# Compact paper-facing labels.  The provenance registry keeps the full method
# names for tables/audits; videos deliberately use short labels so the world
# view and metric panel stay readable at 16:9.
PAPER_DISPLAY_NAMES: dict[str, str] = {
    "ocrap": "OC-RAP",
    # Safe: names used by the cited papers / public implementations.
    "gameformer_lite": "GameFormer",
    "plantf": "PlanTF",
    "pluto": "PLUTO",
    "pdm_closed": "PDM-Closed",
    "pdm_hybrid": "PDM-Hybrid",
    "idm": "IDM",
    "diffusion_planner": "Diffusion Planner",
    # Near-contact: never expose repository suffixes such as *_lite.
    "marc_lite": "MARC",
    "racp_lite": "RACP",
    "robust_scenario_mpc": "Scenario MPC",
    "predictive_safety_filter": "PSF",
    "dr_cvar_safety_filter": "DR-CVaR",
    "conformal_predictive_safety_filter": "CPSF",
    "flow_planner": "Flow Planner",
    "plan_r1": "Plan-R1",
    "betopnet": "BeTopNet",
    # Contact: use acronyms/components actually introduced in the source papers.
    # Ghosh et al. do not define a named acronym for the full restoration law, so
    # do not invent one; use the paper-native short descriptor instead.
    "postimpact_mpc_lite": "MPC + PSO",
    "post_crash_braking": "PIB",
    "postimpact_motion_tvlqr": "APF + TVLQR",
    "post_collision_restoration": "Trajectory restoration",
    "compensatory_postimpact_mpc": "FCC-MPC",
    "robust_postimpact_control": "SMC + QP",
}


def _display_name(method: str) -> str:
    key = str(method).strip().lower()
    if key in PAPER_DISPLAY_NAMES:
        return PAPER_DISPLAY_NAMES[key]
    if find_provenance is not None:
        item = find_provenance(method)
        if item is not None:
            return str(item.reporting_name or item.canonical_name)
    return method


def _short_comparator_role(text: str, regime: str) -> str:
    low = str(text or "").lower()
    if regime == "safe" or "highest per-scene" in low:
        return "Strongest Safe external"
    if "fail the trace-level" in low or "recovery gate" in low:
        return "Hardest trace-failing external"
    if "trace-severe" in low:
        return "Hardest trace-severe external"
    if "lowest paired" in low or "hardest" in low:
        return "Hardest paired external"
    if "regime-level strongest" in low or "global" in low:
        return "Global strongest external"
    if "weakest" in low or "worst" in low:
        return "Weakest external (supp.)"
    return "External comparator"


PANEL_METRICS: dict[str, tuple[tuple[str, str, str, str, int], ...]] = {
    "safe": (
        ("nup", "NUP", "", "higher", 3),
        ("intervention_rate", "Intervention", "", "lower", 3),
        ("clearance_p05_m", "Clearance p05", " m", "higher", 2),
        ("ttc_p05_s", "TTC p05", " s", "higher", 2),
        ("overlap_any", "Overlap", "", "lower", 0),
        ("offroad_any", "Off-road", "", "lower", 0),
    ),
    "near": (
        ("ttc_p05_s", "TTC p05", " s", "higher", 2),
        ("clearance_p05_m", "Clearance p05", " m", "higher", 2),
        ("critical_ttc_exposure_s", "Critical-TTC exp.", " s", "lower", 2),
        ("near_zero_clearance_rate", "Near-zero exp.", "", "lower", 3),
        ("overlap_any", "Overlap", "", "lower", 0),
        ("offroad_any", "Off-road", "", "lower", 0),
    ),
    "contact": (
        ("clearance_p05_m", "Clearance p05", " m", "higher", 2),
        ("terminal_clearance_m", "Terminal clearance", " m", "higher", 2),
        ("clearance_gain_m", "Clearance recovery", " m", "higher", 2),
        ("overlap_duration_s", "Overlap duration", " s", "lower", 2),
        ("penetration_duration_s", "Penetration duration", " s", "lower", 2),
        ("max_penetration_depth_m", "Max penetration", " m", "lower", 2),
        ("stable_stop", "Stable stop", "", "higher", 0),
    ),
}


def _metric_float(frame: dict[str, Any], key: str) -> float | None:
    try:
        value = float((frame.get("metrics", {}) or {}).get(key))
        return value if math.isfinite(value) else None
    except Exception:
        return None


def _scene_metric(scene: dict[str, Any], *keys: str) -> float | None:
    summary = scene.get("metric_summary", {}) or {}
    for key in keys:
        for source in (scene, summary):
            try:
                if key in source:
                    value = float(source[key])
                    if math.isfinite(value):
                        return value
            except Exception:
                pass
    return None


def _frame(trace: list[dict[str, Any]], index: int) -> dict[str, Any]:
    return trace[min(max(index, 0), len(trace) - 1)]


def _sdc_agent(frame: dict[str, Any]) -> dict[str, Any] | None:
    for agent in frame.get("agents", []):
        if agent.get("is_sdc"):
            return agent
    return None


def _sdc(frame: dict[str, Any]) -> tuple[float, float] | None:
    agent = _sdc_agent(frame)
    if agent is None:
        return None
    try:
        return float(agent["x"]), float(agent["y"])
    except Exception:
        return None


def _box_corners(agent: dict[str, Any]) -> list[tuple[float, float]]:
    x = float(agent["x"]); y = float(agent["y"])
    half_l = max(float(agent["length"]), 0.1) / 2.0
    half_w = max(float(agent["width"]), 0.1) / 2.0
    yaw = float(agent["yaw"])
    c, s = math.cos(yaw), math.sin(yaw)
    out = []
    for dx, dy in ((half_l, half_w), (half_l, -half_w), (-half_l, -half_w), (-half_l, half_w)):
        out.append((x + c * dx - s * dy, y + s * dx + c * dy))
    return out


def _orient(a, b, c) -> float:
    return (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])


def _point_segment_distance(p, a, b) -> float:
    vx, vy = b[0] - a[0], b[1] - a[1]
    wx, wy = p[0] - a[0], p[1] - a[1]
    denom = vx * vx + vy * vy
    if denom <= 1e-12:
        return math.hypot(wx, wy)
    t = max(0.0, min(1.0, (wx * vx + wy * vy) / denom))
    qx, qy = a[0] + t * vx, a[1] + t * vy
    return math.hypot(p[0] - qx, p[1] - qy)


def _segments_intersect(a, b, c, d) -> bool:
    eps = 1e-9
    o1, o2, o3, o4 = _orient(a, b, c), _orient(a, b, d), _orient(c, d, a), _orient(c, d, b)
    if ((o1 > eps and o2 < -eps) or (o1 < -eps and o2 > eps)) and ((o3 > eps and o4 < -eps) or (o3 < -eps and o4 > eps)):
        return True
    def on(p, q, r):
        return abs(_orient(p, q, r)) <= eps and min(p[0], q[0]) - eps <= r[0] <= max(p[0], q[0]) + eps and min(p[1], q[1]) - eps <= r[1] <= max(p[1], q[1]) + eps
    return on(a, b, c) or on(a, b, d) or on(c, d, a) or on(c, d, b)


def _polygon_distance(poly_a, poly_b) -> float:
    edges_a = list(zip(poly_a, poly_a[1:] + poly_a[:1]))
    edges_b = list(zip(poly_b, poly_b[1:] + poly_b[:1]))
    if any(_segments_intersect(a, b, c, d) for a, b in edges_a for c, d in edges_b):
        return 0.0
    return min(
        min(_point_segment_distance(p, c, d) for p in poly_a for c, d in edges_b),
        min(_point_segment_distance(p, a, b) for p in poly_b for a, b in edges_a),
    )


def _minimum_box_pair(frame: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any], float] | None:
    sdc = _sdc_agent(frame)
    if sdc is None:
        return None
    try:
        sdc_poly = _box_corners(sdc)
    except Exception:
        return None
    rows = []
    for other in frame.get("agents", []):
        if other.get("is_sdc"):
            continue
        try:
            dist = _polygon_distance(sdc_poly, _box_corners(other))
        except Exception:
            continue
        rows.append((dist, other))
    if not rows:
        return None
    dist, other = min(rows, key=lambda row: row[0])
    return sdc, other, float(dist)


def _prepare_roadgraph_segments(context, center, radius):
    """Prepare the exact visible road polylines once for a fixed camera.

    Rendering previously created one Line2D artist per polyline on every frame.
    A single LineCollection preserves the same geometry/linewidth/alpha while
    avoiding hundreds of Python artist constructions per frame.
    """
    cx, cy = center
    segments = []
    for polyline in (context or {}).get("roadgraph_polylines", []):
        xy = polyline.get("xy") or []
        points = []
        for point in xy:
            try:
                x, y = float(point[0]), float(point[1])
            except Exception:
                continue
            if abs(x - cx) <= radius + 5.0 and abs(y - cy) <= radius + 5.0:
                points.append((x, y))
        if len(points) >= 2:
            segments.append(points)
    return segments


def _draw_roadgraph(ax, context, center, radius, prepared_segments=None):
    segments = prepared_segments
    if segments is None:
        segments = _prepare_roadgraph_segments(context, center, radius)
    if segments:
        cycle = plt.rcParams.get("axes.prop_cycle").by_key().get("color", ["C0"])
        colors = [cycle[i % len(cycle)] for i in range(len(segments))]
        ax.add_collection(LineCollection(segments, colors=colors, linewidths=0.65, alpha=0.35, zorder=0))


def _all_model_fixed_view(traces: dict[str, list[dict[str, Any]]], minimum_radius: float):
    points = [point for trace in traces.values() for frame in trace for point in [_sdc(frame)] if point is not None]
    if not points:
        return (0.0, 0.0), minimum_radius
    min_x, max_x = min(p[0] for p in points), max(p[0] for p in points)
    min_y, max_y = min(p[1] for p in points), max(p[1] for p in points)
    center = ((min_x + max_x) / 2.0, (min_y + max_y) / 2.0)
    radius = max(minimum_radius, 0.55 * max(max_x - min_x, max_y - min_y) + 6.0)
    return center, radius


def _dynamic_center(traces: list[list[dict[str, Any]]], sim_index: int):
    points = [p for trace in traces for p in [_sdc(_frame(trace, sim_index))] if p is not None]
    if not points:
        return 0.0, 0.0
    return sum(x for x, _ in points) / len(points), sum(y for _, y in points) / len(points)


def _contact_marker(trace, regime):
    for idx, row in enumerate(trace):
        if (_metric_float(row, "overlap") or 0.0) > 0.5:
            return _sdc(row), "observed overlap", idx
    # Contact bucket membership is a counterfactual-surrogate label in the
    # current dataset build, not proof that raw WOMD replay starts post-impact.
    # Do not draw a fabricated contact marker when no simulator overlap occurs.
    return None, None, None


def _yaw_rate(trace: list[dict[str, Any]], index: int, metric_dt_s: float) -> float | None:
    if index <= 0:
        return 0.0
    curr = _metric_float(_frame(trace, index), "ego_yaw_rad")
    prev = _metric_float(_frame(trace, index - 1), "ego_yaw_rad")
    if curr is None or prev is None:
        return None
    return math.atan2(math.sin(curr - prev), math.cos(curr - prev)) / metric_dt_s


def _draw_frame(
    ax, trace, sim_index, title, center, radius, contact_xy, contact_label, metric_dt_s, context=None, contact_event_index=None,
    *, show_hud: bool = True, show_axes: bool = True, show_clearance_annotation: bool = True,
    roadgraph_segments=None,
):
    held = sim_index >= len(trace)
    row = _frame(trace, sim_index)
    cx, cy = center
    ax.clear(); ax.set_aspect("equal", adjustable="box")
    ax.set_xlim(cx - radius, cx + radius); ax.set_ylim(cy - radius, cy + radius)
    _draw_roadgraph(ax, context, center, radius, prepared_segments=roadgraph_segments)
    ax.set_title(title + (" · final state held" if held else ""), fontsize=10)
    if show_axes:
        ax.set_xlabel("x [m]"); ax.set_ylabel("y [m]"); ax.grid(alpha=0.15)
    else:
        ax.set_xticks([]); ax.set_yticks([]); ax.grid(False)

    trail = [_sdc(r) for r in trace[:min(sim_index, len(trace) - 1) + 1]]
    trail = [p for p in trail if p is not None]
    if len(trail) >= 2:
        ax.plot([p[0] for p in trail], [p[1] for p in trail], linewidth=1.8, alpha=0.9, zorder=2)
    # Never leak a future collision into earlier frames. The marker only appears
    # once the event has actually happened; its text label is restricted to the
    # event neighborhood to avoid covering vehicles for the rest of the clip.
    if contact_xy is not None and contact_event_index is not None and sim_index >= contact_event_index:
        ax.scatter([contact_xy[0]], [contact_xy[1]], marker="x", s=70, linewidths=1.8, alpha=0.75, zorder=5)
        if abs(sim_index - contact_event_index) <= 1:
            ax.annotate(contact_label or "contact", contact_xy, xytext=(6, 6), textcoords="offset points", fontsize=7,
                        bbox={"boxstyle": "round", "facecolor": "white", "alpha": 0.75}, zorder=7)

    overlap = (_metric_float(row, "overlap") or 0.0) > 0.5
    offroad = (_metric_float(row, "offroad") or 0.0) > 0.5
    for agent in row.get("agents", []):
        try:
            x, y = float(agent["x"]), float(agent["y"])
            length, width, yaw = max(float(agent["length"]), 0.1), max(float(agent["width"]), 0.1), float(agent["yaw"])
        except Exception:
            continue
        if abs(x - cx) > radius + length or abs(y - cy) > radius + length:
            continue
        is_sdc = bool(agent.get("is_sdc"))
        edge = "red" if is_sdc and overlap else ("orange" if is_sdc and offroad else ("tab:blue" if is_sdc else "0.35"))
        rect = patches.Rectangle((x - length / 2, y - width / 2), length, width, fill=False,
                                 linewidth=2.4 if is_sdc else 0.8, edgecolor=edge, zorder=4 if is_sdc else 3)
        rect.set_transform(transforms.Affine2D().rotate_around(x, y, yaw) + ax.transData)
        ax.add_patch(rect)
        if is_sdc:
            ax.text(x, y, "SDC", fontsize=8, ha="center", va="center", zorder=6)

    reported = _metric_float(row, "min_clearance_m")
    pair = _minimum_box_pair(row)
    if show_clearance_annotation and pair is not None and reported is not None:
        sdc, other, rendered_dist = pair
        sx, sy, ox, oy = float(sdc["x"]), float(sdc["y"]), float(other["x"]), float(other["y"])
        ax.plot([sx, ox], [sy, oy], linestyle="--", linewidth=1.0, alpha=0.65, zorder=1)
        mismatch = abs(rendered_dist - max(0.0, reported)) > 0.15
        label = f"clearance={reported:.2f} m"
        if mismatch:
            label += "*"
        ax.annotate(label, ((sx + ox) / 2.0, (sy + oy) / 2.0), xytext=(4, 4), textcoords="offset points", fontsize=7,
                    bbox={"boxstyle": "round", "facecolor": "white", "alpha": 0.70}, zorder=7)

    # Keep the map readable. Detailed candidate/reason/provenance belongs in
    # the side panel/index, not on top of road geometry.
    status = [f"t={row.get('time_index')}"]
    for key, label, unit in (("min_clearance_m", "clr", "m"), ("ttc_s", "TTC", "s"),
                             ("ego_speed_mps", "v", "m/s")):
        value = _metric_float(row, key)
        if value is not None:
            status.append(f"{label}={value:.2f}{unit}")
    flags = []
    if overlap:
        flags.append("OVERLAP")
    if offroad:
        flags.append("OFF-ROAD")
    yr = _yaw_rate(trace, min(sim_index, len(trace) - 1), metric_dt_s)
    if yr is not None:
        status.append(f"yaw-rate={yr:.2f}rad/s")
    lines = ["  ·  ".join(status[:4])]
    if flags:
        lines.append(" / ".join(flags))
    if show_hud:
        ax.text(0.012, 0.985, "\n".join(lines), transform=ax.transAxes, va="top", fontsize=7.8,
                bbox={"boxstyle": "round,pad=0.25", "facecolor": "white", "alpha": 0.78}, zorder=10)


def _sample_indices(
    frame_count: int, fps: int, metric_dt_s: float, playback_slowdown: float = 1.0,
    *, clip_duration_s: float | None = None, max_sim_index: int | None = None,
) -> list[int]:
    """Map encoded frames onto simulation states, including the clip endpoint.

    The old time-based formula sampled frame i at i/fps and therefore a 4.0 s
    clip encoded at 10 fps ended at 3.9 s.  For Contact supplements this could
    omit the terminal render state while the side panel correctly reported the
    full-run terminal metric.  When clip_duration_s is supplied, distribute the
    encoded frames over [0, terminal_index] inclusively so the final video frame
    and terminal metric refer to the same simulated endpoint.
    """
    playback_slowdown = float(playback_slowdown)
    if not math.isfinite(playback_slowdown) or playback_slowdown <= 0.0:
        raise ValueError(f"invalid playback_slowdown={playback_slowdown}")
    if frame_count <= 1:
        return [0]
    if clip_duration_s is None:
        indices = [int(round((i / fps / playback_slowdown) / metric_dt_s)) for i in range(frame_count)]
    else:
        terminal = max(0, int(round(float(clip_duration_s) / float(metric_dt_s))))
        if max_sim_index is not None:
            terminal = min(terminal, max(0, int(max_sim_index)))
        indices = [int(round(i * terminal / (frame_count - 1))) for i in range(frame_count)]
    if max_sim_index is not None:
        cap = max(0, int(max_sim_index))
        indices = [min(max(0, x), cap) for x in indices]
    return indices


def _validate_trace_time_alignment(traces: dict[str, list[dict[str, Any]]], item: dict[str, Any]) -> dict[str, Any]:
    starts: dict[str, int] = {}
    lengths: dict[str, int] = {}
    for method, trace in traces.items():
        times = []
        for row in trace:
            try:
                times.append(int(row["time_index"]))
            except Exception as exc:
                raise SystemExit(f"{item.get('target_key')}: render_trace for {method} lacks integer time_index") from exc
        if not times:
            raise SystemExit(f"{item.get('target_key')}: empty time-index sequence for {method}")
        bad = [(a, b) for a, b in zip(times, times[1:]) if b != a + 1]
        if bad:
            raise SystemExit(f"{item.get('target_key')}: non-consecutive render time_index for {method}; examples={bad[:5]}")
        starts[method] = times[0]
        lengths[method] = len(times)
    if len(set(starts.values())) != 1:
        raise SystemExit(f"{item.get('target_key')}: model traces do not start at the same simulator time: {starts}")
    # Safe/Near treatment starts at the locked target.  Contact first executes
    # the shared exact-a0 pre-treatment prelude, so the compared policies and
    # render traces start at the observed-contact treatment boundary instead.
    expected_field = "contact_anchor_time_index" if item.get("contact_anchor_time_index") is not None else "target_time_index"
    expected = item.get(expected_field)
    if expected is not None and int(expected) != next(iter(starts.values())):
        raise SystemExit(
            f"{item.get('target_key')}: trace start time {next(iter(starts.values()))} != selected {expected_field} {expected}"
        )
    return {
        "start_time_index": next(iter(starts.values())),
        "expected_start_field": expected_field,
        "expected_start_time_index": int(expected) if expected is not None else None,
        "trace_lengths": lengths,
        "consecutive": True,
    }


def _series(trace: list[dict[str, Any]], key: str, sim_indices: list[int]) -> list[float]:
    values = []
    for idx in sim_indices:
        val = _metric_float(_frame(trace, idx), key)
        values.append(float("nan") if val is None else val)
    return values


def _prepare_timeline_cache(traces: dict[str, list[dict[str, Any]]], sim_indices: list[int], regime: str):
    secondary_key = "ttc_s" if regime == "near" else "ego_speed_mps"
    out = {}
    for method, trace in traces.items():
        out[method] = {
            "clearance": _series(trace, "min_clearance_m", sim_indices),
            "secondary": _series(trace, secondary_key, sim_indices),
            "overlap": [((_metric_float(_frame(trace, idx), "overlap") or 0.0) > 0.5) for idx in sim_indices],
        }
    return out


def _draw_timeline(ax, twin, traces: dict[str, list[dict[str, Any]]], display: dict[str, str], frame_index: int,
                   sim_indices: list[int], fps: int, regime: str, series_cache=None, playback_slowdown: float = 1.0):
    ax.clear(); twin.clear()
    times = [i / fps for i in range(len(sim_indices))]
    visible = min(frame_index + 1, len(times))
    cache = series_cache or _prepare_timeline_cache(traces, sim_indices, regime)
    for method in traces:
        ax.plot(times[:visible], cache[method]["clearance"][:visible], label=f"{display[method]} clearance")
    if regime == "near":
        ax.axhline(2.0, linestyle="--", linewidth=0.9, alpha=0.6, label="2 m near-contact boundary")
    ax.set_xlim(0.0, max(times[-1] if times else 0.0, 0.1))
    xlabel = "rollout video time [s]"
    if abs(float(playback_slowdown) - 1.0) > 1e-9:
        xlabel += f" (playback {1.0/float(playback_slowdown):.2f}× real-time)"
    ax.set_xlabel(xlabel)
    ax.set_ylabel("box clearance [m]"); ax.grid(alpha=0.15)
    if regime == "contact":
        ax.axhline(0.0, linestyle="--", linewidth=0.9, alpha=0.55, label="contact boundary")
    if visible > 0:
        ax.axvline(times[visible - 1], linewidth=0.8, alpha=0.35)

    secondary_label = "TTC [s]" if regime == "near" else "ego speed [m/s]"
    for method in traces:
        twin.plot(times[:visible], cache[method]["secondary"][:visible], linestyle=":" if regime == "near" else "--",
                  alpha=0.65, label=f"{display[method]} {'TTC' if regime == 'near' else 'speed'}")
    if regime == "near":
        twin.axhline(3.0, linestyle=":", linewidth=0.9, alpha=0.45, label="3 s TTC boundary")
    twin.yaxis.set_label_position("right")
    twin.yaxis.tick_right()
    twin.set_ylabel(secondary_label, labelpad=10)

    overlap_y = ax.get_ylim()[0]
    for method in traces:
        xs = [times[j] for j in range(visible) if cache[method]["overlap"][j]]
        if xs:
            ax.scatter(xs, [overlap_y] * len(xs), marker="x", s=18, label=f"{display[method]} overlap")
    handles, labels = ax.get_legend_handles_labels(); h2, l2 = twin.get_legend_handles_labels()
    ax.legend(handles + h2, labels + l2, loc="upper right", fontsize=6.7, ncol=2)


def _fmt(value: float | None, unit: str = "", digits: int = 2) -> str:
    return "n/a" if value is None else f"{value:.{digits}f}{unit}"


def _summary(scene: dict[str, Any], regime: str) -> str:
    if regime == "safe":
        parts = [
            f"NUP={_fmt(_scene_metric(scene, 'closed_loop_bounded_NUP'))}",
            f"intervention={_fmt(_scene_metric(scene, 'intervention_rate'))}",
            f"clearance p05={_fmt(_scene_metric(scene, 'min_clearance_m_p05', 'min_clearance_m_min'), ' m')}",
            f"TTC p05={_fmt(_scene_metric(scene, 'ttc_s_p05', 'ttc_s_min'), ' s')}",
            f"offroad={_fmt(_scene_metric(scene, 'offroad_any'), digits=0)}",
        ]
    elif regime == "near":
        parts = [
            f"TTC p05={_fmt(_scene_metric(scene, 'ttc_s_p05'), ' s')}",
            f"clearance p05={_fmt(_scene_metric(scene, 'min_clearance_m_p05'), ' m')}",
            f"critical-TTC exposure={_fmt(_scene_metric(scene, 'critical_ttc_exposure_duration_s'), ' s')}",
            f"near-zero exposure={_fmt(_scene_metric(scene, 'near_zero_clearance_exposure_rate'))}",
            f"NUP={_fmt(_scene_metric(scene, 'closed_loop_bounded_NUP'))}",
        ]
    else:
        parts = [
            f"clearance p05={_fmt(_scene_metric(scene, 'min_clearance_m_p05'), ' m')}",
            f"terminal clearance={_fmt(_scene_metric(scene, 'terminal_clearance_m'), ' m')}",
            f"recovery gain={_fmt(_scene_metric(scene, 'clearance_recovery_gain_m'), ' m')}",
            f"overlap duration={_fmt(_scene_metric(scene, 'overlap_duration_s'), ' s')}",
            f"penetration duration={_fmt(_scene_metric(scene, 'penetration_duration_s'), ' s')}",
            f"max penetration={_fmt(_scene_metric(scene, 'penetration_depth_m_max'), ' m')}",
            f"stable stop={_fmt(_scene_metric(scene, 'new_stable_stop_quality_event'), digits=0)}",
        ]
    return " | ".join(parts)


def _short_display(method: str, max_len: int = 28) -> str:
    text = _display_name(method)
    return text if len(text) <= max_len else text[: max_len - 1] + "…"


def _fmt_panel(value: Any, unit: str, digits: int) -> str:
    try:
        x = float(value)
    except Exception:
        return "n/a"
    if not math.isfinite(x):
        return "n/a"
    return f"{x:.{digits}f}{unit}"


def _favorable_delta(ocrap: Any, external: Any, direction: str) -> float | None:
    try:
        a, b = float(ocrap), float(external)
    except Exception:
        return None
    if not math.isfinite(a) or not math.isfinite(b):
        return None
    return (a - b) if direction == "higher" else (b - a)


def _draw_info_panel(ax, *, item: dict[str, Any], selection: dict[str, Any], regime: str, comparator: str, comparator_role: str, playback_slowdown: float = 1.0):
    ax.clear(); ax.axis("off")
    y = 0.985
    ax.text(0.0, y, "FULL-RUN METRICS", transform=ax.transAxes, va="top", fontsize=10.0, fontweight="bold")
    y -= 0.036
    ax.text(0.0, y, "full-run endpoint metrics; trace rerun is visualization-only", transform=ax.transAxes, va="top", fontsize=7.2, alpha=0.72)
    y -= 0.052
    comparator_name = _short_display(comparator, 18)
    role_short = _short_comparator_role(comparator_role, regime)
    ax.text(0.0, y, f"Comparator: {comparator_name}", transform=ax.transAxes, va="top", fontsize=8.4, fontweight="bold")
    y -= 0.028
    ax.text(0.0, y, role_short, transform=ax.transAxes, va="top", fontsize=7.3, alpha=0.75)
    y -= 0.052

    om = item.get("ocrap_metrics") or {}
    em = (item.get("external_metrics") or {}).get(comparator, {}) or {}
    ax.text(0.00, y, "Metric", transform=ax.transAxes, fontsize=7.5, fontweight="bold")
    ax.text(0.51, y, "OC-RAP", transform=ax.transAxes, fontsize=7.5, fontweight="bold", ha="right")
    ax.text(0.76, y, comparator_name, transform=ax.transAxes, fontsize=7.5, fontweight="bold", ha="right")
    ax.text(0.99, y, "benefit Δ", transform=ax.transAxes, fontsize=7.5, fontweight="bold", ha="right")
    y -= 0.027
    for key, label, unit, direction, digits in PANEL_METRICS[regime]:
        ov, ev = om.get(key), em.get(key)
        delta = _favorable_delta(ov, ev, direction)
        ax.text(0.00, y, label, transform=ax.transAxes, fontsize=7.2)
        ax.text(0.51, y, _fmt_panel(ov, unit, digits), transform=ax.transAxes, fontsize=7.2, ha="right")
        ax.text(0.76, y, _fmt_panel(ev, unit, digits), transform=ax.transAxes, fontsize=7.2, ha="right")
        dtext = "n/a" if delta is None else f"{delta:+.{digits if digits > 0 else 0}f}{unit}"
        ax.text(0.99, y, dtext, transform=ax.transAxes, fontsize=7.2, ha="right", fontweight="bold" if delta is not None and delta > 0 else "normal")
        y -= 0.030

    y -= 0.025
    ax.text(0.0, y, "ALL-BASELINE CONTEXT", transform=ax.transAxes, va="top", fontsize=9.2, fontweight="bold")
    y -= 0.038
    if regime == "safe":
        scores = item.get("external_absolute_scores") or {}
        ordered = sorted(scores, key=lambda m: (-float(scores[m]), str(m)))
        for rank, method in enumerate(ordered, 1):
            marker = "▶" if method == comparator else " "
            ax.text(0.0, y, f"{marker} {rank}. {_short_display(method, 25)}", transform=ax.transAxes, fontsize=7.2)
            ax.text(0.99, y, f"sel-score={float(scores[method]):+.2f}", transform=ax.transAxes, fontsize=7.2, ha="right")
            y -= 0.027
    else:
        rows = item.get("per_baseline") or {}
        ordered = sorted(rows, key=lambda m: (float(rows[m].get("relative_score", 0.0)), str(m)))
        for rank, method in enumerate(ordered, 1):
            marker = "▶" if method == comparator else " "
            score = float(rows[method].get("relative_score", 0.0))
            ax.text(0.0, y, f"{marker} {rank}. {_short_display(method, 25)}", transform=ax.transAxes, fontsize=7.2)
            ax.text(0.99, y, f"pair-score Δ={score:+.2f}", transform=ax.transAxes, fontsize=7.2, ha="right")
            y -= 0.027

    y -= 0.020
    tier = str(item.get("selection_tier") or "")
    profile = str(item.get("evidence_profile") or "")
    ax.text(0.0, y, "SELECTION PROVENANCE", transform=ax.transAxes, fontsize=8.8, fontweight="bold")
    y -= 0.034
    provenance_lines = [
        f"post-hoc qualitative · tier: {tier}",
        f"profile: {profile}",
        f"target-locked · all {selection.get('num_external_baselines', '?')} paper-table baselines checked",
    ]
    if abs(float(playback_slowdown) - 1.0) > 1e-9:
        provenance_lines.append(f"video playback: {1.0/float(playback_slowdown):.2f}× real-time (simulation span unchanged)")
    for line in provenance_lines:
        ax.text(0.0, y, line, transform=ax.transAxes, fontsize=7.1)
        y -= 0.028
    if regime != "safe":
        ax.text(0.0, y, f"non-regressive: {item.get('num_nonregressive_external_comparisons', 'n/a')}/{selection.get('num_external_baselines', '?')}", transform=ax.transAxes, fontsize=7.1)


def _video_output_complete(path: Path, expected_frames: int, fps: int, use_mp4: bool) -> bool:
    if not path.is_file() or path.stat().st_size < 4096:
        return False
    if use_mp4 and shutil.which("ffprobe"):
        try:
            raw = subprocess.check_output([
                "ffprobe", "-v", "error", "-count_frames", "-select_streams", "v:0",
                "-show_entries", "stream=nb_read_frames,duration", "-of", "json", str(path),
            ], text=True, stderr=subprocess.DEVNULL, timeout=20)
            stream = (json.loads(raw).get("streams") or [{}])[0]
            frames = stream.get("nb_read_frames")
            if frames not in (None, "N/A") and int(frames) >= expected_frames:
                return True
            duration = stream.get("duration")
            return duration not in (None, "N/A") and float(duration) + (1.0 / max(fps, 1)) >= expected_frames / max(fps, 1)
        except Exception:
            return False
    if not use_mp4:
        try:
            from PIL import Image
            with Image.open(path) as im:
                return int(getattr(im, "n_frames", 1)) >= expected_frames
        except Exception:
            return False
    return False


def _save_animation(fig, update, frame_count, fps, output: Path, use_mp4: bool, *, progress_label: str = "video"):
    started = time.monotonic()
    every = max(1, int(os.environ.get("VIS_RENDER_PROGRESS_EVERY", "10")))
    last = [-1]
    def update_with_progress(frame_i):
        if frame_i != last[0] and (frame_i == 0 or frame_i == frame_count - 1 or frame_i - last[0] >= every):
            last[0] = frame_i
            elapsed = time.monotonic() - started
            print(f"[VIDEO][FRAME] {progress_label} {frame_i + 1}/{frame_count} ({100.0*(frame_i+1)/frame_count:.0f}%) elapsed={elapsed:.1f}s", flush=True)
        return update(frame_i)
    print(f"[VIDEO][START] {progress_label} frames={frame_count} fps={fps} output={output}", flush=True)
    anim = animation.FuncAnimation(fig, update_with_progress, frames=frame_count, interval=1000 / fps, blit=False)
    # Render atomically.  If matplotlib/ffmpeg raises while drawing a frame, do
    # not leave a tiny corrupt .mp4 at the final path (the previous supplement
    # crash left a 321-byte all-method file).
    tmp = output.with_name(output.stem + ".tmp" + output.suffix)
    try:
        if tmp.exists():
            tmp.unlink()
        if use_mp4:
            writer = animation.FFMpegWriter(fps=fps, bitrate=2200, metadata={"artist": "OC-RAP submission visualization v54"})
            anim.save(tmp, writer=writer)
        else:
            writer = animation.PillowWriter(fps=fps)
            anim.save(tmp, writer=writer)
        tmp.replace(output)
    except Exception:
        try:
            if tmp.exists():
                tmp.unlink()
        finally:
            plt.close(fig)
        raise
    plt.close(fig)
    elapsed = time.monotonic() - started
    size_mb = output.stat().st_size / (1024*1024) if output.is_file() else 0.0
    print(f"[VIDEO][DONE] {progress_label} elapsed={elapsed:.1f}s size={size_mb:.1f}MiB output={output}", flush=True)


def _render_single(*, method, scene, trace, item, regime, display_name, context, center, radius,
                   camera_mode, sim_indices, fps, metric_dt_s, output, use_mp4, playback_slowdown: float = 1.0):
    contact_xy, contact_label, contact_event_index = _contact_marker(trace, regime)
    road_segments = _prepare_roadgraph_segments(context, center, radius) if camera_mode == "fixed" else None
    timeline_cache = _prepare_timeline_cache({method: trace}, sim_indices, regime)
    figure = plt.figure(figsize=(9.6, 7.8), dpi=100)
    grid = figure.add_gridspec(2, 1, height_ratios=[4.3, 1.35])
    map_ax = figure.add_subplot(grid[0, 0]); timeline_ax = figure.add_subplot(grid[1, 0]); timeline_twin = timeline_ax.twinx()
    figure.suptitle(f"{regime.upper()} · {display_name} · rank {item.get('category_rank')}\n{_summary(scene, regime)}", fontsize=10)
    figure.subplots_adjust(top=0.89, bottom=0.08, hspace=0.30)

    def update(frame_i):
        sim_idx = sim_indices[frame_i]
        view_center = _dynamic_center([trace], sim_idx) if camera_mode == "dynamic" else center
        _draw_frame(map_ax, trace, sim_idx, display_name, view_center, radius, contact_xy, contact_label, metric_dt_s, context, contact_event_index,
                    roadgraph_segments=road_segments if camera_mode == "fixed" else None)
        _draw_timeline(timeline_ax, timeline_twin, {method: trace}, {method: display_name}, frame_i, sim_indices, fps, regime,
                       series_cache=timeline_cache, playback_slowdown=playback_slowdown)

    _save_animation(figure, update, len(sim_indices), fps, output, use_mp4, progress_label=f"{regime}/{output.stem}")


def _draw_montage_info(ax, *, traces, displays, sim_idx, metric_dt_s, regime, item, selection, playback_slowdown: float = 1.0):
    ax.clear(); ax.axis("off")
    row0 = next(iter(traces.values()))
    frame = _frame(row0, sim_idx)
    start_t = int(row0[0].get("time_index", 0)) if row0 else 0
    current_t = int(frame.get("time_index", start_t)) if frame else start_t
    ax.text(0.0, 0.98, "TARGET-LOCKED ALL-METHOD VIEW", va="top", fontsize=10.2, fontweight="bold")
    ax.text(0.0, 0.91, f"rank {item.get('category_rank')} · sim t={current_t} · +{(current_t-start_t)*metric_dt_s:.1f}s", va="top", fontsize=8.2)
    ax.text(0.0, 0.86, "Same scene · same time · shared fixed camera", va="top", fontsize=7.6, alpha=0.75)
    # These values are required in both normal-speed and slowed playback.  A
    # previous indentation error initialized ``metric_name`` only in the
    # normal-speed branch and ``y`` only in the slowed branch, causing the
    # all-method Contact supplement montage to crash on its first frame.
    metric_name = "TTC" if regime == "near" else "clearance"
    metric_key = "ttc_s" if regime == "near" else "min_clearance_m"
    y = 0.79
    if abs(float(playback_slowdown) - 1.0) > 1e-9:
        ax.text(0.0, 0.82, f"Playback {1.0/float(playback_slowdown):.2f}× real-time · simulation span unchanged", va="top", fontsize=7.2, alpha=0.75)
        y = 0.75
    for method, trace in traces.items():
        r = _frame(trace, sim_idx)
        v = _metric_float(r, metric_key)
        overlap = (_metric_float(r, "overlap") or 0.0) > 0.5
        suffix = " · overlap" if overlap else ""
        value = "n/a" if v is None else f"{v:.2f}{' s' if regime == 'near' else ' m'}"
        ax.text(0.0, y, _short_display(method, 19), fontsize=7.5, fontweight="bold" if method == "ocrap" else "normal")
        ax.text(0.98, y, f"{metric_name} {value}{suffix}", fontsize=7.3, ha="right")
        y -= 0.065
    y -= 0.02
    ax.text(0.0, y, "Selection is qualitative/post-hoc; population claims use the locked quantitative tables.",
            fontsize=7.0, wrap=True, va="top")


def _render_montage(*, methods, traces, item, selection, regime, displays, context, center, radius,
                    camera_mode, sim_indices, fps, metric_dt_s, output, use_mp4, playback_slowdown: float = 1.0):
    contacts = {m: _contact_marker(traces[m], regime) for m in methods}
    road_segments = _prepare_roadgraph_segments(context, center, radius) if camera_mode == "fixed" else None
    total_panels = len(methods) + 1
    if total_panels <= 8:
        cols = 4
    elif total_panels <= 9:
        cols = 3
    else:
        cols = 4
    rows = int(math.ceil(total_panels / cols))
    figure = plt.figure(figsize=(4.0 * cols, 4.15 * rows), dpi=100)
    grid = figure.add_gridspec(rows, cols, wspace=0.08, hspace=0.14)
    axes = {}
    for i, method in enumerate(methods):
        axes[method] = figure.add_subplot(grid[i // cols, i % cols])
    info_i = len(methods)
    info_ax = figure.add_subplot(grid[info_i // cols, info_i % cols])
    regime_title = "NEAR-CONTACT" if regime == "near" else ("CONTACT" if regime == "contact" else "SAFE")
    figure.suptitle(f"{regime_title} · target-locked all-method comparison · Rank {item.get('category_rank')}",
                    fontsize=12.0, fontweight="bold", y=0.985)
    figure.subplots_adjust(left=0.025, right=0.985, top=0.93, bottom=0.035)

    def update(frame_i):
        sim_idx = sim_indices[frame_i]
        view_center = _dynamic_center([traces[m] for m in methods], sim_idx) if camera_mode == "dynamic" else center
        for method in methods:
            xy, label, event_idx = contacts[method]
            _draw_frame(axes[method], traces[method], sim_idx, displays[method], view_center, radius, xy, label,
                        metric_dt_s, context, event_idx, show_hud=False, show_axes=False, show_clearance_annotation=False,
                        roadgraph_segments=road_segments if camera_mode == "fixed" else None)
        _draw_montage_info(info_ax, traces={m: traces[m] for m in methods}, displays=displays, sim_idx=sim_idx,
                           metric_dt_s=metric_dt_s, regime=regime, item=item, selection=selection,
                           playback_slowdown=playback_slowdown)

    _save_animation(figure, update, len(sim_indices), fps, output, use_mp4, progress_label=f"{regime}/{output.stem}")


def _render_pair(*, methods, scenes, traces, item, selection, regime, displays, context, center, radius,
                 camera_mode, sim_indices, fps, metric_dt_s, output, use_mp4, comparator_role,
                 playback_slowdown: float = 1.0):
    ocrap, comparator = methods
    contact = {m: _contact_marker(traces[m], regime) for m in methods}
    road_segments = _prepare_roadgraph_segments(context, center, radius) if camera_mode == "fixed" else None
    timeline_cache = _prepare_timeline_cache(traces, sim_indices, regime)
    figure = plt.figure(figsize=(18.0, 9.6), dpi=100)
    grid = figure.add_gridspec(2, 3, width_ratios=[1.0, 1.0, 0.82], height_ratios=[3.55, 1.10])
    axes = {ocrap: figure.add_subplot(grid[0, 0]), comparator: figure.add_subplot(grid[0, 1])}
    timeline_ax = figure.add_subplot(grid[1, 0:2]); timeline_twin = timeline_ax.twinx()
    info_ax = figure.add_subplot(grid[:, 2])
    regime_title = "NEAR-CONTACT" if regime == "near" else ("CONTACT" if regime == "contact" else regime.upper())
    comparator_name = _short_display(comparator, 20)
    role_short = _short_comparator_role(comparator_role, regime)
    figure.suptitle(
        f"{regime_title} · {displays.get('ocrap', 'OC-RAP')} vs {comparator_name} · Rank {item.get('category_rank')}",
        fontsize=12.2, fontweight="bold", y=0.985,
    )
    figure.text(
        0.5, 0.952,
        f"{role_short} · same target · {camera_mode} world camera · target-locked cohort · all {selection.get('num_external_baselines', '?')} baselines audited",
        ha="center", va="top", fontsize=8.1, alpha=0.78,
    )
    figure.subplots_adjust(top=0.905, bottom=0.070, left=0.045, right=0.985, hspace=0.28, wspace=0.16)
    _draw_info_panel(info_ax, item=item, selection=selection, regime=regime, comparator=comparator,
                     comparator_role=comparator_role, playback_slowdown=playback_slowdown)

    def update(frame_i):
        sim_idx = sim_indices[frame_i]
        view_center = _dynamic_center([traces[m] for m in methods], sim_idx) if camera_mode == "dynamic" else center
        for method in methods:
            xy, label, event_idx = contact[method]
            _draw_frame(axes[method], traces[method], sim_idx, displays[method], view_center, radius, xy, label, metric_dt_s, context, event_idx,
                        roadgraph_segments=road_segments if camera_mode == "fixed" else None)
        _draw_timeline(timeline_ax, timeline_twin, {m: traces[m] for m in methods}, displays, frame_i, sim_indices, fps, regime,
                       series_cache=timeline_cache, playback_slowdown=playback_slowdown)

    _save_animation(figure, update, len(sim_indices), fps, output, use_mp4, progress_label=f"{regime}/{output.stem}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--trace", action="append", default=[], metavar="METHOD=SCENES.jsonl")
    ap.add_argument("--selection", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, required=True)
    ap.add_argument("--fps", type=int, default=10)
    ap.add_argument("--format", choices=("auto", "mp4", "gif"), default="auto")
    ap.add_argument("--view-radius-m", type=float, default=35.0)
    ap.add_argument("--playback-slowdown", type=float, default=1.0, help="Minimum playback slowdown factor. 1.0 is real-time; >1 renders more slowly while preserving the simulation span.")
    ap.add_argument("--target-rendered-duration-s", type=float, default=0.0, help="If >0, automatically slow short clips toward this viewing duration.")
    ap.add_argument("--max-playback-slowdown", type=float, default=1.6, help="Upper bound for automatic slowdown used with --target-rendered-duration-s.")
    ap.add_argument("--supplement-name", default="", help="Optional nested output name, e.g. supplement_01, written under <output-dir>/<regime>/ without overwriting main ranks/index.")
    ap.add_argument("--camera-mode", choices=("fixed", "dynamic"), default="fixed")
    ap.add_argument("--include-singles", action="store_true", help="Render one single-method video for every method (supplement/debug only).")
    ap.add_argument("--include-global-strongest-pair", action="store_true", help="Also compare against the regime-level strongest external baseline when it differs from the per-scene comparator.")
    ap.add_argument("--include-worst-pair", action="store_true", help="Also render OC-RAP vs the per-scene weakest external baseline (not recommended for the main paper).")
    ap.add_argument("--include-all-method-montage", action="store_true", help="Render one synchronized OC-RAP + all-baseline montage per scene (recommended for supplemental material).")
    ap.add_argument("--force", action="store_true", help="Re-render outputs even when an existing file passes completeness validation.")
    args = ap.parse_args()
    if args.fps <= 0 or args.view_radius_m <= 5.0:
        raise SystemExit("fps must be positive and view radius must exceed 5 m")
    if args.playback_slowdown <= 0 or not math.isfinite(args.playback_slowdown):
        raise SystemExit("playback slowdown must be a positive finite number")
    if args.max_playback_slowdown < 1.0 or not math.isfinite(args.max_playback_slowdown):
        raise SystemExit("max playback slowdown must be finite and >= 1")
    if args.target_rendered_duration_s < 0 or not math.isfinite(args.target_rendered_duration_s):
        raise SystemExit("target rendered duration must be finite and >= 0")
    if args.supplement_name and (Path(args.supplement_name).name != args.supplement_name or args.supplement_name in {".", ".."}):
        raise SystemExit("supplement name must be one simple directory name")

    paths = _parse_trace_specs(args.trace)
    print(f"[VIDEO][LOAD] loading {len(paths)} method journals", flush=True)
    load_started = time.monotonic()
    loaded = {method: _load_scenes(path) for method, path in paths.items()}
    print(f"[VIDEO][LOAD] done elapsed={time.monotonic()-load_started:.1f}s", flush=True)
    selection = json.loads(args.selection.read_text(encoding="utf-8"))
    regime = str(selection.get("regime") or "")
    if regime not in {"safe", "near", "contact"}:
        raise SystemExit(f"invalid/missing regime in selection: {regime!r}")
    selected = selection.get("selected") or []
    if not selected:
        raise SystemExit("selection contains no selected scenes")
    external_methods = [m for m in paths if m != "ocrap"]
    expected_external = list(selection.get("external_baselines") or [])
    if set(external_methods) != set(expected_external):
        raise SystemExit(f"trace baseline set does not match selection: traces={external_methods}, selection={expected_external}")

    use_mp4 = args.format == "mp4" or (args.format == "auto" and shutil.which("ffmpeg") is not None)
    if args.format == "mp4" and shutil.which("ffmpeg") is None:
        raise SystemExit("--format mp4 requested but ffmpeg is unavailable")
    suffix = ".mp4" if use_mp4 else ".gif"
    args.output_dir.mkdir(parents=True, exist_ok=True)
    metric_dt_s = float(selection.get("metric_dt_s", 0.1) or 0.1)
    records = []

    total_selected = len(selected)
    for scene_no, item in enumerate(selected, 1):
        key = str(item["target_key"])
        scene_started = time.monotonic()
        print(f"[VIDEO][SCENE] regime={regime} scene={scene_no}/{total_selected} target={key}", flush=True)
        resolved: dict[str, dict[str, Any]] = {}
        methods_resolution: dict[str, str] = {}
        for method in paths:
            scene, how = _resolve_scene(item, loaded[method])
            if scene is None:
                raise SystemExit(f"selected target {key} unresolved for {method}")
            trace = scene.get("render_trace") or []
            if not trace:
                raise SystemExit(f"selected target {key} has no render_trace for {method}; rerun selective traces with full scene detail")
            resolved[method] = scene
            methods_resolution[method] = how
        traces = {m: list(resolved[m]["render_trace"]) for m in paths}
        time_alignment = _validate_trace_time_alignment(traces, item)

        clip_duration_s = float(item.get("clip_duration_s", selection.get("selected_clip_duration_s", 5.0)))
        scene_slowdown = float(args.playback_slowdown)
        if args.target_rendered_duration_s > 0.0 and clip_duration_s > 0.0:
            scene_slowdown = max(scene_slowdown, min(float(args.max_playback_slowdown), float(args.target_rendered_duration_s) / clip_duration_s))
        frame_count = max(1, int(round(clip_duration_s * args.fps * scene_slowdown)))
        max_sim_index = min(len(t) - 1 for t in traces.values())
        sim_indices = _sample_indices(
            frame_count, args.fps, metric_dt_s, playback_slowdown=scene_slowdown,
            clip_duration_s=clip_duration_s, max_sim_index=max_sim_index,
        )
        center, radius = _all_model_fixed_view(traces, args.view_radius_m)
        context = resolved["ocrap"].get("render_context") or next((resolved[m].get("render_context") for m in paths if resolved[m].get("render_context")), {})
        rank = int(item.get("category_rank", len(records) + 1))
        regime_output_root = args.output_dir / regime / args.supplement_name if args.supplement_name else args.output_dir / regime
        scene_dir = regime_output_root / f"rank_{rank:02d}"
        scene_dir.mkdir(parents=True, exist_ok=True)
        displays = {m: _display_name(m) for m in paths}
        display_overrides = selection.get("display_name_overrides") or {}
        if isinstance(display_overrides, dict):
            for m, name in display_overrides.items():
                if m in displays and str(name).strip():
                    displays[m] = str(name).strip()
        outputs = []

        if args.include_singles:
            for method in paths:
                filename = scene_dir / f"{regime}__rank_{rank:02d}__{_safe_name(method)}{suffix}"
                if not args.force and _video_output_complete(filename, frame_count, args.fps, use_mp4):
                    print(f"[VIDEO][REUSE] {filename}", flush=True)
                else:
                    _render_single(method=method, scene=resolved[method], trace=traces[method], item=item, regime=regime,
                                   display_name=displays[method], context=context, center=center, radius=radius,
                                   camera_mode=args.camera_mode, sim_indices=sim_indices, fps=args.fps, metric_dt_s=metric_dt_s,
                                   output=filename, use_mp4=use_mp4, playback_slowdown=scene_slowdown)
                outputs.append({"type": "single", "method": method, "path": str(filename)})

        best = str(item.get("best_external_method") or "")
        worst = str(item.get("worst_external_method") or "")
        primary = str(item.get("primary_external_method") or item.get("hardest_external_method") or best)
        global_strongest = str(item.get("global_strongest_external_method") or selection.get("global_strongest_external_method") or "")
        for label, method in (("best", best), ("worst", worst), ("primary", primary)):
            if method not in external_methods:
                raise SystemExit(f"selection {label} comparator missing from external trace set for {key}: {method}")

        pair_plan: list[tuple[str, str, str]] = [
            ("primary", primary, str(item.get("primary_comparator_reason") or "per-scene strongest/hardest external comparator")),
        ]
        if args.include_global_strongest_pair and global_strongest in external_methods and global_strongest != primary:
            pair_plan.append(("global_strongest", global_strongest, "regime-level strongest external baseline across the full paired population"))
        if args.include_worst_pair and worst != primary and all(worst != m for _r, m, _d in pair_plan):
            pair_plan.append(("worst", worst, "per-scene weakest external baseline; supplementary/debug view"))

        for role, comparator, role_text in pair_plan:
            filename = scene_dir / f"{regime}__rank_{rank:02d}__ocrap_vs_{role}__{_safe_name(comparator)}{suffix}"
            pair_methods = ["ocrap", comparator]
            if not args.force and _video_output_complete(filename, frame_count, args.fps, use_mp4):
                print(f"[VIDEO][REUSE] {filename}", flush=True)
            else:
                _render_pair(methods=pair_methods, scenes={m: resolved[m] for m in pair_methods}, traces={m: traces[m] for m in pair_methods},
                             item=item, selection=selection, regime=regime, displays={m: displays[m] for m in pair_methods}, context=context,
                             center=center, radius=radius, camera_mode=args.camera_mode, sim_indices=sim_indices, fps=args.fps,
                             metric_dt_s=metric_dt_s, output=filename, use_mp4=use_mp4, comparator_role=role_text,
                             playback_slowdown=scene_slowdown)
            outputs.append({"type": f"pair_{role}", "method": comparator, "path": str(filename), "comparator_role": role_text})

        if args.include_all_method_montage:
            montage_methods = ["ocrap"] + expected_external
            filename = scene_dir / f"{regime}__rank_{rank:02d}__all_methods{suffix}"
            if not args.force and _video_output_complete(filename, frame_count, args.fps, use_mp4):
                print(f"[VIDEO][REUSE] {filename}", flush=True)
            else:
                _render_montage(
                    methods=montage_methods, traces={m: traces[m] for m in montage_methods}, item=item, selection=selection,
                    regime=regime, displays={m: displays[m] for m in montage_methods}, context=context, center=center, radius=radius,
                    camera_mode=args.camera_mode, sim_indices=sim_indices, fps=args.fps, metric_dt_s=metric_dt_s,
                    output=filename, use_mp4=use_mp4, playback_slowdown=scene_slowdown,
                )
            outputs.append({"type": "all_method_montage", "methods": montage_methods, "path": str(filename)})
        print(f"[VIDEO][SCENE-DONE] regime={regime} scene={scene_no}/{total_selected} elapsed={time.monotonic()-scene_started:.1f}s", flush=True)
        records.append({
            "target_key": key,
            "rank": rank,
            "scene_id": item.get("scene_id"),
            "target_time_index": item.get("target_time_index"),
            "clip_duration_s": clip_duration_s,
            "encoded_frames": frame_count,
            "fps": args.fps,
            "playback_slowdown": scene_slowdown,
            "rendered_duration_s": frame_count / max(args.fps, 1),
            "metric_dt_s": metric_dt_s,
            "camera_mode": args.camera_mode,
            "camera_center_xy": list(center),
            "camera_radius_m": radius,
            "best_external_method": best,
            "worst_external_method": worst,
            "primary_external_method": primary,
            "global_strongest_external_method": global_strongest or None,
            "resolution": methods_resolution,
            "time_alignment": time_alignment,
            "raw_trace_frames": {m: len(traces[m]) for m in paths},
            "held_final_state": {m: max(sim_indices) >= len(traces[m]) - 1 for m in paths},
            "num_videos": len(outputs),
            "videos": outputs,
        })

    actual_total = sum(r["num_videos"] for r in records)
    index = {
        "event": "regime_visualization_video_index_v124",
        "regime": regime,
        "selection": str(args.selection),
        "external_baselines": external_methods,
        "num_external_baselines": len(external_methods),
        "num_selected_scenes": len(selected),
        "default_video_policy": "one OC-RAP-vs-primary pair per selected scene; supplemental mode can additionally render one synchronized all-method montage",
        "include_singles": bool(args.include_singles),
        "include_global_strongest_pair": bool(args.include_global_strongest_pair),
        "include_worst_pair": bool(args.include_worst_pair),
        "include_all_method_montage": bool(args.include_all_method_montage),
        "num_videos": actual_total,
        "format": suffix.lstrip("."),
        "synchronization_contract": "same selected target, same video-time sample, same simulation dt, same scene-wide fixed camera unless camera_mode=dynamic",
        "pair_layout": "OC-RAP left; primary external comparator right; compact full-run endpoint card and all-baseline audit context at right",
        "records": records,
    }
    if args.supplement_name:
        index["supplement_name"] = args.supplement_name
        index["target_rendered_duration_s"] = args.target_rendered_duration_s
        index["max_playback_slowdown"] = args.max_playback_slowdown
        index_path = args.output_dir / regime / args.supplement_name / "VIDEO_INDEX.json"
    else:
        index_path = args.output_dir / f"{regime.upper()}_VIDEO_INDEX.json"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"event": index["event"], "regime": regime, "num_videos": actual_total, "index": str(index_path)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
