from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


DEFAULT_CONFIG: dict[str, Any] = {
    "seed": 7,
    "data_source": "synthetic_artifact",
    "num_synthetic_scenarios": 4,
    "womd_patterns": None,
    "max_scenarios": None,
    "sample_rate_hz": 10,
    "history_horizon_s": 1.0,
    "prefix_horizon_s": 1.0,
    "recovery_horizon_s": 4.0,
    "planning_time_stride_s": 0.5,
    "max_times_per_scenario": 2,
    "max_biased_times_per_scenario": 2,
    "max_agents": 32,
    "max_map_polylines": 128,
    "max_polyline_points": 64,
    "max_dynamic_signals": 16,
    "route_points": 80,
    "local_radius_m": 80.0,
    "bev_resolution_m": 2.0,
    "bev_channels": 7,
    "num_candidate_prefixes": 24,
    "prefix_macro_whitelist": None,
    "num_reactive_futures": 4,
    "num_targeted_futures": 8,
    "num_roots": 8,
    "num_recovery_options": 24,
    "prefix_param_dim": 5,
    "margin_clip": 5.0,
    "root_margin_aggregation": "lcvar",
    "intra_root_lcvar_alpha": 0.2,
    "hidden_emergence_delay_steps": 2,
    "min_unknown_ratio_for_hidden": 0.01,
    "eps_signature": 0.30,
    "epsilon_obs": 1.0,
    "tau_obs": 1.4426950408889634,
    "wheelbase_m": 2.8,
    "speed_limit_default": 13.4,
    "route_width": 3.5,
    "route_dev_max_m": 2.5,
    "default_available_distance_m": 60.0,
    "d_safe0_m": 1.0,
    "safe_time_headway_s": 0.5,
    "comfort_brake_mps2": -3.0,
    "control_delay_s_default": 0.2,
    "delta_v_max_mps": 5.0,
    "yaw_rate_max_rps": 0.6,
    "future_priors": {"replay": 0.25, "reactive": 0.35, "targeted": 0.40},
    "control_limits": {"a_max": 3.0, "a_min": -6.0, "j_max": 6.0, "delta_max": 0.55, "steer_rate_max": 0.5, "v_max": 20.0},
    "margin_scales": {"distance": 2.0, "stop": 5.0, "accel": 1.0, "decel": 1.0, "steer": 0.1, "jerk": 2.0, "steer_rate": 0.1, "route": 1.0, "delta_v": 2.0, "yaw": 0.2, "inactive": 10.0},
    "obs_distance": {"s_c": 2.0, "s_v": 2.0, "s_p": 2.0, "s_yaw": 0.2, "lambda_psi": 0.5, "lambda_v": 0.5, "lambda_type": 2.0, "lambda_occ": 1.0, "lambda_ego": 0.5, "lambda_map": 0.5, "p_unmatch": 5.0},
    "utility_weights": {"progress": 1.0, "comfort": 0.05, "route": 0.5, "logdiv": 0.05, "offroad": 5.0, "wrongway": 5.0},
    "split_ratios": {"train": 0.70, "val": 0.10, "calibration": 0.10, "test": 0.10},
    "split": {"force_id": None},
    "regime_thresholds": {
        "tau_high": 1.0,
        "tau_d": 2.0,
        "tau_ttc": 3.0,
        "tau_occ": 0.05,
        # Normal/NUP examples in WOMD should be safe, non-artifact samples, but
        # they do not need a completely empty unknown corridor. Occlusion remains
        # a separate overlapping regime through tau_occ.
        "tau_normal_occ": 0.75,
        "tau_normal_dep": 0.50,
        "tau_prefix_hard": 0.0,
        "tau_prefix_harm": 0.05,
        "tau_contact": 0.8,
        "include_prefix_collision_in_near": False,
        "include_prefix_contact_in_post": False,
        "use_paper_regime_definitions": True,
        "require_uniform_for_normal": False,
    },
    "ocmero": {"alpha": 0.2, "beta": 0.2, "top_m": 8},
    "artifact": {
        "gamma_orc": 0.0,
        "gamma_dep": 0.0,
        "delta_neg": 0.0,
        "min_fraction_train_warning": 0.05,
        "force_mine": True,
        "mine_probability": 1.0,
        "compatible_margin": 1.2,
        "incompatible_margin": -6.0,
        "enable_branch_intent_margin": False,
        "branch_intent_compatible_margin": 1.0,
        "branch_intent_incompatible_margin": -2.5,
        "gap_margin": 0.5,
        "admission_gamma": 0.0,
    },
    "selection": {
        "gamma_rec": 0.0, "fixed_gamma_rec": 0.0, "gamma_H": 0.0, "gamma_D": 5.0,
        "ocrap_selector": "lcb_constrained", "lcb_beta": 0.10, "nominal_slack": 0.03,
        "nominal_slack_gap_limit": 0.50, "intervention_penalty": 0.03,
        "deviation_penalty": 0.15, "recovery_bonus": 0.02, "fallback_rec_weight": 0.10,
        "fallback_lcb_margin": 0.05, "fallback_gap_margin": 0.25,
        "nominal_fallback_lcb_slack": 0.05,
        "calibrated_shortfall_penalty": 1.0,
        "calibrated_gap_penalty": 0.05,
        "calibrated_admission_bonus": 0.02,
        "nominal_utility_slack": 0.05,
        "safe_nominal_slack": 0.12,
        "prefer_admitted": False,
        "switch_score_margin": 0.0,
        "safe_switch_score_margin": 0.10,
        "safe_min_rec_lcb_gain": 0.05,
        "safe_min_gap_reduction": 0.15,
        "budget_preserve_nominal": True,
        "budget_nominal_slack": 0.08,
        "deployability_bonus": 0.10,
        "contact_deployability_bonus": 0.40,
        "contact_gap_penalty": 0.10,
        "safe_hard_nominal_guard": True,
        "safe_nominal_max_gap": 0.20,
        "safe_override_require_both": True,
        "safe_min_drs_gain": 0.10,
        "safe_force_nominal_when_feasible": False,
        "safe_force_nominal_mode": "feasible",
        "drs_success_gamma": 0.0,
        "stress_preserve_nominal_min_drs_drop": -1.0,
        "require_admitted_intervention": False,
        "unadmitted_fallback_to_nominal": True,
        "intervention_macro_allowlist": "",
        "intervention_macro_blocklist": "",
        "intervention_require_macro": False,
        "intervention_budget_hard": False,
        "intervention_budget_hard_min_rec_gain": 0.0,
        "intervention_budget_hard_min_drs_gain": 0.0,
        "intervention_budget_hard_min_gap_reduction": 0.0,
        "intervention_min_pred_drs": -1.0,
        "intervention_max_pred_gap": -1.0,
        "require_intervention_evidence": False,
        "intervention_min_rec_lcb_gain": 0.00,
        "intervention_min_drs_gain": 0.00,
        "intervention_min_gap_reduction": 0.00,
        "option_drs_certificate": False,
        "option_drs_certificate_threshold": 1.01,
        "option_drs_certificate_max_gap": -1.0,
        "option_drs_certificate_rec_slack": 0.0,
        "option_drs_certificate_min_rec_lcb": -1.0e9,
        "option_drs_certificate_counts_as_evidence": True,
        "relative_recovery_certificate": False,
        "relative_recovery_nominal_rec_lcb_max": -1.0e9,
        "relative_recovery_nominal_gap_min": 1.0e9,
        "relative_recovery_nominal_drs_max": -1.0,
        "relative_recovery_min_rec_gain": 0.10,
        "relative_recovery_min_drs": 0.70,
        "relative_recovery_min_drs_gain": -1.0,
        "relative_recovery_max_drs_drop": -1.0,
        "relative_recovery_max_rec_lcb_drop": -1.0,
        "relative_recovery_min_improvement_axes": 1,
        "relative_recovery_max_gap": -1.0,
        "relative_recovery_max_gap_increase": 0.20,
        "relative_recovery_min_gap_reduction": -1.0,
        "relative_recovery_gate": "rec_gain",
        "relative_recovery_use_recovery_pool": False,
        "recovery_cert_max_hard": 0.0,
        "recovery_cert_max_harm": 5.0,
        "relative_recovery_bonus": 0.0,
        "relative_recovery_counts_as_evidence": True,
        "relative_recovery_macro_allowlist": "",
        "relative_recovery_macro_blocklist": "",
        "relative_recovery_require_macro": False,
        "relative_recovery_max_intervention_score_gain": -1.0,
        "protective_macro_certificate": False,
        "protective_macro_allowlist": "",
        "protective_macro_blocklist": "",
        "protective_macro_nominal_rec_lcb_max": -1.0e9,
        "protective_macro_nominal_gap_min": 1.0e9,
        "protective_macro_nominal_drs_max": -1.0,
        "protective_macro_min_drs": 0.60,
        "protective_macro_min_rec_lcb": -1.0e9,
        "protective_macro_min_rec_gain": -1.0,
        "protective_macro_min_gap_reduction": -1.0,
        "protective_macro_min_drs_gain": -1.0,
        "protective_macro_max_drs_drop": 0.05,
        "protective_macro_max_rec_lcb_drop": 0.10,
        "protective_macro_max_gap": -1.0,
        "protective_macro_max_gap_increase": 0.20,
        "protective_macro_max_hard": 0.0,
        "protective_macro_max_harm": 5.0,
        "protective_macro_min_improvement_axes": 1,
        "protective_macro_bonus": 0.0,
        "protective_macro_counts_as_evidence": True,
        "brake_rescue_certificate": False,
        "brake_rescue_macro_name": "brake",
        "brake_rescue_min_pred_drs": 0.65,
        "brake_rescue_min_pred_r_dep": -0.65,
        "brake_rescue_min_candidate_gap": 0.12,
        "brake_rescue_max_candidate_gap": 0.34,
        "brake_rescue_max_hard": 1.0,
        "brake_rescue_max_harm": 0.70,
        "brake_rescue_require_nominal_unadmitted": True,
        "brake_rescue_nominal_rec_lcb_max": 0.60,
        "brake_rescue_nominal_gap_min": 0.02,
        "brake_rescue_nominal_drs_max": 1.01,
        "brake_rescue_counts_as_evidence": True,
        "brake_rescue_budget_bypass": True,
        "brake_tail_rescue_certificate": False,
        "brake_tail_min_pred_drs": 0.78,
        "brake_tail_min_pred_r_dep": -0.55,
        "brake_tail_min_pred_pcd": 0.24,
        "brake_tail_min_candidate_gap": 0.10,
        "brake_tail_max_candidate_gap": 0.42,
        "brake_tail_high_gap_min": 0.34,
        "brake_tail_low_r_dep_max": 0.00,
        "brake_tail_max_hard": 1.0,
        "brake_tail_max_harm": 0.70,
        "brake_tail_require_nominal_low_headroom": True,
        "brake_tail_nominal_rec_lcb_max": 0.65,
        "brake_tail_nominal_gap_min": 0.02,
        "brake_tail_nominal_drs_max": 1.01,
        "brake_tail_counts_as_evidence": True,
        "brake_tail_budget_bypass": False,
        "brake_tail_challenge_budget_bypass": False,
        "brake_tail_challenge_cooldown_bypass": False,
        "brake_tail_challenge_bypass_pcd_gain": False,
        "brake_tail_challenge_min_pred_drs": 0.86,
        "brake_tail_challenge_min_pred_pcd": 0.30,
        "brake_tail_challenge_min_candidate_gap": 0.085,
        "brake_tail_challenge_max_candidate_gap": 0.42,
        "brake_tail_challenge_high_gap_min": 0.115,
        "brake_tail_challenge_low_r_dep_max": -0.14, "brake_tail_challenge_max_consecutive": -1, "brake_tail_min_nominal_deviation": 0.0,
        "pcd_rescue_certificate": False,
        "pcd_rescue_macro_allowlist": "",
        "pcd_rescue_macro_blocklist": "",
        "pcd_rescue_min_pred_pcd": 0.35,
        "pcd_rescue_min_pcd_gain": -1.0,
        "pcd_rescue_min_pred_drs": 0.70,
        "pcd_rescue_min_pred_r_dep": -0.70,
        "pcd_rescue_min_candidate_gap": 0.0,
        "pcd_rescue_max_candidate_gap": 0.50,
        "pcd_rescue_max_hard": 1.0,
        "pcd_rescue_max_harm": 0.70,
        "pcd_rescue_require_nominal_low_headroom": True,
        "pcd_rescue_require_nominal_unadmitted": False,
        "pcd_rescue_nominal_rec_lcb_max": 0.65,
        "pcd_rescue_nominal_gap_min": 0.02,
        "pcd_rescue_nominal_drs_max": 1.01,
        "pcd_rescue_nominal_low_headroom_min_axes": 1,
        "pcd_rescue_max_utility_drop": -1.0,
        "pcd_rescue_large_pcd_gain": 0.06,
        "pcd_rescue_bonus": 0.0,
        "pcd_rescue_counts_as_evidence": True,
        "pcd_rescue_budget_bypass": False,
        "stress_rescue_challenge_nominal": False,
        "rescue_challenge_min_candidate_gap": -1.0,
        "rescue_challenge_max_candidate_gap": -1.0,
        "rescue_challenge_min_pred_drs": -1.0,
        "rescue_challenge_min_pred_pcd": -1.0,
        "rescue_challenge_min_pcd_gain": -1.0,
        "rescue_challenge_min_rec_lcb_gain": -1.0,
        "rescue_challenge_min_drs_gain": -1.0,
        "rescue_challenge_min_gap_reduction": -1.0,
        "rescue_challenge_min_improvement_axes": 0,
        "rescue_challenge_macro_allowlist": "",
        "rescue_challenge_macro_blocklist": "",
        "rescue_challenge_max_pred_utility": -1.0,
        "rescue_challenge_max_used": -1,
        "rescue_challenge_score_pcd_weight": 1.0,
        "rescue_challenge_score_drs_weight": 0.15,
        "rescue_challenge_score_gap_weight": 0.25,
        "rescue_challenge_score_utility_weight": 0.02,
        "rescue_challenge_nominal_guard_min_pcd": -1.0,
        "rescue_challenge_nominal_guard_max_gap": -1.0,
        "intervention_cooldown_steps": 0,
        "steps_since_last_intervention": None,
        "safe_cert_min_pred_drs": 0.95,
        "safe_cert_max_pred_gap": 0.20,
        "safe_cert_rec_slack": 0.15,
        "stress_nominal_anchor": False,
        "stress_anchor_drs_floor": 0.90,
        "stress_anchor_max_gap": 0.30,
        "stress_anchor_rec_slack": 0.10,
        "stress_anchor_min_drs_gain": 0.06,
        "stress_anchor_min_rec_gain": 0.08,
        "stress_anchor_min_gap_reduction": 0.05,
        "intervention_budget_rate": None,
        "intervention_budget_penalty": 0.25,
        # v40 OC-UVRA: an uncertainty-aware direct value may challenge nominal
        # only after the candidate passes physical/semantic gates.  OC-MERO
        # remains the calibrated safety certificate.
        "direct_value_certificate": False,
        "direct_value_macro_allowlist": "brake,yield,merge,stabilize",
        "direct_value_lcb_z": 1.0,
        "direct_value_uncertainty_mode": "scaled",
        "direct_value_additive_q": 0.0,
        "direct_value_min_nominal_deviation": 0.0,
        "direct_value_min_advantage_lcb": 0.035,
        "direct_value_min_candidate_value": 0.45,
        "direct_value_max_candidate_std": 0.35,
        "direct_value_max_hard": 0.0,
        "direct_value_max_harm": 0.70,
        "direct_value_bonus": 0.15,
        "direct_value_counts_as_evidence": True,
        "direct_value_challenge_nominal": True,
        "direct_value_max_consecutive": 2,
        "direct_value_score_mode": False,
        "direct_value_opportunity_threshold": 0.0,
        "direct_value_harm_threshold": 1.0,
        "direct_value_top1_only": False,
        "direct_value_min_rank_margin": 0.0,
        "direct_value_conditional_rank_margin": False,
        "direct_value_risk_controlled_admission": False,
        "gamma_rec_by_bucket": {},
        "gamma_rec_by_bucket_file": None,
    },
    "calibration": {"deltas": [0.01, 0.05, 0.10], "numerical_margin": 0.0, "strict": True, "required_min_for_delta": 100},
    "model": {"d_model": 128, "d_z": 128, "d_obs": 64, "d_signature": 32, "d_future_signature": 32, "num_macros": 16, "no_occlusion_bev": False, "encoder_type": "mlp", "transformer_layers": 2, "transformer_heads": 4, "dropout": 0.1, "direct_recovery_value_head": False, "direct_recovery_value_pooling": "scene", "direct_recovery_value_output": "probability", "direct_recovery_value_regime_conditioning": False, "direct_recovery_value_num_regimes": 4, "direct_recovery_value_regime_dim": 16, "direct_recovery_opportunity_head": False, "direct_recovery_harm_head": False, "direct_recovery_value_experts": False, "direct_recovery_value_num_experts": 2, "direct_recovery_value_expert_routing": "bucket", "direct_recovery_value_router_temperature": 1.0, "direct_recovery_value_router_pooling": "candidate", "direct_recovery_expert_disagreement_penalty": 0.5, "direct_recovery_set_context": False, "direct_recovery_set_context_hidden": 192, "direct_recovery_set_context_dropout": 0.1},
    "training": {"device": "auto", "require_cuda": False, "progress": True, "batch_size": 16, "num_workers": 0, "epochs": 1, "lr": 0.001, "weight_decay": 0.0001, "grad_clip": 5.0, "artifact_sampler_weight": 0.25, "negative_deployable_sampler_weight": 0.75, "safe_positive_sampler_weight": 0.25, "regime_balance_power": 0.0, "option_success_temperature": 0.35, "early_stop_patience": 0, "dataset_profile": True, "dataset_profile_max_scalar_scan": 0, "root_target_mode": "recovery_signature", "val_dataset": None, "balanced_obs_loss": True, "group_batching": False, "group_batching_replacement": True, "group_batch_positive_best_macro_balance_power": 0.0, "group_ranking_margin": 0.25, "group_ranking_gap_weight": 0.25, "group_ranking_teacher_gap_weight": 0.25, "group_ranking_artifact_only": True, "group_ce_temperature": 0.35, "group_ce_pred_gap_weight": 0.35, "group_ce_teacher_gap_weight": 0.35, "group_ce_utility_weight": 0.03, "group_ce_require_deployable_target": True, "nominal_switch_margin": 0.12, "nominal_switch_pred_gap_weight": 0.30, "nominal_switch_teacher_gap_weight": 0.35, "nominal_switch_utility_weight": 0.03, "nominal_switch_teacher_gain_margin": 0.06, "nominal_switch_deployable_gamma": 0.0, "nominal_switch_gap_max": 0.30, "group_distill_pred_gap_weight": 0.45, "group_distill_teacher_gap_weight": 0.45, "group_distill_utility_weight": 0.02, "group_distill_teacher_temperature": 0.20, "group_distill_pred_temperature": 0.30, "safe_nominal_margin": 0.18, "safe_nominal_pred_gap_weight": 0.35, "safe_nominal_utility_weight": 0.03, "safe_nominal_drs_weight": 0.30, "safe_nominal_min_success": 0.90, "protective_macro_ids": "2,7", "protective_macro_bucket_ids": "2", "protective_macro_margin": 0.14, "protective_macro_min_teacher_r_dep": 0.0, "protective_macro_min_teacher_drs": 0.50, "protective_macro_min_teacher_pcd_gain": 0.02, "protective_macro_max_nominal_teacher_pcd": 0.90, "protective_macro_pred_gap_weight": 0.18, "protective_macro_pred_drs_weight": 0.65, "protective_macro_utility_weight": 0.02, "protective_macro_teacher_gap_weight": 0.10, "protective_macro_teacher_drs_weight": 0.70, "protective_macro_target_min_pred_drs": 0.62, "macro_drs_ids": "2,3,5,7", "macro_drs_bucket_ids": "1,2", "macro_drs_pos_threshold": 0.80, "macro_drs_neg_threshold": 0.05, "macro_drs_pos_weight": 4.0, "macro_drs_neg_weight": 1.0, "teacher_pcd_direct_macro_ids": "2,3,5,7", "teacher_pcd_direct_bucket_ids": "2", "teacher_pcd_direct_regression_weight": 1.0, "teacher_pcd_direct_ranking_weight": 2.5, "teacher_pcd_direct_nominal_penalty_weight": 1.0, "teacher_pcd_direct_false_positive_weight": 1.5, "teacher_pcd_direct_margin": 0.18, "teacher_pcd_direct_min_teacher_pcd_gain": 0.015, "teacher_pcd_direct_min_teacher_best_pcd": 0.50, "teacher_pcd_direct_max_nominal_teacher_pcd": 0.68, "teacher_pcd_direct_target_min_pred_pcd": 0.52, "teacher_pcd_direct_nominal_max_pred_pcd": 0.50, "teacher_pcd_direct_focus_non_nominal_weight": 2.0, "teacher_pcd_direct_false_positive_margin": 0.03, "teacher_pcd_direct_positive_rank_all_weight": 0.0, "teacher_pcd_direct_positive_floor_weight": 0.0, "teacher_pcd_direct_positive_min_pred_r_dep": -1000000000.0, "teacher_pcd_direct_positive_max_pred_gap": -1.0, "teacher_pcd_direct_positive_min_pred_drs": -1.0, "recovery_advantage_macro_ids": "2,3,5,7", "recovery_advantage_bucket_ids": "1,2", "recovery_advantage_positive_gain": 0.03, "recovery_advantage_negative_gain": 0.03, "recovery_advantage_margin": 0.10, "recovery_advantage_regression_weight": 1.0, "recovery_advantage_ranking_weight": 1.0, "recovery_advantage_component_weight": 0.5, "recovery_advantage_false_positive_weight": 0.75, "recovery_advantage_nominal_failure_pcd_max": 0.20, "recovery_advantage_target_min_pred_pcd": 0.50, "recovery_advantage_nominal_max_pred_pcd": 0.48, "recovery_advantage_near_weight": 1.5, "recovery_advantage_contact_weight": 1.0, "direct_value_bucket_ids": "1,2", "direct_value_macro_ids": "2,3,5,7", "direct_value_temperature": 0.12, "direct_value_positive_gain": 0.03, "direct_value_negative_gain": 0.02, "direct_value_rank_margin": 0.04, "direct_value_point_weight": 0.15, "direct_value_listwise_weight": 0.35, "direct_value_advantage_weight": 1.0, "direct_value_centered_weight": 1.0, "direct_value_positive_group_weight": 4.0, "direct_value_negative_group_weight": 1.0, "direct_value_ambiguous_group_weight": 0.25, "direct_value_near_weight": 1.5, "direct_value_contact_weight": 1.0, "direct_value_min_group_range": 0.01, "direct_value_false_positive_weight": 1.0, "direct_value_variance_floor": 0.0025, "direct_value_output_mode": "probability", "direct_value_pairwise_weight": 0.0, "direct_value_top_rank_weight": 0.0, "direct_value_policy_distill_weight": 0.0, "direct_value_policy_teacher_temperature": 0.08, "direct_value_policy_regret_weight": 0.0, "direct_value_policy_regret_margin": 0.0},
    "loss_weights": {"assign": 1.0, "sig": 0.5, "ib": 0.01, "obs": 1.0, "dep": 0.5, "orc": 0.5, "margin": 2.0, "anti_oracle": 1.0, "artifact_gap": 0.5, "admission": 0.2, "option_q": 0.5, "option_admission": 0.4, "option_success": 0.5, "option_success_bce": 0.5, "option_best": 0.2, "group_ranking": 0.0, "group_ce": 0.0, "nominal_switch": 0.0, "group_distill": 0.0, "safe_nominal": 0.0, "protective_macro": 0.0, "macro_drs": 0.0, "teacher_pcd_direct": 0.0, "recovery_advantage": 0.0, "direct_recovery_value": 0.0, "direct_router_balance": 0.0, "utility": 0.2},
    "evaluation": {"batch_size": 64, "delta": 0.05, "allow_infinite_gamma": False, "group_by_dataset": True, "fallback_to_all_if_empty_split": True, "use_running_intervention_budget": False, "require_calibrated_selector": False, "require_gamma_by_bucket": False, "methods": ["nominal", "log_replay", "idm_proxy", "mpc_proxy", "risk_aware", "backup_filter", "contingency", "oracle_filter", "ocrap"]},
    "closed_loop": {
        "require_calibrated_selector": False,
        "require_gamma_by_bucket": False,
        "max_scenarios": 8,
        "max_rollouts": None,
        "raw_max_scenarios": None,
        "bucket_dataset": None,
        "bucket_split": "",
        "max_bucket_targets": 0,
        "max_targets_per_scene": 1,
        "start_time_index": None,
        "max_steps": 40,
        "replan_interval_steps": 1,
        "method": "ocrap",
        "label_mode": "fast",
        "audit_every_n_steps": 1,
        "audit_max_labels": 0,
        "audit_auto_max_labels": 256,
        "audit_top_k": 4,
        "audit_max_extra_candidates": 5,
        "num_candidate_prefixes": None,
        "num_recovery_options": None,
        "external_sparse_labels": True,
        "external_label_max_candidates": None,
        "external_label_macro_diversity": True,
        "external_teacher_rollout_top_k_options": 4,
        "external_online_future_metrics": False,
        "exhaustive_teacher_labels": False,
        "artifact_mine_probability": 0.0,
        "render": False,
        "save_trace_npz": False,
        "save_partial": True,
        "resume": True,
        "resume_force": False,
        "resume_allow_legacy_partial": True,
        "resume_fsync": False,
        "partial_write_every_scenes": 4,
        "progress": True,
        "progress_every_steps": 5,
        "allow_infinite_gamma": False,
        "force_teacher_baselines": False,
    },
    "baselines": {"risk_lambda": 1.0, "idm_harm_lambda": 2.0, "idm_hard_lambda": 15.0},
    "metrics": {"sigma_u": 1.0},
    "dataset_quality": {
        "require_artifact_pairs": False,
        "artifact_pair_mode": "tag",
        "max_accepted_prefixes_per_scene_time": 0,
        "min_artifact_prefixes_per_scene_time": 1,
        "max_artifact_prefixes_per_scene_time": 2,
        "min_nonartifact_prefixes_per_scene_time": 1,
        "max_nonartifact_prefixes_per_scene_time": 6,
        "macro_diversity_first": True,
        "balanced_two_pass": True,
        "balanced_rotate_prefix_order": True,
        "balanced_keep_nominal_nonartifact": True,
        "require_nominal_per_scene_time": True,
        "keep_nominal_even_if_quality_fails": True,
        "min_accepted_prefixes_per_scene_time": 2,
        "require_nominal_regimes": [],
        "forbid_nominal_regimes": [],
        "require_any_regimes": [],
        "forbid_any_regimes": [],
        "min_uniform_times_per_scenario": 0,
        "nominal_regime_dataset": False,
        "early_nominal_regime_filter": True,
        "skip_forbidden_prefix_diagnostics": True,
        "max_quality_attempts_per_scene_time": 0,
        # For primary mixed builds, non-mined pass stays natural/nominal while
        # the mined pass may use the branch-specific oracle-artifact label.
        # Without this, mined hidden pairs often remain r_dep >= 0 under benign
        # Waymax metrics and the artifact quota silently becomes non-artifact.
        "artifact_pass_use_margin_override": True,
        # Count an artifact quota only when the final OC-MERO label is actually
        # an oracle artifact, not merely because a hidden pair was generated.
        "artifact_quota_uses_label": True,
        "warn_if_artifact_fraction_above": 0.80,
        "warn_if_scene_count_below": 50,
        "min_obs_negative_fraction_per_sample": 0.0,
        "min_deployable_score_per_sample": None,
        "min_oracle_score_per_sample": None,
        "drop_scene_time_if_under_min_quality": False,
        "require_negative_deployable_sample": False,
        "negative_deployable_threshold": 0.0,
    },
    "simulation_backend": "ocrap_surrogate",
    "progress": True,
    "io": {"compress_npz": True, "fsync_npz": True},
    "profiling": {"enabled": False, "log_every_sample": False, "slow_sample_s": 30.0, "slow_scene_time_s": 120.0, "profile_flush_scene_times": 1, "profile_csv_fsync": False},
    "scenario_start_index": 0,
    "scenario_stride": 1,
    "scenario_worker_index": 0,
    "waymax": {
        "append_scenario_index_to_id": True,
        "strict": True,
        "dataloader_include_sdc_paths": True,
        "num_paths": 45,
        "num_points_per_path": 800,
        "max_num_rg_points": 30000,
        "init_history_steps": 11,
        "prefix_dynamics": "invertible_bicycle",
        "debug_prefix_dynamics": "state",
        "control_non_sdc": "log_playback",
        "allow_new_objects_after_warmup": True,
        "enable_augmented_hidden_roots": True,
        "augmented_hidden_from_unknown_only": True,
        "metrics_to_run": ["log_divergence", "overlap", "offroad", "sdc_wrongway", "sdc_off_route", "sdc_progression", "kinematic_infeasibility"],
        "jax_platforms": "cuda,cpu",
        "preallocate_gpu_memory": False,
        "cache_identical_teacher_rollouts": True,
        "cache_env_objects": True,
        "cache_postprefix_rollouts": True,
        "cache_teacher_metric_rollouts": True,
        "use_jit_scan_rollouts": True,
        "compute_future_metrics": True,
        "detect_natural_hidden_emergence": True,
        "teacher_backend": "auto",
        "teacher_metrics_stride": 0,
        "teacher_rollout_top_k_options": 0,
        "teacher_rollout_option_modes": [],
        # In screened-hybrid mode, screened-out options still need the same
        # branch-specific mined-pair label as rolled options. Otherwise top-k
        # rollout can leave incompatible options structurally positive and erase
        # FRA/ODG artifacts.
        "apply_artifact_override_to_screened_options": True,
        # Optional smoke/debug acceleration: when a mined hidden pair is being
        # explicitly labeled by the branch override, skip Waymax recovery rollout
        # for that augmented future and use the override/structural label row.
        # Keep false for strict final runs unless this approximation is reported.
        "skip_waymax_rollout_for_augmented_override": False,
    },
    "ablation": {"without_observation_kernel": False, "without_lower_tail": False, "without_calibration": False, "without_anti_oracle": False, "full_future_roots": False, "no_occlusion_bev": False},
}


def repo_default_config_path() -> Path | None:
    p = Path(__file__).resolve().parents[3] / "configs" / "default.yaml"
    return p if p.exists() else None


def get_default_config() -> dict[str, Any]:
    p = repo_default_config_path()
    if p is not None:
        with p.open("r", encoding="utf-8") as f:
            loaded = yaml.safe_load(f) or {}
        return deep_update(DEFAULT_CONFIG.copy(), loaded)
    return DEFAULT_CONFIG.copy()


def deep_update(base: dict[str, Any], upd: dict[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for k, v in (upd or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_update(out[k], v)
        else:
            out[k] = v
    return out
